//! Deterministic lower infrastructure platform.

use ratatui::style::Color;

#[derive(Debug, Clone, Copy)]
pub struct GlowBase {
    pub width: u16,
    pub rows: u16,
}

impl GlowBase {
    pub const fn new(width: u16, rows: u16) -> Self {
        Self { width, rows }
    }
    pub fn color_at(&self, x: u16, row: u16, active: bool, failed: bool) -> Color {
        self.color_at_state(x, row, active, false, failed, 1.0)
    }

    /// Render the platform from truthful presentation state. `pulse` is a
    /// bounded brightness multiplier generated by the time-based render loop;
    /// it never changes the semantic state or fabricates install progress.
    pub fn color_at_state(
        &self,
        x: u16,
        row: u16,
        active: bool,
        complete: bool,
        failed: bool,
        pulse: f32,
    ) -> Color {
        let center = self.width.saturating_sub(1) as f32 / 2.0;
        let distance = ((x as f32 - center).abs() / center.max(1.0)).min(1.0);
        if failed {
            return if row == 0 {
                Color::Red
            } else {
                Color::Rgb(120, 60, 20)
            };
        }
        if complete {
            return if distance < 0.4 {
                Color::Green
            } else {
                Color::Rgb(20, 110, 55)
            };
        }
        if active {
            let bright = pulse.clamp(0.55, 1.0);
            if row > self.rows / 2 && distance > 0.55 {
                // Restrained violet/magenta reflections sit beneath the
                // cyan/electric-blue infrastructure layers.
                if distance > 0.8 {
                    Color::Magenta
                } else {
                    Color::Rgb(138, 92, 255)
                }
            } else if row == 0 || distance < 0.35 {
                if bright > 0.82 {
                    Color::Cyan
                } else {
                    Color::Blue
                }
            } else {
                Color::Blue
            }
        } else {
            Color::DarkGray
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn platform_is_deterministic() {
        let b = GlowBase::new(20, 4);
        assert_eq!(b.color_at(10, 0, true, false), Color::Cyan);
    }

    #[test]
    fn active_platform_pulse_is_bounded_and_completion_is_green() {
        let b = GlowBase::new(120, 8);
        let dim = b.color_at_state(60, 0, true, false, false, 0.55);
        let bright = b.color_at_state(60, 0, true, false, false, 0.9);
        assert_ne!(dim, bright);
        assert_eq!(
            b.color_at_state(60, 0, false, true, false, 0.7),
            Color::Green
        );
    }

    #[test]
    fn failure_platform_is_red_and_amber() {
        let b = GlowBase::new(20, 4);
        assert_eq!(b.color_at_state(10, 0, false, false, true, 0.7), Color::Red);
        assert_eq!(
            b.color_at_state(10, 2, false, false, true, 0.7),
            Color::Rgb(120, 60, 20)
        );
    }
}
