// Generated by generate-spec135-mission-canvas-derived-contracts.py. Do not edit.
import type { ActivityMode, CanvasDraftState, HostLifecycleState, HostRendererResolution, LayoutMutationResult, OmissionDiagnostic, ProfileLayoutMemory, ProjectionLifecycleEvent, RecompositionEvidence, RecompositionReceipt, RegistryEntry, ResolvedWorkspaceProjection, WorkspaceProfile } from './mission-canvas-types.generated';

export interface MissionCanvasTransport {
  request<T>(operationId: string, input?: unknown): Promise<T>;
}

export class MissionCanvasClient {
  constructor(private readonly transport: MissionCanvasTransport) {}

  projectionGet(input?: unknown): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.projection.get", input);
  }

  projectionResolve(input?: unknown): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.projection.resolve", input);
  }

  profileList(input?: unknown): Promise<Array<WorkspaceProfile>> {
    return this.transport.request<Array<WorkspaceProfile>>("focusa.mission_canvas.profile.list", input);
  }

  profileSelect(input?: unknown): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.profile.select", input);
  }

  profileGet(input?: unknown): Promise<WorkspaceProfile> {
    return this.transport.request<WorkspaceProfile>("focusa.mission_canvas.profile.get", input);
  }

  activityList(input?: unknown): Promise<Array<ActivityMode>> {
    return this.transport.request<Array<ActivityMode>>("focusa.mission_canvas.activity.list", input);
  }

  activitySelect(input?: unknown): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.activity.select", input);
  }

  domain_packInstall(input?: unknown): Promise<unknown> {
    return this.transport.request<unknown>("focusa.mission_canvas.domain_pack.install", input);
  }

  registryList(input?: unknown): Promise<Array<RegistryEntry>> {
    return this.transport.request<Array<RegistryEntry>>("focusa.mission_canvas.registry.list", input);
  }

  layout_memoryGet(input?: unknown): Promise<ProfileLayoutMemory> {
    return this.transport.request<ProfileLayoutMemory>("focusa.mission_canvas.layout_memory.get", input);
  }

  layout_memoryUpdate(input?: unknown): Promise<RecompositionReceipt> {
    return this.transport.request<RecompositionReceipt>("focusa.mission_canvas.layout_memory.update", input);
  }

  layoutMutate(input?: unknown): Promise<LayoutMutationResult> {
    return this.transport.request<LayoutMutationResult>("focusa.mission_canvas.layout.mutate", input);
  }

  rich_hostResolve(input?: unknown): Promise<HostRendererResolution> {
    return this.transport.request<HostRendererResolution>("focusa.mission_canvas.rich_host.resolve", input);
  }

  rich_hostLaunch(input?: unknown): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.launch", input);
  }

  rich_hostFocus(input?: unknown): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.focus", input);
  }

  rich_hostHide(input?: unknown): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.hide", input);
  }

  rich_hostClose(input?: unknown): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.close", input);
  }

  draftGet(input?: unknown): Promise<CanvasDraftState> {
    return this.transport.request<CanvasDraftState>("focusa.mission_canvas.draft.get", input);
  }

  draftSync(input?: unknown): Promise<CanvasDraftState> {
    return this.transport.request<CanvasDraftState>("focusa.mission_canvas.draft.sync", input);
  }

  recipientResolve(input?: unknown): Promise<unknown> {
    return this.transport.request<unknown>("focusa.mission_canvas.recipient.resolve", input);
  }

  recompositionEvidenceGet(input?: unknown): Promise<RecompositionEvidence> {
    return this.transport.request<RecompositionEvidence>("focusa.mission_canvas.recomposition.evidence.get", input);
  }

  recompositionReceiptGet(input?: unknown): Promise<RecompositionReceipt> {
    return this.transport.request<RecompositionReceipt>("focusa.mission_canvas.recomposition.receipt.get", input);
  }

  recompositionDiagnosticsList(input?: unknown): Promise<Array<OmissionDiagnostic>> {
    return this.transport.request<Array<OmissionDiagnostic>>("focusa.mission_canvas.recomposition.diagnostics.list", input);
  }

  pi_sessionEventAppend(input?: unknown): Promise<unknown> {
    return this.transport.request<unknown>("focusa.mission_canvas.pi_session.event.append", input);
  }

  eventsStream(input?: unknown): Promise<Array<ProjectionLifecycleEvent>> {
    return this.transport.request<Array<ProjectionLifecycleEvent>>("focusa.mission_canvas.events.stream", input);
  }
}
