// Generated by generate-spec135-mission-canvas-derived-contracts.py. Do not edit.

export type AccessibilityDescriptor = {
  "description"?: string | null;
  "focus_semantic_id": string;
  "keyboard_operation_ids"?: Array<string>;
  "label": string;
  "landmark_role": string;
  "live_region"?: "off" | "polite" | "assertive";
};

export type ActivityMode = {
  "activity_mode_id": string;
  "candidate_contribution_ids": Array<ContributionId>;
  "display_name": string;
  "revision": number;
  "terminology_overrides_ref"?: string | null;
  "viability_rule_revision": string;
};

export type ActorRef = {
  "actor_id": string;
  "actor_type": "operator" | "agent" | "pi" | "desktop" | "web" | "service";
};

export type AttachmentId = string;

export type AttachmentKey = {
  "attachment_id": AttachmentId;
  "continuity_id"?: ContinuityId | null;
  "instance_id": InstanceId;
  "session_id": SessionId;
  "workspace_binding_id": WorkspaceBindingId;
  "workstream": WorkstreamKey;
};

export type AuthorityContext = {
  "authority_ref": string;
  "envelope": AuthorityEnvelope;
};

export type AuthorityDescriptor = {
  "approval_required"?: boolean;
  "attachment"?: AttachmentKey | null;
  "canonical_owner": string;
  "contention_ref"?: string | null;
  "continuity_id"?: ContinuityId | null;
  "mutation_owner": string;
  "read_only": boolean;
  "runtime_object"?: RuntimeObjectRef | null;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type AuthorityEnvelope = {
  "status": "canonical" | "blocked" | "degraded" | "missing" | "stale";
  "why": string;
};

export type CandidateContribution = {
  "active_work_surface_relationships"?: Array<"focused" | "open" | "pinned" | "contextual" | "aggregate" | "none">;
  "applicable_activity_mode_ids": Array<string>;
  "applicable_profile_ids": Array<string>;
  "candidate_revision"?: number;
  "canonical_content_refs": Array<CanonicalRef>;
  "configuration_ref"?: string | null;
  "contribution_id": ContributionId;
  "geometry": GeometryPreference;
  "kind": ContributionKind;
  "preference_ref"?: string | null;
  "priority": number;
  "renderer_binding_id": RendererBindingId;
  "required_capabilities": Array<string>;
  "required_operations": Array<string>;
  "required_permissions": Array<string>;
  "semantic_binding_id": SemanticBindingId;
};

export type CanonicalRef = {
  "freshness"?: "current" | "stale" | "unknown" | "not_applicable";
  "kind": string;
  "ref": string;
  "revision": number | string;
};

export type CanvasDraftState = {
  "attachment": AttachmentKey;
  "conflict_ref"?: string | null;
  "content": string;
  "content_sha256": string;
  "continuity_id"?: ContinuityId | null;
  "draft_id": string;
  "draft_revision": number;
  "idempotency_key": string;
  "owner": "pi_editor" | "canvas_prompt_editor";
  "recipient_ref": string;
  "runtime_object"?: RuntimeObjectRef | null;
  "selection_end"?: number;
  "selection_start"?: number;
  "sync_state": "synchronized" | "pi_newer" | "canvas_newer" | "conflict" | "offline";
  "updated_at": string;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type CapabilityProjection = {
  "attachment"?: AttachmentKey | null;
  "available_operation_ids": Array<string>;
  "capabilities": Array<string>;
  "capability_revision": number;
  "continuity_id"?: ContinuityId | null;
  "observed_at": string;
  "permissions": Array<string>;
  "runtime_object"?: RuntimeObjectRef | null;
  "unavailable_operations": Array<UnavailableOperationDiagnostic>;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type ContinuityId = string;

export type ContributionEligibilityContext = {
  "activity_mode_id": string;
  "activity_mode_revision": number;
  "attachment"?: AttachmentKey | null;
  "available_operations": Array<string>;
  "canonical_read_model_revision": number;
  "capabilities": Array<string>;
  "continuity_id"?: ContinuityId | null;
  "focused_work_surface_id": WorkSurfaceId | null;
  "observed_at"?: string;
  "open_work_surface_ids"?: Array<WorkSurfaceId>;
  "permissions": Array<string>;
  "pinned_work_surface_ids"?: Array<WorkSurfaceId>;
  "project_constraint_refs": Array<string>;
  "resolver_rule_revision": string;
  "runtime_object"?: RuntimeObjectRef | null;
  "user_preference_ref": string | null;
  "viewport": ViewportDescriptor;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workspace_profile_id": string;
  "workspace_profile_revision": number;
  "workstream": WorkstreamKey;
};

export type ContributionId = string;

export type ContributionKind = "work_surface_strip" | "focused_work_surface" | "inspector" | "inspector_section" | "work_rail" | "steering_queue" | "follow_up_queue" | "prompt_editor" | "scope_bar" | "activity_navigation" | "toolbar_control" | "contextual_action" | "transient_notification" | "generated_surface";

export type ContributionPlacementPreference = {
  "contribution_id": ContributionId;
  "last_compatible_layout_node_id"?: string | null;
  "maximum_span": number;
  "minimum_span": number;
  "preferred_adjacency"?: Array<ContributionId>;
  "preferred_order": number;
  "preferred_regions": Array<RegionKind>;
};

export type DomainPackInstallReceipt = {
  "installed": boolean;
  "pack_id": string;
  "receipt_ref": string;
  "schema": "focusa.mission_canvas.domain_pack_install_receipt.v1";
  "workstream": WorkstreamKey;
};

export type EligibilityDecision = {
  "contribution_id": ContributionId;
  "evidence_refs"?: Array<string>;
  "merged_into_contribution_id"?: ContributionId | null;
  "omission"?: OmissionDiagnostic | null;
  "outcome": "eligible" | "omitted" | "merged" | "compacted" | "suspended";
  "projection_revision": number;
  "rule_revision": string;
};

export type FreshnessDescriptor = {
  "observed_at": string;
  "refresh_operation_id"?: string | null;
  "stale_reason"?: string | null;
  "status": "current" | "stale" | "unknown" | "not_applicable";
};

export type GeometryPreference = {
  "inspector_side"?: "start" | "end" | "profile_default" | "none";
  "maximum_span": number;
  "merge_policy": "never" | "compatible" | "preferred";
  "minimum_span": number;
  "preferred_adjacency"?: Array<ContributionId>;
  "preferred_order"?: number;
  "preferred_regions": Array<RegionKind>;
  "tab_policy": "never" | "compatible" | "preferred";
};

export type GridLayoutNode = {
  "children": Array<LayoutNode>;
  "columns": number;
  "gap_token"?: string;
  "kind": "grid";
  "node_id": string;
};

export type HostLifecycleState = {
  "attachment"?: AttachmentKey | null;
  "canvas_draft_ref"?: string | null;
  "continuity_id"?: ContinuityId | null;
  "durable_event_cursor": string;
  "focused": boolean;
  "host_instance_id": string;
  "last_error_ref"?: string | null;
  "lifecycle_revision": number;
  "pi_draft_ref"?: string | null;
  "process_id"?: number | null;
  "renderer_resolution": HostRendererResolution;
  "runtime_object"?: RuntimeObjectRef | null;
  "state": "absent" | "launching" | "visible" | "focused" | "hidden" | "closing" | "reconnecting" | "failed";
  "updated_at": string;
  "window_id"?: string | null;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type HostRendererResolution = {
  "asset_digest"?: string | null;
  "asset_version"?: string | null;
  "attachment"?: AttachmentKey | null;
  "availability": "available" | "fallback" | "unavailable" | "headless";
  "continuity_id"?: ContinuityId | null;
  "diagnostic_ref"?: string | null;
  "interaction_mode": "canvas-guided" | "terminal-guided" | "headless";
  "platform": "macOS" | "Windows" | "Linux";
  "resolution_reason": string;
  "resolver_revision": string;
  "runtime_object"?: RuntimeObjectRef | null;
  "selected_renderer": "focusa_desktop_tauri" | "focusa_pi_rich_window" | "uiai_engine_cockpit" | "mission_deck_web" | "pi_terminal_projection" | "native_tui" | "menubar_peek" | "headless_none";
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream"?: WorkstreamKey;
};

export type HostScopeKey = {
  "canonical_name": string;
  "fingerprint": string;
  "root_path": string;
  "scope_id": string;
  "scope_kind": "host";
};

export type InspectorLayoutNode = {
  "inspector_contribution_ids": Array<ContributionId>;
  "kind": "inspector";
  "node_id": string;
  "primary": LayoutNode;
  "side": "start" | "end";
  "span"?: number;
};

export type InstanceId = string;

export type LayoutMutationCommand = {
  "action": "open" | "focus" | "pin" | "unpin" | "group" | "ungroup" | "reorder" | "split_horizontal" | "split_vertical" | "resize_split" | "compare" | "suspend_projection" | "rehydrate" | "close_projection" | "set_active_tab";
  "attachment": AttachmentKey;
  "command_id": string;
  "continuity_id"?: ContinuityId | null;
  "expected_layout_revision": number;
  "expected_projection_revision": number;
  "idempotency_key": string;
  "requested_at"?: string;
  "runtime_object"?: RuntimeObjectRef | null;
  "secondary_work_surface_id"?: WorkSurfaceId | null;
  "split_ratio"?: number | null;
  "target_contribution_id"?: ContributionId | null;
  "target_index"?: number | null;
  "target_layout_node_id"?: string | null;
  "target_work_surface_id"?: WorkSurfaceId | null;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type LayoutMutationResult = {
  "accepted": boolean;
  "attachment"?: AttachmentKey | null;
  "command_id": string;
  "continuity_id"?: ContinuityId | null;
  "error_ref"?: string | null;
  "event_cursor": string;
  "evidence_ref"?: string | null;
  "layout_revision": number;
  "projection_digest": ProjectionDigest;
  "projection_revision": number;
  "receipt_ref"?: string | null;
  "runtime_object"?: RuntimeObjectRef | null;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type LayoutNode = SingleLayoutNode | SplitLayoutNode | StackLayoutNode | GridLayoutNode | TabLayoutNode | InspectorLayoutNode;

export type LegacyExactScopeCompatibilityInput = {
  "attachment_id": string;
  "continuity_id": string;
  "instance_id"?: string | null;
  "project_root": string;
  "session_id": string;
  "working_subpath_id"?: string | null;
};

export type LegacyLayoutMapping = {
  "diagnostic_ref"?: string | null;
  "legacy_ref": string;
  "mapping_status": "mapped" | "omitted" | "manual_review";
  "target_contribution_id": ContributionId;
};

export type LegacyLayoutMigrationEnvelope = {
  "attachment"?: AttachmentKey | null;
  "continuity_id"?: ContinuityId | null;
  "created_at": string;
  "error_ref"?: string | null;
  "idempotency_key": string;
  "mappings": Array<LegacyLayoutMapping>;
  "migration_id": string;
  "preserved_draft_ref": string | null;
  "runtime_object"?: RuntimeObjectRef | null;
  "source_digest": string;
  "source_kind": "terminal_local" | "process_local" | "legacy_canvas" | "imported_snapshot";
  "source_revision": number | string;
  "status": "pending" | "validated" | "applied" | "rejected" | "rolled_back";
  "target_activity_mode_id": string;
  "target_layout_memory_ref"?: string | null;
  "target_profile_id": string;
  "warning_refs"?: Array<string>;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type OmissionDiagnostic = {
  "canonical_input_refs": Array<CanonicalRef>;
  "contribution_id": ContributionId;
  "details_ref"?: string | null;
  "observed_at": string;
  "projection_revision": number;
  "reason": OmissionReason;
  "rule_revision": string;
};

export type OmissionReason = "no_relevant_content" | "not_applicable" | "capability_not_present" | "not_authorized" | "merged" | "compacted" | "suspended" | "viewport_omitted";

export type OperationBinding = {
  "authority_ref": string;
  "confirmation"?: "none" | "preview" | "explicit";
  "disabled_reason_ref"?: string | null;
  "enabled": boolean;
  "operation_id": string;
  "target_contribution_id": ContributionId;
};

export type PiSessionEventReceipt = {
  "accepted": boolean;
  "event_id": string;
  "receipt_ref": string;
  "schema": "focusa.mission_canvas.pi_session_event_receipt.v1";
  "workstream": WorkstreamKey;
};

export type ProfileLayoutMemory = {
  "absent_contribution_ids": Array<ContributionId>;
  "activity_mode_id": string;
  "attachment"?: AttachmentKey | null;
  "continuity_id"?: ContinuityId | null;
  "focused_semantic_target"?: string | null;
  "idempotency_key": string;
  "memory_id": string;
  "memory_revision": number;
  "placements": Array<ContributionPlacementPreference>;
  "profile_id": string;
  "runtime_object"?: RuntimeObjectRef | null;
  "updated_at": string;
  "viewport_class": "minimum" | "compact" | "standard" | "productive" | "wide" | "reference_capture";
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type ProjectRootKey = {
  "canonical_name": string;
  "fingerprint": string;
  "root_path": string;
  "scope_id": string;
  "scope_kind": "project";
};

export type ProjectionDigest = string;

export type ProjectionEventKind = "candidate_discovered" | "contribution_eligible" | "contribution_omitted" | "contribution_merged" | "projection_resolved" | "layout_changed" | "focus_changed" | "profile_changed" | "activity_mode_changed" | "capability_changed" | "host_launch_requested" | "host_visible" | "host_focused" | "host_hidden" | "host_closed" | "host_reconnected" | "host_failed" | "draft_synchronized" | "draft_conflict" | "projection_suspended" | "projection_rehydrated" | "migration_started" | "migration_completed" | "migration_failed" | "pi_turn_started" | "pi_turn_completed" | "pi_message_updated" | "pi_tool_started" | "pi_tool_completed";

export type ProjectionLifecycleEvent = {
  "attachment"?: AttachmentKey | null;
  "causation_id"?: string | null;
  "continuity_id"?: ContinuityId | null;
  "contribution_id"?: ContributionId | null;
  "correlation_id"?: string | null;
  "event_cursor": string;
  "event_id": string;
  "event_kind": ProjectionEventKind;
  "evidence_refs": Array<string>;
  "host_instance_id"?: string | null;
  "layout_revision": number;
  "occurred_at": string;
  "payload_ref": string;
  "projection_revision": number;
  "receipt_refs": Array<string>;
  "runtime_object"?: RuntimeObjectRef | null;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type RecipientResolution = {
  "attachment"?: AttachmentKey | null;
  "continuity_id"?: ContinuityId | null;
  "recipient_ref": string;
  "routable": boolean;
  "runtime_object"?: RuntimeObjectRef | null;
  "schema": "focusa.mission_canvas.recipient_resolution.v1";
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type RecompositionEvidence = {
  "attachment"?: AttachmentKey | null;
  "candidate_contribution_ids": Array<ContributionId>;
  "continuity_id"?: ContinuityId | null;
  "diagnostic_refs"?: Array<string>;
  "eligibility_decisions": Array<EligibilityDecision>;
  "evidence_id": string;
  "input_projection_digest": ProjectionDigest | null;
  "layout_decision_refs"?: Array<string>;
  "observed_at": string;
  "output_projection_digest": ProjectionDigest;
  "rule_revision": string;
  "runtime_object"?: RuntimeObjectRef | null;
  "trigger": "canonical_read_change" | "profile_change" | "activity_mode_change" | "focus_change" | "viewport_change" | "capability_change" | "preference_change" | "migration" | "explicit_resolve";
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type RecompositionReceipt = {
  "accepted": boolean;
  "attachment"?: AttachmentKey | null;
  "continuity_id"?: ContinuityId | null;
  "error_ref"?: string | null;
  "event_cursor": string;
  "evidence_id": string;
  "idempotency_key": string;
  "issued_at": string;
  "layout_revision": number;
  "projection_digest": ProjectionDigest;
  "projection_revision": number;
  "receipt_id": string;
  "runtime_object"?: RuntimeObjectRef | null;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type RegionKind = "primary" | "secondary" | "inspector" | "rail" | "queue" | "composer" | "navigation" | "overlay";

export type RegistryEntry = {
  "enabled": boolean;
  "entry_id": string;
  "payload_ref": string;
  "registry_kind": "WorkspaceProfileRegistry" | "ActivityModeRegistry" | "PanelRegistry" | "HomeCanvasRegistry" | "WorkSurfaceRendererRegistry" | "ArtifactRendererRegistry" | "TerminologyRegistry" | "DomainSemanticBindingRegistry";
  "required_capabilities"?: Array<string>;
  "required_permissions"?: Array<string>;
  "revision": number;
  "schema_ref": string;
  "supersedes_entry_id"?: string | null;
};

export type RendererBindingId = string;

export type ResolvedContribution = {
  "accessibility": AccessibilityDescriptor;
  "authority": AuthorityDescriptor;
  "contribution_id": ContributionId;
  "contribution_revision": number;
  "data_ref": CanonicalRef;
  "evidence_refs"?: Array<string>;
  "freshness": FreshnessDescriptor;
  "kind": ContributionKind;
  "operation_ids": Array<string>;
  "renderer_binding_id": RendererBindingId;
  "resolved_geometry": GeometryPreference;
  "semantic_binding_id": SemanticBindingId;
};

export type ResolvedWorkspaceProjection = {
  "activity_mode_id": string;
  "activity_mode_revision": number;
  "attachment"?: AttachmentKey | null;
  "candidate_contribution_ids": Array<ContributionId>;
  "canonical_read_model_revision": number;
  "continuity_id"?: ContinuityId | null;
  "durable_event_cursor": string;
  "eligible_contributions": Array<ResolvedContribution>;
  "evidence_refs"?: Array<string>;
  "focused_semantic_target": string;
  "focused_work_surface_id": WorkSurfaceId | null;
  "layout_revision": number;
  "layout_tree": LayoutNode;
  "omission_diagnostics": Array<OmissionDiagnostic>;
  "operation_bindings": Array<OperationBinding>;
  "projection_digest": ProjectionDigest;
  "projection_revision": number;
  "receipt_refs"?: Array<string>;
  "resolved_at"?: string;
  "runtime_object"?: RuntimeObjectRef | null;
  "schema": "focusa.resolved_workspace_projection.v1";
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workspace_profile_id": string;
  "workspace_profile_revision": number;
  "workstream": WorkstreamKey;
};

export type ResponsiveEvaluationFixture = {
  "activity_mode_id": string;
  "candidate_contribution_ids": Array<ContributionId>;
  "expected_eligible_contribution_ids": Array<ContributionId>;
  "expected_layout_kinds": Array<"single" | "split" | "stack" | "grid" | "tabs" | "inspector">;
  "expected_omissions": Array<{
  "contribution_id": ContributionId;
  "reason": OmissionReason;
}>;
  "fixture_id": string;
  "maximum_visible_contributions"?: number | null;
  "minimum_primary_span": number;
  "must_preserve_focus"?: boolean;
  "profile_id": string;
  "viewport": ViewportDescriptor;
};

export type RuntimeObjectRef = {
  "runtime_id": string;
  "runtime_kind": string;
};

export type ScopeRef = {
  "scope_key": ProjectRootKey;
  "scope_kind": "project";
} | {
  "scope_key": HostScopeKey;
  "scope_kind": "host";
};

export type SemanticBindingId = string;

export type SessionId = string;

export type SingleLayoutNode = {
  "contribution_id": ContributionId;
  "kind": "single";
  "node_id": string;
};

export type SplitLayoutNode = {
  "children": Array<LayoutNode>;
  "kind": "split";
  "node_id": string;
  "orientation": "horizontal" | "vertical";
  "ratio": number;
};

export type StackLayoutNode = {
  "children": Array<LayoutNode>;
  "gap_token"?: string;
  "kind": "stack";
  "node_id": string;
};

export type TabLayoutNode = {
  "active_contribution_id": ContributionId;
  "contribution_ids": Array<ContributionId>;
  "kind": "tabs";
  "node_id": string;
};

export type UnavailableOperationDiagnostic = {
  "diagnostic_ref": string;
  "operation_id": string;
  "reason": "capability_not_present" | "not_authorized" | "not_applicable" | "suspended" | "offline";
};

export type ViewportDescriptor = {
  "class": "minimum" | "compact" | "standard" | "productive" | "wide" | "reference_capture";
  "css_height": number;
  "css_width": number;
  "device_pixel_ratio": number;
  "high_contrast"?: boolean;
  "platform": "macOS" | "Windows" | "Linux";
  "reduced_motion"?: boolean;
  "reduced_transparency"?: boolean;
  "text_scale_percent"?: number;
  "zoom_percent"?: 100 | 125 | 150 | 200;
};

export type WorkSurfaceId = string;

export type WorkSurfaceIdentity = {
  "attachment"?: AttachmentKey | null;
  "continuity_id"?: ContinuityId | null;
  "runtime_object"?: RuntimeObjectRef | null;
  "work_surface_id": WorkSurfaceId;
  "workstream": WorkstreamKey;
};

export type WorkspaceBindingId = string;

export type WorkspaceProfile = {
  "candidate_contribution_ids": Array<ContributionId>;
  "density": "comfortable" | "standard" | "compact" | "dense";
  "display_name": string;
  "domain_semantic_binding_registry_ref"?: string | null;
  "installed"?: boolean;
  "profile_id": string;
  "renderer_registry_ref": string;
  "revision": number;
  "terminology_registry_ref": string;
  "viability_rule_revision": string;
};

export type WorkstreamAuthorityContext = {
  "attachment"?: AttachmentKey | null;
  "continuity_id"?: ContinuityId | null;
  "runtime_object"?: RuntimeObjectRef | null;
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};

export type WorkstreamId = string;

export type WorkstreamKey = {
  "scope": ScopeRef;
  "workstream_id": WorkstreamId;
};

export type WorkstreamOperationRequest = {
  "actor": ActorRef;
  "attachment"?: AttachmentKey | null;
  "authority": AuthorityContext;
  "command_id": string;
  "continuity_id"?: ContinuityId | null;
  "expected_fencing_token"?: number | null;
  "expected_revision"?: number | null;
  "idempotency_key"?: string | null;
  "input": unknown;
  "runtime_object"?: RuntimeObjectRef | null;
  "schema": "focusa.workstream_operation_request.v1";
  "work_surface_id"?: WorkSurfaceId | null;
  "workspace_binding_id"?: WorkspaceBindingId | null;
  "workstream": WorkstreamKey;
};
