// Generated by generate-spec135-mission-canvas-derived-contracts.py. Do not edit.
import type { ActivityMode, CanvasDraftState, DomainPackInstallReceipt, HostLifecycleState, HostRendererResolution, LayoutMutationResult, OmissionDiagnostic, PiSessionEventReceipt, ProfileLayoutMemory, ProjectionLifecycleEvent, RecipientResolution, RecompositionEvidence, RecompositionReceipt, RegistryEntry, ResolvedWorkspaceProjection, WorkspaceProfile, WorkstreamAuthorityContext } from './mission-canvas-types.generated';

/** Every generated operation input is Workstream-bound.  Operation-specific
 * fields are generated from their published schema/registry entry; they do
 * not replace the canonical identity context. */
export type MissionCanvasOperationInput = WorkstreamAuthorityContext & Record<string, unknown>;

export interface MissionCanvasTransport {
  request<T>(operationId: string, input: MissionCanvasOperationInput): Promise<T>;
}

export class MissionCanvasClient {
  constructor(private readonly transport: MissionCanvasTransport) {}

  projectionGet(input: MissionCanvasOperationInput): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.projection.get", input);
  }

  projectionResolve(input: MissionCanvasOperationInput): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.projection.resolve", input);
  }

  profileList(input: MissionCanvasOperationInput): Promise<Array<WorkspaceProfile>> {
    return this.transport.request<Array<WorkspaceProfile>>("focusa.mission_canvas.profile.list", input);
  }

  profileSelect(input: MissionCanvasOperationInput): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.profile.select", input);
  }

  profileGet(input: MissionCanvasOperationInput): Promise<WorkspaceProfile> {
    return this.transport.request<WorkspaceProfile>("focusa.mission_canvas.profile.get", input);
  }

  activityList(input: MissionCanvasOperationInput): Promise<Array<ActivityMode>> {
    return this.transport.request<Array<ActivityMode>>("focusa.mission_canvas.activity.list", input);
  }

  activitySelect(input: MissionCanvasOperationInput): Promise<ResolvedWorkspaceProjection> {
    return this.transport.request<ResolvedWorkspaceProjection>("focusa.mission_canvas.activity.select", input);
  }

  domain_packInstall(input: MissionCanvasOperationInput): Promise<DomainPackInstallReceipt> {
    return this.transport.request<DomainPackInstallReceipt>("focusa.mission_canvas.domain_pack.install", input);
  }

  registryList(input: MissionCanvasOperationInput): Promise<Array<RegistryEntry>> {
    return this.transport.request<Array<RegistryEntry>>("focusa.mission_canvas.registry.list", input);
  }

  layout_memoryGet(input: MissionCanvasOperationInput): Promise<ProfileLayoutMemory> {
    return this.transport.request<ProfileLayoutMemory>("focusa.mission_canvas.layout_memory.get", input);
  }

  layout_memoryUpdate(input: MissionCanvasOperationInput): Promise<RecompositionReceipt> {
    return this.transport.request<RecompositionReceipt>("focusa.mission_canvas.layout_memory.update", input);
  }

  layoutMutate(input: MissionCanvasOperationInput): Promise<LayoutMutationResult> {
    return this.transport.request<LayoutMutationResult>("focusa.mission_canvas.layout.mutate", input);
  }

  rich_hostResolve(input: MissionCanvasOperationInput): Promise<HostRendererResolution> {
    return this.transport.request<HostRendererResolution>("focusa.mission_canvas.rich_host.resolve", input);
  }

  rich_hostLaunch(input: MissionCanvasOperationInput): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.launch", input);
  }

  rich_hostFocus(input: MissionCanvasOperationInput): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.focus", input);
  }

  rich_hostHide(input: MissionCanvasOperationInput): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.hide", input);
  }

  rich_hostClose(input: MissionCanvasOperationInput): Promise<HostLifecycleState> {
    return this.transport.request<HostLifecycleState>("focusa.mission_canvas.rich_host.close", input);
  }

  draftGet(input: MissionCanvasOperationInput): Promise<CanvasDraftState> {
    return this.transport.request<CanvasDraftState>("focusa.mission_canvas.draft.get", input);
  }

  draftSync(input: MissionCanvasOperationInput): Promise<CanvasDraftState> {
    return this.transport.request<CanvasDraftState>("focusa.mission_canvas.draft.sync", input);
  }

  recipientResolve(input: MissionCanvasOperationInput): Promise<RecipientResolution> {
    return this.transport.request<RecipientResolution>("focusa.mission_canvas.recipient.resolve", input);
  }

  recompositionEvidenceGet(input: MissionCanvasOperationInput): Promise<RecompositionEvidence> {
    return this.transport.request<RecompositionEvidence>("focusa.mission_canvas.recomposition.evidence.get", input);
  }

  recompositionReceiptGet(input: MissionCanvasOperationInput): Promise<RecompositionReceipt> {
    return this.transport.request<RecompositionReceipt>("focusa.mission_canvas.recomposition.receipt.get", input);
  }

  recompositionDiagnosticsList(input: MissionCanvasOperationInput): Promise<Array<OmissionDiagnostic>> {
    return this.transport.request<Array<OmissionDiagnostic>>("focusa.mission_canvas.recomposition.diagnostics.list", input);
  }

  pi_sessionEventAppend(input: MissionCanvasOperationInput): Promise<PiSessionEventReceipt> {
    return this.transport.request<PiSessionEventReceipt>("focusa.mission_canvas.pi_session.event.append", input);
  }

  eventsStream(input: MissionCanvasOperationInput): Promise<Array<ProjectionLifecycleEvent>> {
    return this.transport.request<Array<ProjectionLifecycleEvent>>("focusa.mission_canvas.events.stream", input);
  }
}
