//! Generated by scripts/generate-spec152-route-entitlement-table.py. Do not hand-edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct RouteEntitlementRequirement {
    pub template: &'static str,
    pub feature: &'static str,
    pub limit_bucket: Option<&'static str>,
}

pub(crate) static ROUTE_ENTITLEMENT_REQUIREMENTS: &[RouteEntitlementRequirement] = &[
    RouteEntitlementRequirement {
        template: "/v1/agent/compatibility-lock",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/agent/handshake",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/agent/operations",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/agent/ui-action-bindings",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/agent/ui-capabilities",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/awareness/packet",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/bloatgaurd/report",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/call-stack/design",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/call-stack/verify",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/connect/approve",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/connect/room/create",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/connect/room/start",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/connect/room/{room_id}/approve",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/connect/room/{room_id}/join",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/connect/room/{room_id}/mac-offer",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/connect/start",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context-cognition/curate",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context/adapters/docling/health",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context/graph",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context/graph/mutate",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context/retrieve",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context/sources",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context/sources/commit",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/context/sources/ingest",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/device/pair/complete",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/device/pair/revoke",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/device/pair/start",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/device/pair/status",
        feature: "focusa.team.multi_operator",
        limit_bucket: Some("team_operators"),
    },
    RouteEntitlementRequirement {
        template: "/v1/dxux/report",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/events/stream",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/interview/strategy/grill-with-docs/next-question",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/interviews/closure-package",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/interviews/sessions",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/lineage/head",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/lineage/tree",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/memory/procedural",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/memory/procedural/reinforce",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/memory/semantic",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/memory/semantic/upsert",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/metacognition/capture",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/metacognition/reflect",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/metacognition/retrieve",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/mission-canvas/state",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/mission-canvas/surface-bindings",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/mission-canvas/surface-bindings/mutate",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/mission-canvas/surfaces",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/prediction-authority/events",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/prediction-authority/projection",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/predictions/recent",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/bootstrap/apply",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/bootstrap/preview",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/bootstrap/repair",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/bootstrap/status",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/genesis/commit",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/genesis/resume",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/genesis/start",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/genesis/status",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/identity",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/project/verify",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/providers/conformance",
        feature: "focusa.agent.parallelism",
        limit_bucket: Some("parallel_agents"),
    },
    RouteEntitlementRequirement {
        template: "/v1/providers/contracts",
        feature: "focusa.agent.parallelism",
        limit_bucket: Some("parallel_agents"),
    },
    RouteEntitlementRequirement {
        template: "/v1/resource/mode",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/roles/profiles",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/roles/profiles/draft",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/roles/profiles/review",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/spec-workbench/sessions",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/state/current",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/task-plans",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/task-plans/materialize/beads",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/civil/resolve",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/clock/capture",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/commit",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/forecast",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/high-consequence/preflight",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/migrate-signatures",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/observe",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/preflight",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/priority/commit",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/revise",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/settle-closure",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/temporal/status",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/trajectory/assess",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/trajectory/checkpoint",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/trajectory/define-goal",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/trajectory/propose-workpoint",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/trajectory/resume",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/trajectory/view",
        feature: "focusa.core.mission",
        limit_bucket: Some("missions"),
    },
    RouteEntitlementRequirement {
        template: "/v1/traverse",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/turn/append",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/turn/complete",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/turn/start",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/work-loop/driver/abort",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/work-loop/driver/prompt",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/work-loop/driver/start",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/work-loop/driver/stop",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/work-loop/status",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/work-rail",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/workpoint/checkpoint",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/workpoint/resume",
        feature: "focusa.core.workpoint",
        limit_bucket: Some("workpoints"),
    },
    RouteEntitlementRequirement {
        template: "/v1/workspace/artifacts",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
    RouteEntitlementRequirement {
        template: "/v1/workspace/artifacts/intake",
        feature: "focusa.core.evidence",
        limit_bucket: Some("evidence_records"),
    },
];

pub(crate) fn requirement_for_path(path: &str) -> Option<&'static RouteEntitlementRequirement> {
    ROUTE_ENTITLEMENT_REQUIREMENTS
        .iter()
        .find(|requirement| template_matches(requirement.template, path))
}

fn template_matches(template: &str, path: &str) -> bool {
    let template_segments: Vec<_> = template.trim_matches('/').split('/').collect();
    let path_segments: Vec<_> = path.trim_matches('/').split('/').collect();
    template_segments.len() == path_segments.len()
        && template_segments
            .iter()
            .zip(path_segments)
            .all(|(expected, actual)| {
                (expected.starts_with('{') && expected.ends_with('}'))
                    || expected.starts_with(':')
                    || *expected == actual
            })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_and_parameterized_routes_match_without_prefix_guessing() {
        assert!(requirement_for_path("/v1/workpoint/checkpoint").is_some());
        assert!(requirement_for_path("/not/a/focusa/route").is_none());
        assert!(!template_matches("/v1/items/{id}", "/v1/items"));
        assert!(template_matches("/v1/items/{id}", "/v1/items/item-1"));
    }
}
