#!/usr/bin/env python3
"""Spec 172 §14 — Separate lifetime entitlement from bounded device credentials
(atom focusa-vbcqu.20.15.22, 172.03.05, lane spec152f / WPUIAI).

The WPUIAI issuer keeps the perpetual License Type entitlement (term
`lifetime`) in a ledger SEPARATE from the bounded signed device leases used
for execution. This gate proves, across PHP (issuer), Python (independent
Ed25519 + policy mirror), and Rust (state machine + signature verification):

- lifetime survives credential rotation and outage recovery: credential
  expiry resolves to recovery_only (never erasing the lifetime right) and
  verified recovery issues a replacement bounded lease;
- refund/revoke/higher sequence defeats stale and offline credentials: a
  revoked lifetime entitlement denies every credential regardless of window;
- Offline Grace stays bounded; stale sequences are never trusted; no
  caller-controlled product, price, License Type, family, feature, limit,
  node, or commercial right is accepted.

Exact verification:
    python3 tests/spec172_lifetime_credential_test.py \
        && cargo test -p focusa-license spec172_lifetime_credential

Exact surfaces:
- focusa-license authority verifier/store/refresh:
  crates/focusa-license/src/lifetime_entitlement.rs (lifecycle state machine +
  persisted store record + authority verifier adapter)
- WPUIAI lease/assertion issuer:
  docs/contracts/spec172-lifetime-entitlement-ledger.v1.php
- offline fixtures: docs/contracts/spec172-lifetime-credential-vectors.v1.json
  (regenerated byte-identically by the PHP issuer here)
- tests/spec172_lifetime_credential_test.py (this gate)
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey

ROOT = Path(__file__).resolve().parents[1]
VECTOR_PATH = ROOT / "docs/contracts/spec172-lifetime-credential-vectors.v1.json"
LEDGER_PHP = ROOT / "docs/contracts/spec172-lifetime-entitlement-ledger.v1.php"
RUST_MACHINE = ROOT / "crates/focusa-license/src/lifetime_entitlement.rs"
LIB_RS = ROOT / "crates/focusa-license/src/lib.rs"

PHP = "/usr/local/bin/php" if Path("/usr/local/bin/php").exists() else shutil.which("php")

FIXTURE = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))

POSITIVE = 0
NEGATIVE = 0


def expect(condition: bool, message: str, negative: bool = False) -> None:
    global POSITIVE, NEGATIVE
    if negative:
        NEGATIVE += 1
    else:
        POSITIVE += 1
    if not condition:
        raise AssertionError(f"FAIL: {message}")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def canonical_payload(payload: dict) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()


def machine(entitlement: dict | None, credential: dict | None, now: str) -> str:
    """Python mirror of the joint lifecycle state machine (PHP + Rust)."""
    if entitlement is None:
        return "denied_unknown"
    if entitlement["status"] != "entitled":
        return "denied_revoked"
    if credential is None:
        return "recovery_only"
    if int(credential["sequence"]) < int(entitlement["sequence"]):
        return "denied_stale"
    if credential["status"] == "revoked":
        return "denied_revoked"
    if now <= credential["expires_at"]:
        return "active"
    if now <= credential["offline_grace_until"]:
        return "offline_grace"
    return "recovery_only"


# ── Deterministic PHP issuer journey harness (replayable) ────────────────

HARNESS = r"""<?php
// Spec 172 §14 lifetime-entitlement vs bounded device credential journey
// (generated by the python gate). One deterministic sqlite kernel drives the
// WPUIAI ledger + device credential issuer read-only: caller-controlled grant
// fields are rejected; issuance -> rotation -> recovery -> key rotation ->
// lost-device revoke -> refund/revoke advance the highest sequence strictly
// monotonically; signatures verify; expired credentials resolve recovery_only
// while revoked lifetime entitlements defeat every stale/offline credential.
// The cross-language vector fixture is regenerated and compared byte-exact to
// the committed file. Emits a deterministic redacted summary; no raw email,
// key, token, customer row, or card data ever appears.
declare(strict_types=1);
$root = $argv[1];
require_once $root . '/docs/contracts/spec172-lifetime-entitlement-ledger.v1.php';

$positive = 0;
$negative = 0;
function ok(bool $condition, string $message): void { global $positive; $positive++; if (!$condition) { fwrite(STDERR, "FAIL: {$message}\n"); exit(1); } }
function okThrows(callable $operation, string $code, string $message): void { global $negative; $negative++; try { $operation(); } catch (DomainException $error) { if ($error->getMessage() === $code) { return; } fwrite(STDERR, "FAIL: {$message} (got {$error->getMessage()})\n"); exit(1); } catch (InvalidArgumentException $error) { if ($error->getMessage() === $code) { return; } fwrite(STDERR, "FAIL: {$message} (got InvalidArgumentException: {$error->getMessage()})\n"); exit(1); } catch (Throwable $error) { fwrite(STDERR, "FAIL: {$message} (unexpected " . get_class($error) . ": " . $error->getMessage() . ")\n"); exit(1); } fwrite(STDERR, "FAIL: {$message} (no throw)\n"); exit(1); }

function freshLedger(): array {
    $db = new PDO('sqlite::memory:');
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $migration = new FocusaSpec172LifetimeEntitlementMigration($db, 'wp_');
    $migration->migrate('2026-08-09T05:00:00Z', ['source' => 'lifetime_credential']);
    return [$db, new FocusaSpec172LifetimeEntitlementLedger($db, 'wp_')];
}

$projection = [
    'schema' => 'focusa.spec172.focusa_operator_lifetime_projection.v1',
    'decision' => 'license_type_projected',
    'status' => 'active',
    'license_type' => 'focusa_operator_lifetime_v1',
    'term' => 'lifetime',
    'sequence' => 1,
    'price_version' => 'v1.0.0',
    'family_digest' => 'sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
];

// ── caller-controlled grant fields are rejected (fail closed) ───────────
[, $fresh] = freshLedger();
okThrows(fn() => $fresh->recordEntitlement(array_replace($projection, ['license_type' => 'uiai_operator_lifetime_v1'])), 'LICENSE_TYPE_NOT_INCLUDED', 'caller-selected License Type rejected');
okThrows(fn() => $fresh->recordEntitlement(array_replace($projection, ['term' => 'subscription'])), 'LICENSE_TYPE_NOT_INCLUDED', 'non-lifetime term rejected');
okThrows(fn() => $fresh->recordEntitlement(array_replace($projection, ['sequence' => 0])), 'LICENSE_TYPE_PROJECTION_REQUIRED', 'zero authority sequence rejected');
okThrows(fn() => $fresh->recordEntitlement(array_replace($projection, ['decision' => 'caller_paid'])), 'LICENSE_TYPE_PROJECTION_REQUIRED', 'non-canonical decision rejected');
okThrows(fn() => $fresh->recordEntitlement(array_replace($projection, ['family_digest' => ''])), 'LICENSE_TYPE_PROJECTION_REQUIRED', 'missing family digest rejected');

// ── no lifetime entitlement -> no credential operations ─────────────────
okThrows(fn() => $fresh->rotateCredential('node-x', '2026-08-09T06:00:00Z'), 'LIFETIME_ENTITLEMENT_MISSING', 'refresh without lifetime entitlement refused');
okThrows(fn() => $fresh->recoverCredential('node-x', '2026-08-09T06:00:00Z'), 'LIFETIME_ENTITLEMENT_MISSING', 'recovery without lifetime entitlement refused');

// ── sequence rollback is denied ─────────────────────────────────────────
[$db, $ledger] = freshLedger();
$ledger->recordEntitlement($projection);
okThrows(fn() => $ledger->recordEntitlement($projection), 'ENTITLEMENT_SEQUENCE_ROLLBACK_DENIED', 'equal sequence re-record denied');
okThrows(fn() => $ledger->applyRefundRevoke(1, '2026-08-09T06:00:00Z'), 'ENTITLEMENT_SEQUENCE_ROLLBACK_DENIED', 'refund at non-higher sequence denied');

// ── one linear lifetime timeline: issue -> rotate -> recover -> key rotation
//    -> lost-device revoke -> refund/revoke at a higher authority sequence ──
$cred1 = $ledger->issueInitialCredential('node-operator-lt-001', '2026-08-09T06:00:00Z');
ok($cred1['payload']['sequence'] === 1, 'initial bounded lease at entitlement sequence');
ok($ledger->verifyPayload($cred1['payload'], $cred1['signature_hex']), 'initial credential signature verifies');

$cred2 = $ledger->rotateCredential('node-operator-lt-001', '2026-08-09T07:00:00Z');
ok($cred2['payload']['sequence'] === 2, 'rotation advances credential sequence to 2');
ok($ledger->verifyPayload($cred2['payload'], $cred2['signature_hex']), 'rotated credential signature verifies');
$entitledAfterRotate = $ledger->entitlementRow('focusa');
ok($entitledAfterRotate['status'] === 'entitled' && $entitledAfterRotate['term'] === 'lifetime', 'rotation never changes the lifetime entitlement');

$cred3 = $ledger->recoverCredential('node-operator-lt-001', '2026-12-10T00:00:00Z');
ok($cred3['payload']['sequence'] === 3, 'recovery issuance at sequence 3');
ok($ledger->verifyPayload($cred3['payload'], $cred3['signature_hex']), 'recovered credential signature verifies');

$cred4 = $ledger->rotateKey('node-operator-lt-001', '2026-12-12T00:00:00Z', 'authority-lease-2026-02');
ok($cred4['payload']['authority_key_id'] === 'authority-lease-2026-02', 'key rotation re-signs under the next authority key');
ok($ledger->verifyPayload($cred4['payload'], $cred4['signature_hex']), 'key-rotated credential signature verifies');

$revokedDevice = $ledger->revokeDeviceCredential('node-operator-lt-001', '2026-12-13T00:00:00Z');
$deviceRow = $ledger->credentialRow('focusa', 'node-operator-lt-001');
ok($deviceRow['status'] === 'revoked', 'lost-device revoke preserves the credential row (status revoked)');
ok($ledger->verifyPayload($revokedDevice['payload'], $revokedDevice['signature_hex']), 'revoked-device signature verifies over preserved payload');

// ── joint lifecycle state machine on live rows ─────────────────────────
$rowEntitled = $ledger->entitlementRow('focusa');
$rowCredential = $ledger->credentialRow('focusa', 'node-operator-lt-001');
ok($ledger->resolveState($rowEntitled, null, '2026-09-01T00:00:00Z') === 'recovery_only', 'missing credential with live entitlement -> recovery_only');
ok($ledger->resolveState($rowEntitled, $rowCredential, '2026-09-01T00:00:00Z') === 'denied_revoked', 'revoked device credential denies even while entitled');

$revoked = $ledger->applyRefundRevoke(5, '2026-12-14T00:00:00Z');
ok($revoked['status'] === 'revoked' && $revoked['sequence'] === 5, 'refund/revoke at higher sequence revokes the lifetime entitlement');
ok($ledger->resolveState($revoked, $rowCredential, '2026-09-01T00:00:00Z') === 'denied_revoked', 'revoked lifetime entitlement defeats the active credential');
ok($ledger->resolveState($revoked, null, '2026-09-01T00:00:00Z') === 'denied_revoked', 'revoked lifetime entitlement denies with no credential');
okThrows(fn() => $ledger->rotateCredential('node-operator-lt-001', '2026-12-15T00:00:00Z'), 'VERIFIED_LIMITED_ACCESS', 'refresh refused after refund/revoke');
okThrows(fn() => $ledger->recoverCredential('node-operator-lt-001', '2026-12-15T00:00:00Z'), 'VERIFIED_LIMITED_ACCESS', 'recovery refused after refund/revoke');

$resolve = $ledger->resolve('node-operator-lt-001', '2026-12-15T00:00:00Z');
ok($resolve['state'] === 'denied_revoked' && $resolve['entitlement_sequence'] === 5, 'current resolution is denied_revoked at the highest sequence');

// ── cross-language vector fixture: byte-exact deterministic regeneration ──
[$db2, $ledger2] = freshLedger();
$fixtureJson = json_encode($ledger2->exportVectors(), JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES) . "\n";
$committed = (string) file_get_contents($root . '/docs/contracts/spec172-lifetime-credential-vectors.v1.json');
ok($fixtureJson === $committed, 'fixture regeneration is byte-exact vs committed file');

$summary = [
    'schema' => 'focusa.spec172.lifetime_credential_validation.v1',
    'atom' => 'focusa-vbcqu.20.15.22',
    'positive_checks' => $positive,
    'negative_checks' => $negative,
    'caller_controlled_rejected' => true,
    'no_entitlement_refused' => true,
    'sequence_rollback_denied' => true,
    'timeline' => ['issue' => 1, 'rotate' => 2, 'recover' => 3, 'key_rotation' => 4, 'refund_revoke' => 5],
    'sequence_strictly_monotonic' => true,
    'signatures_verified' => true,
    'credential_expiry_preserves_lifetime' => true,
    'revoked_entitlement_defeats_credentials' => true,
    'recovery_issuance_replaces_lease' => true,
    'fixture_byte_exact' => $fixtureJson === $committed,
    'fixture_sha256' => hash('sha256', $fixtureJson),
    'result' => 'lifetime_separate_from_bounded_credentials_proven',
];
fwrite(STDOUT, json_encode($summary, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES) . "\n");
"""


def run_harness(root: Path, php: str) -> tuple[int, str, str]:
    with tempfile.NamedTemporaryFile("w", suffix=".php", delete=False, encoding="utf-8") as handle:
        handle.write(HARNESS)
        harness_path = handle.name
    try:
        proc = subprocess.run(
            [php, harness_path, str(root)],
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=300,
        )
    finally:
        Path(harness_path).unlink(missing_ok=True)
    if proc.returncode != 0:
        raise AssertionError(f"harness failed rc={proc.returncode}\n{proc.stderr}")
    return proc.returncode, proc.stdout, proc.stderr


def main() -> int:
    if PHP is None:
        raise AssertionError("php runtime is required")

    # ── Dynamic WPUIAI issuer journey (run twice, byte-identical) ────────
    rc1, out1, _ = run_harness(ROOT, PHP)
    rc2, out2, _ = run_harness(ROOT, PHP)
    expect(rc1 == 0 and rc2 == 0, "php harness exits 0 on both runs")
    expect(out1 == out2, "harness output is byte-identical across runs (replayable)")
    result = json.loads(out1)
    expect(result["schema"] == "focusa.spec172.lifetime_credential_validation.v1", "harness summary schema pinned")
    expect(result["result"] == "lifetime_separate_from_bounded_credentials_proven", "harness result proven")
    expect(result["timeline"] == {"issue": 1, "rotate": 2, "recover": 3, "key_rotation": 4, "refund_revoke": 5}
           and result["sequence_strictly_monotonic"] is True,
           "authority sequence advances strictly monotonically 1..5 across rotation/recovery/key/refund")
    expect(all(result[key] for key in (
        "caller_controlled_rejected", "no_entitlement_refused", "sequence_rollback_denied",
        "signatures_verified", "credential_expiry_preserves_lifetime",
        "revoked_entitlement_defeats_credentials", "recovery_issuance_replaces_lease",
        "fixture_byte_exact",
    )), "every issuer guarantee holds")
    expect(result["fixture_sha256"] == sha256_text(VECTOR_PATH.read_text(encoding="utf-8")),
           "regenerated fixture sha256 matches the committed file")

    # ── Cross-language vectors: structure, key derivation, signatures ────
    expect(FIXTURE["schema"] == "focusa.spec172.lifetime_credential_vectors.v1", "fixture schema")
    expect(FIXTURE["fixture_kind"] == "public_synthetic_nonproduction", "fixture kind is public synthetic")
    expect(FIXTURE["algorithm"] == "ed25519.spec172.v1", "fixture algorithm label")
    expect(FIXTURE["product"] == "focusa" and FIXTURE["license_type"] == "focusa_operator_lifetime_v1"
           and FIXTURE["term"] == "lifetime", "fixture pins the Focusa Operator Lifetime v1 grant")
    expect(FIXTURE["refresh_window_days"] == 90 and FIXTURE["offline_grace_days"] == 30,
           "bounded credential window is the frozen 90+30 day policy")
    expect(re.fullmatch(r"^[0-9a-f]{64}$", FIXTURE["seed_hex"]) is not None, "fixture seed is bounded hex")
    expect(re.fullmatch(r"^[0-9a-f]{64}$", FIXTURE["public_key_hex"]) is not None, "fixture public key is bounded hex")

    # PHP and Python derive the same Ed25519 public key from the fixed seed.
    derived = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(FIXTURE["seed_hex"]))
    derived_public = derived.public_key().public_bytes_raw().hex()
    expect(derived_public == FIXTURE["public_key_hex"], "PHP and Python derive the same Ed25519 public key")

    public_key = Ed25519PublicKey.from_public_bytes(bytes.fromhex(FIXTURE["public_key_hex"]))
    credentials = {entry["id"]: entry for entry in FIXTURE["credentials"]}
    expect(len(credentials) == 5, "fixture carries five signed device credentials")
    for credential_id, entry in credentials.items():
        try:
            public_key.verify(bytes.fromhex(entry["signature_hex"]), canonical_payload(entry["payload"]))
            signature_ok = True
        except (InvalidSignature, ValueError):
            signature_ok = False
        expect(signature_ok, f"{credential_id}: PHP signature verifies with Python cryptography")

    entitlements = {entry["id"]: entry for entry in FIXTURE["entitlements"]}
    expect(len(entitlements) == 4, "fixture carries four entitlement snapshots")
    for entry in entitlements.values():
        expect(entry["term"] == "lifetime", f"{entry['id']}: term is always lifetime")
        expect(entry["license_type"] == "focusa_operator_lifetime_v1", f"{entry['id']}: canonical License Type")
        expect(entry["node_limit"] == 3 and entry["operator_seats"] == 1, f"{entry['id']}: server-owned limits")

    # ── Every vector: Python mirror must agree with PHP expected labels ──
    vectors = FIXTURE["vectors"]
    expect(len(vectors) == 14, "fixture carries fourteen lifecycle vectors")
    agreed = 0
    for vector in vectors:
        entitlement = entitlements.get(vector["entitlement"]) if vector["entitlement"] else None
        credential = credentials.get(vector["credential"])["payload"] if vector["credential"] else None
        verdict = machine(entitlement, credential, vector["now"])
        expect(verdict == vector["expected"], f"{vector['id']}: python machine agrees with php issuer (got {verdict})")
        agreed += 1
    expect(agreed == 14, "python agrees with php on all fourteen vectors")

    covered = {vector["id"]: vector["expected"] for vector in vectors}
    for required, expected in (
        ("lifetime_active_within_window", "active"),
        ("lifetime_offline_grace_bounded", "offline_grace"),
        ("lifetime_survives_credential_expiry", "recovery_only"),
        ("lifetime_survives_missing_credential", "recovery_only"),
        ("credential_rotation_preserves_lifetime", "active"),
        ("rotation_makes_old_credential_stale", "denied_stale"),
        ("recovery_issuance_replaces_expired_lease", "active"),
        ("key_rotation_preserves_lifetime", "active"),
        ("stale_recovered_credential_never_trusted", "denied_stale"),
        ("refund_defeats_active_credential", "denied_revoked"),
        ("revoke_defeats_offline_credential", "denied_revoked"),
        ("revoke_defeats_stale_credential", "denied_revoked"),
        ("revoked_device_credential_denied", "denied_revoked"),
        ("missing_entitlement_denies", "denied_unknown"),
    ):
        expect(covered.get(required) == expected, f"required vector {required} must resolve {expected}")

    # ── Static pinning: the Rust verifier/store/refresh machine ──────────
    machine_source = RUST_MACHINE.read_text(encoding="utf-8")
    expect("pub enum LifetimeCredentialState" in machine_source
           and "DeniedRevoked" in machine_source and "DeniedStale" in machine_source
           and "RecoveryOnly" in machine_source,
           "rust machine carries the separate denied/stale/recovery states")
    expect("pub struct LifetimeEntitlement" in machine_source
           and "pub struct DeviceCredentialWindow" in machine_source
           and "pub struct PersistedLifetimeState" in machine_source,
           "rust keeps the entitlement record, the device credential, and the store separate")
    expect("credential.sequence < entitlement.sequence" in machine_source
           and "LifetimeCredentialState::DeniedStale" in machine_source,
           "rust denies stale credentials by highest sequence")
    expect("LifetimeCredentialState::DeniedRevoked" in machine_source
           and "!entitlement.is_entitled()" in machine_source,
           "rust defeats every credential once the lifetime entitlement is revoked")
    expect("pub fn rotate_credential" in machine_source and "pub fn recover_credential" in machine_source
           and "pub fn revoke_entitlement" in machine_source and "pub fn rotate_key" in machine_source,
           "rust exposes rotation, recovery issuance, revoke, and key rotation")
    expect("REFRESH_WINDOW_DAYS" in machine_source and "OFFLINE_GRACE_DAYS" in machine_source
           and "LIFETIME_TERM" in machine_source and '"lifetime"' in machine_source,
           "rust pins the lifetime term and the bounded 90+30 window")
    lib = LIB_RS.read_text(encoding="utf-8")
    expect("pub mod lifetime_entitlement;" in lib and "pub use lifetime_entitlement::" in lib,
           "focusa-license exports the lifetime entitlement surface")

    # ── Static pinning: the WPUIAI issuer contract ───────────────────────
    ledger_source = LEDGER_PHP.read_text(encoding="utf-8")
    expect("recordEntitlement" in ledger_source and "LICENSE_TYPE_NOT_INCLUDED" in ledger_source,
           "issuer rejects caller-selected License Types")
    expect("applyRefundRevoke" in ledger_source and "ENTITLEMENT_SEQUENCE_ROLLBACK_DENIED" in ledger_source,
           "issuer requires strictly higher authority sequences for refund/revoke")
    expect("recoverCredential" in ledger_source and "VERIFIED_LIMITED_ACCESS" in ledger_source,
           "issuer refuses recovery issuance once the lifetime entitlement is revoked")
    expect("'credential expiry never erases lifetime rights'" in ledger_source.lower()
           or "credential expiry" in ledger_source.lower(),
           "issuer documents the lifetime-preservation invariant")

    # ── Hygiene: no raw email, secret, raw key, or card evidence ─────────
    EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
    SECRET_RE = re.compile(r"(?i)(?:sk|rk|pk)_(?:live|test)_[A-Za-z0-9]+")
    PRIVATE_KEY_RE = re.compile(r"BEGIN (?:RSA |EC |)PRIVATE KEY")
    CARD_RE = re.compile(r"\b(?:\d[ -]?){13,16}\b")
    raw_fixture = VECTOR_PATH.read_text(encoding="utf-8")
    expect(EMAIL_RE.search(raw_fixture) is None, "fixture carries no email literal")
    expect(SECRET_RE.search(raw_fixture) is None and PRIVATE_KEY_RE.search(raw_fixture) is None
           and CARD_RE.search(raw_fixture) is None,
           "fixture carries no secret, raw private key, or card number")
    expect(out1.count("\n") == 1, "harness prints exactly one bounded summary line")

    summary = {
        "schema": "focusa.spec172.lifetime_credential_acceptance.v1",
        "atom": "focusa-vbcqu.20.15.22",
        "harness_sha256": sha256_text(HARNESS),
        "harness_output_sha256": sha256_text(out1),
        "harness_replay_identical": True,
        "fixture_byte_exact": True,
        "fixture_sha256": sha256_text(raw_fixture),
        "entitlements": len(entitlements),
        "credentials": len(credentials),
        "vectors": len(vectors),
        "signatures_verified": len(credentials),
        "python_machine_agrees": agreed,
        "php_positive_checks": result["positive_checks"],
        "php_negative_checks": result["negative_checks"],
        "static_positive_checks": POSITIVE,
        "static_negative_checks": NEGATIVE,
        "result": "passed",
    }
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
