#!/usr/bin/env python3
"""Guard Spec 135 OpenAPI → TypeScript/Go generation parity."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "docs/contracts/spec135/generated-contract-v1/openapi-3.0.3.json"
TS = ROOT / "packages/generated/spec135/typescript/schema.d.ts"
GO = ROOT / "packages/generated/spec135/go/client.gen.go"
GENERATOR = ROOT / "scripts/generate-spec135-clients.sh"

contract = json.loads(CONTRACT.read_text())
ts = TS.read_text()
go = GO.read_text()
generator = GENERATOR.read_text()

assert contract["openapi"] == "3.0.3"
assert contract["x-focusa-json-schema-dialect"] == "https://json-schema.org/draft/2020-12/schema"
assert contract["paths"] and contract["components"]["schemas"]

methods = {"get", "post", "put", "patch", "delete"}
operations = [
    operation["operationId"]
    for path in contract["paths"].values()
    for method, operation in path.items()
    if method in methods
]
assert len(operations) == len(set(operations)) >= 45

for operation_id in operations:
    assert f'operations["{operation_id}"]' in ts, f"TypeScript missing {operation_id}"
    go_name = "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", operation_id) if part)
    assert f"func (c *Client) {go_name}(" in go, f"Go missing {operation_id} ({go_name})"

assert "This file was auto-generated by openapi-typescript" in ts
assert "oapi-codegen/v2 version v2.7.0" in go
assert "openapi-typescript@7.10.1" in generator
assert "oapi-codegen@v2.7.0" in generator
assert "-generate types,client" in generator

print(f"Spec 135 generated clients: PASS ({len(operations)} operations)")
