#!/usr/bin/env python3
"""Spec 152E.07.02 website paid Focusa through the branded EDD facade (atom focusa-vbcqu.20.13.56).

Exact verification:
    python3 tests/spec152e_paid_website_e2e_test.py

Runs one synthetic test-mode customer through the complete branded website paid
journey (spec 152E §11, §23 "Website paid Focusa"): branded website
registration -> single-use mailbox verification -> authority account + EDD
customer promotion -> server-owned EDD checkout intent on the branded facade ->
test-mode EDD Stripe payment -> EDD order/item -> EDD Software Licensing human
key -> dual-channel delivery (transactional email + terminal-independent
account) -> node registration -> signed device-bound lease -> EDD refund
cleanup that revokes entitlement, increments the monotonic sequence, and
preserves account/order/delivery/node/evidence truth. The journey contract
executes on sqlite through a deterministic PHP harness; the harness output is
byte-identical across runs (replayable from the pinned commit) and the signed
lease is independently re-verified with `cryptography` Ed25519PublicKey over
the domain-separated payload, byte-compatible with the Rust verifier.

Surfaces under test (EXACT SURFACES):
- Website registration/verification:
  docs/contracts/spec152e-website-paid-facade.v1.php (startRegistration,
  verifyEmail, promote) + fixture docs/contracts/spec152e-website-paid-facade-
  fixture.v1.json
- EDD checkout/order/key/email: createCheckoutIntent, completePayment,
  issueLicense, deliver (transactional email + account delivery)
- Terminal-independent account delivery: deliver() account channel + receipt
- Signed lease: issueLease via the canonical Ed25519 signer seam from
  docs/contracts/spec152e-edd-bound-lease-issuer.v1.php (loaded first)

Fail-closed invariants (spec 152E FORBIDDEN + §19; no install-site authority):
- A submitted email creates only a pending registration attempt; no EDD
  customer, account, checkout, order, license, node, or lease exists until
  mailbox control is verified. No unverified-email promotion.
- No local/self-issued entitlement: the human key is created only by the EDD
  Software Licensing issuance step after a complete, integrity-ok order bound
  to the verified identity. Payment success alone never verifies or issues.
- No independent facade authority: facades are allowlisted presenters; the
  journey completes with install_site_authority=none and no direct install-site
  issuance surface.
- No client-controlled EDD price/grants: caller-supplied product/download/
  price/amount/grants/limits/redirect fields fail closed
  (CALLER_CONTROLLED_GRANT_DENIED).
- Checkout email integrity: a different checkout email holds fulfillment
  (EDD_ORDER_UNVERIFIED) until the verified identity matches.
- Refund cleanup: EDD refund increments the sequence and revokes the lease;
  refresh is denied; account/order/delivery/node/evidence rows are preserved.
- Spec 158 implementation is excluded.
- No raw email, raw human key, payment reference, or secret material in any
  artifact; receipts are masked and carry an immutable sha256 handle.
- No push, deploy, release, merge, or Beads mutation is performed.
"""

import base64
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "docs/contracts/spec152e-website-paid-facade.v1.php"
LEASE_CONTRACT = ROOT / "docs/contracts/spec152e-edd-bound-lease-issuer.v1.php"
FIXTURE = ROOT / "docs/contracts/spec152e-website-paid-facade-fixture.v1.json"

PHP = "/usr/local/bin/php" if Path("/usr/local/bin/php").exists() else shutil.which("php")

positive = 0
negative = 0


def expect(condition: bool, message: str) -> None:
    global positive
    positive += 1
    if not condition:
        raise AssertionError(f"FAIL: {message}")


def expect_negative(condition: bool, message: str) -> None:
    global negative
    negative += 1
    if not condition:
        raise AssertionError(f"FAIL: {message}")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ── Deterministic PHP journey harness ───────────────────────────────────────

HARNESS = r"""<?php
// Spec 152E.07.02 branded website paid-Focusa journey harness (generated by the
// python gate). Executes the complete acceptance-matrix row on sqlite with a
// fixed clock, then emits a deterministic redacted summary. Byte-identical
// across runs; every positive/negative check is counted.
declare(strict_types=1);
$contractPath = $argv[1];
$leaseContractPath = $argv[2];
$fixturePath = $argv[3];
require_once $leaseContractPath;
require_once $contractPath;
$fixture = json_decode((string) file_get_contents($fixturePath), true, 512, JSON_THROW_ON_ERROR);
$positive = 0;
$negative = 0;
function ok(bool $condition, string $message): void { global $positive; $positive++; if (!$condition) { fwrite(STDERR, "FAIL: {$message}\n"); exit(1); } }
function okThrows(callable $operation, string $code, string $message): void { global $negative; $negative++; try { $operation(); } catch (DomainException $error) { if ($error->getMessage() === $code) { return; } fwrite(STDERR, "FAIL: {$message} (got {$error->getMessage()})\n"); exit(1); } catch (Throwable $error) { fwrite(STDERR, "FAIL: {$message} (unexpected " . get_class($error) . ": " . $error->getMessage() . ")\n"); exit(1); } fwrite(STDERR, "FAIL: {$message} (no throw)\n"); exit(1); }

$db = new PDO('sqlite::memory:');
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$tick = 0;
$clock = static function () use (&$tick): string {
    $ts = (new DateTimeImmutable('2026-08-09T03:00:00Z'))->modify('+' . $tick . ' minutes')->format('Y-m-d\TH:i:s\Z');
    $tick++;
    return $ts;
};
$schema = new FocusaSpec152eWebsitePaidFacadeMigration($db, 'wp_');
$schema->migrate('2026-08-09T02:00:00Z', ['source' => 'website_paid_facade_test']);
$keySet = new FocusaSpec152eAuthorityKeySetSeam(str_repeat('R', 32), str_repeat('L', 32), $clock);
$svc = new FocusaSpec152eWebsitePaidFacadeService($db, $clock, 'wp_', $keySet);

$counts = static function () use ($db): array {
    $table = static fn(string $name): int => (int) $db->query("SELECT COUNT(*) FROM wp_wpuiai_webpaid_{$name}")->fetchColumn();
    return [
        'registrations' => $table('registrations'),
        'identities' => $table('identities'),
        'accounts' => $table('accounts'),
        'orders' => $table('orders'),
        'order_items' => $table('order_items'),
        'licenses' => $table('licenses'),
        'deliveries' => $table('deliveries'),
        'nodes' => $table('nodes'),
        'leases' => $table('leases'),
        'sequences' => $table('sequences'),
        'refunds' => $table('refunds'),
        'journal' => $table('journal'),
    ];
};
$correlation = static function (int $seq, string $kind): array {
    return [
        'request_id' => 'req_webpaid_' . $kind . '_' . str_pad((string) $seq, 4, '0', STR_PAD_LEFT),
        'idempotency_key' => 'idem_webpaid_' . $kind . '_' . str_pad((string) $seq, 4, '0', STR_PAD_LEFT),
    ];
};
$journey = [];
$customer = $fixture['customer'];
$facade = $fixture['facade'];
$product = $fixture['product'];
$edd = $fixture['edd'];
$device = $fixture['device'];

// ── Pre-flight negatives: no operation works without a verified registration ──
$bogus = '00000000-0000-0000-0000-000000000000';
okThrows(static fn() => $svc->verifyEmail(array_merge(['registration_uuid' => $bogus, 'code' => $customer['verification_code']], $correlation(1, 'pre'))), 'REGISTRATION_NOT_FOUND', 'verify on unknown registration');
okThrows(static fn() => $svc->receipt(['registration_uuid' => $bogus]), 'REGISTRATION_NOT_FOUND', 'receipt on unknown registration');
okThrows(static fn() => $svc->startRegistration(array_merge(['facade_id' => 'attacker_v1', 'origin' => 'https://evil.invalid', 'product_code' => $product['product_code'], 'email_digest' => $customer['email_digest'], 'email_domain' => $customer['email_domain'], 'email_prefix_char' => 'x', 'challenge_code' => $customer['verification_code']], $correlation(1, 'pre'))), 'FACADE_ORIGIN_DENIED', 'facade spoof denied');
okThrows(static fn() => $svc->startRegistration(array_merge(['facade_id' => $facade['facade_id'], 'origin' => $facade['origin'], 'product_code' => 'focusa_hacker', 'email_digest' => $customer['email_digest'], 'email_domain' => $customer['email_domain'], 'email_prefix_char' => 'x', 'challenge_code' => $customer['verification_code']], $correlation(1, 'pre'))), 'PRODUCT_MAPPING_REQUIRED', 'unmapped product denied');
okThrows(static fn() => $svc->startRegistration(array_merge(['facade_id' => $facade['facade_id'], 'origin' => $facade['origin'], 'product_code' => $product['product_code'], 'email_digest' => $customer['email_digest'], 'email_domain' => $customer['email_domain'], 'email_prefix_char' => 'x', 'challenge_code' => $customer['verification_code'], 'price' => '0'], $correlation(1, 'pre'))), 'CALLER_CONTROLLED_GRANT_DENIED', 'caller price denied at registration');

// ── Invalid/unreachable email: pending attempt only, zero promotion ────────
$invalidStart = $svc->startRegistration(array_merge([
    'facade_id' => $facade['facade_id'], 'origin' => $facade['origin'],
    'product_code' => $product['product_code'],
    'email_digest' => $customer['invalid_email_digest'], 'email_domain' => $customer['email_domain'],
    'email_prefix_char' => 'u', 'challenge_code' => $customer['verification_code'],
], $correlation(1, 'inv')));
ok($invalidStart['ok'] === true && $invalidStart['state'] === 'attempt_created', 'invalid email creates pending attempt only');
ok($invalidStart['customer_created'] === false && $invalidStart['entitlement_created'] === false, 'pending attempt creates no customer or entitlement');
$invalidReg = $invalidStart['registration_uuid'];
okThrows(static fn() => $svc->verifyEmail(array_merge(['registration_uuid' => $invalidReg, 'code' => '000000'], $correlation(1, 'inv'))), 'EMAIL_VERIFICATION_FAILED', 'wrong code fails');
okThrows(static fn() => $svc->promote(array_merge(['registration_uuid' => $invalidReg], $correlation(1, 'inv'))), 'EMAIL_VERIFICATION_REQUIRED', 'unverified email never promotes');
okThrows(static fn() => $svc->completePayment(array_merge(['registration_uuid' => $invalidReg, 'checkout_email_digest' => $customer['invalid_email_digest'], 'payment_reference_digest' => $edd['payment_reference_digest']], $correlation(1, 'inv'))), 'EDD_CHECKOUT_REQUIRED', 'payment cannot reach an unverified registration');
okThrows(static fn() => $svc->issueLicense(array_merge(['registration_uuid' => $invalidReg], $correlation(1, 'inv'))), 'EDD_ORDER_PENDING', 'no license before a complete order');
okThrows(static fn() => $svc->deliver(array_merge(['registration_uuid' => $invalidReg], $correlation(1, 'inv'))), 'EDD_LICENSE_PENDING', 'no delivery before issuance');
okThrows(static fn() => $svc->registerNode(array_merge(['registration_uuid' => $invalidReg, 'node_id' => $device['node_id'], 'device_public_key' => $device['device_public_key_b64']], $correlation(1, 'inv'))), 'LICENSE_DELIVERY_PENDING', 'no node before delivery');
okThrows(static fn() => $svc->issueLease(array_merge(['registration_uuid' => $invalidReg], $correlation(1, 'inv'))), 'NODE_REQUIRED', 'no lease before node');
okThrows(static fn() => $svc->refund(array_merge(['registration_uuid' => $invalidReg, 'reason' => 'synthetic_proof_cleanup'], $correlation(1, 'inv'))), 'REFUND_STATE_REQUIRED', 'no refund before lease');
$preCounts = $counts();
ok($preCounts['identities'] === 0 && $preCounts['accounts'] === 0 && $preCounts['orders'] === 0, 'unverified attempt writes zero identity/account/order rows');
ok($preCounts['licenses'] === 0 && $preCounts['nodes'] === 0 && $preCounts['leases'] === 0 && $preCounts['refunds'] === 0, 'unverified attempt writes zero license/node/lease/refund rows');

// ── Main journey: branded website paid Focusa ──────────────────────────────
$start = $svc->startRegistration(array_merge([
    'facade_id' => $facade['facade_id'], 'origin' => $facade['origin'],
    'product_code' => $product['product_code'],
    'email_digest' => $customer['email_digest'], 'email_domain' => $customer['email_domain'],
    'email_prefix_char' => $customer['email_prefix_char'], 'challenge_code' => $customer['verification_code'],
], $correlation(2, 'start')));
ok($start['ok'] === true && $start['state'] === 'attempt_created', 'branded website registration created');
ok($start['facade_id'] === $facade['facade_id'] && $start['origin'] === $facade['origin'], 'facade-bound registration');
ok($start['masked_email'] === $customer['email_prefix_char'] . '***@' . $customer['email_domain'], 'masked email only');
ok($start['customer_created'] === false && $start['entitlement_created'] === false, 'registration creates no customer/entitlement');
$reg = $start['registration_uuid'];
$journey[] = $start['state'];

// Replay: identical request returns the stored registration, zero new rows.
$replayStart = $svc->startRegistration(array_merge([
    'facade_id' => $facade['facade_id'], 'origin' => $facade['origin'],
    'product_code' => $product['product_code'],
    'email_digest' => $customer['email_digest'], 'email_domain' => $customer['email_domain'],
    'email_prefix_char' => $customer['email_prefix_char'], 'challenge_code' => $customer['verification_code'],
], $correlation(2, 'start')));
ok($replayStart['replayed'] === true && $replayStart['idempotent_replay'] === true, 'registration replay is idempotent');
okThrows(static fn() => $svc->startRegistration(array_merge([
    'facade_id' => $facade['facade_id'], 'origin' => $facade['origin'],
    'product_code' => $product['product_code'],
    'email_digest' => $customer['email_digest'], 'email_domain' => $customer['email_domain'],
    'email_prefix_char' => $customer['email_prefix_char'], 'challenge_code' => '111111',
], $correlation(2, 'start'))), 'IDEMPOTENCY_CONFLICT', 'idempotency-key reuse with a different request fails');

// Verification: single-use magic code proves mailbox control.
okThrows(static fn() => $svc->verifyEmail(array_merge(['registration_uuid' => $reg, 'code' => '000000'], $correlation(2, 'verify'))), 'EMAIL_VERIFICATION_FAILED', 'wrong verification code fails');
$verified = $svc->verifyEmail(array_merge(['registration_uuid' => $reg, 'code' => $customer['verification_code']], $correlation(3, 'verify')));
ok($verified['ok'] === true && $verified['state'] === 'email_verified', 'mailbox verified with single-use code');
$journey[] = $verified['state'];
okThrows(static fn() => $svc->verifyEmail(array_merge(['registration_uuid' => $reg, 'code' => $customer['verification_code']], $correlation(4, 'verify'))), 'EMAIL_VERIFICATION_FAILED', 'verification code is single-use (replay fails)');

// Promotion: only after verification is the authority account + EDD customer created.
okThrows(static fn() => $svc->promote(array_merge(['registration_uuid' => $invalidReg], $correlation(5, 'promote'))), 'EMAIL_VERIFICATION_REQUIRED', 'unverified promote fails closed');
$promoted = $svc->promote(array_merge(['registration_uuid' => $reg], $correlation(3, 'promote')));
ok($promoted['ok'] === true && $promoted['state'] === 'account_promoted', 'account promoted');
ok($promoted['customer_id'] === (int) $edd['customer_id'] && $promoted['edd_customer_resolved_or_created'] === true, 'EDD customer resolved/created');
$journey[] = $promoted['state'];
$replayPromote = $svc->promote(array_merge(['registration_uuid' => $reg], $correlation(3, 'promote')));
ok($replayPromote['replayed'] === true && $replayPromote['zero_new_rows'] === true, 'promote replay returns stored account');
$afterPromote = $counts();
ok($afterPromote['accounts'] === 1 && $afterPromote['identities'] === 1 && $afterPromote['orders'] === 0, 'exactly one account/identity, zero orders');

// Checkout: server-owned EDD intent on the branded facade.
okThrows(static fn() => $svc->createCheckoutIntent(array_merge(['registration_uuid' => $invalidReg], $correlation(6, 'intent'))), 'EDD_CHECKOUT_REQUIRED', 'unpromoted checkout denied');
okThrows(static fn() => $svc->createCheckoutIntent(array_merge(['registration_uuid' => $reg, 'price' => '0'], $correlation(6, 'intent'))), 'CALLER_CONTROLLED_GRANT_DENIED', 'caller price denied at checkout');
okThrows(static fn() => $svc->createCheckoutIntent(array_merge(['registration_uuid' => $reg, 'product_code' => 'focusa_hacker'], $correlation(6, 'intent'))), 'CALLER_CONTROLLED_GRANT_DENIED', 'caller product denied at checkout');
$intent = $svc->createCheckoutIntent(array_merge(['registration_uuid' => $reg], $correlation(7, 'intent')));
ok($intent['ok'] === true && $intent['state'] === 'checkout_pending', 'checkout intent created');
ok(str_starts_with($intent['branded_checkout_url'], $facade['origin'] . $facade['checkout_path']), 'branded facade checkout URL');
ok((int) $intent['edd_download_id'] === (int) $product['edd_download_id'] && $intent['edd_price_id'] === $product['edd_price_id'] && $intent['price_usd'] === $product['price_usd'], 'server-owned product/price mapping');
ok($intent['stripe_gateway'] === 'edd_stripe_test_mode' && $intent['card_data_handled_by'] === 'edd_stripe_only', 'EDD Stripe gateway only, no client card data');
$journey[] = $intent['state'];

// Checkout email integrity: a different checkout email holds fulfillment.
$held = $svc->completePayment(array_merge([
    'registration_uuid' => $reg, 'checkout_email_digest' => $customer['invalid_email_digest'],
    'payment_reference_digest' => $edd['payment_reference_digest'],
], $correlation(8, 'pay')));
ok($held['ok'] === false && $held['state'] === 'held_unverified', 'different checkout email holds fulfillment');
ok($held['error'] === 'EDD_ORDER_UNVERIFIED' && $held['checkout_email_integrity'] === 'fulfillment_held', 'payment success alone cannot bypass verification');
okThrows(static fn() => $svc->issueLicense(array_merge(['registration_uuid' => $reg], $correlation(8, 'license'))), 'EDD_ORDER_PENDING', 'no license while fulfillment is held');

// Matching checkout email completes the same canonical order.
$paid = $svc->completePayment(array_merge([
    'registration_uuid' => $reg, 'checkout_email_digest' => $customer['email_digest'],
    'payment_reference_digest' => $edd['payment_reference_digest'],
], $correlation(9, 'pay')));
ok($paid['ok'] === true && $paid['state'] === 'complete', 'EDD order completed in test mode');
ok($paid['order_id'] === (int) $edd['order_id'] && $paid['checkout_email_integrity'] === 'verified_identity_match', 'one canonical order, verified identity match');
$journey[] = 'order_complete';
$afterOrder = $counts();
ok($afterOrder['orders'] === 1 && $afterOrder['order_items'] === 1, 'exactly one order and one order item');

// Issuance: EDD Software Licensing produces the sole human key, idempotent.
$license = $svc->issueLicense(array_merge(['registration_uuid' => $reg], $correlation(9, 'license')));
ok($license['ok'] === true && $license['state'] === 'entitlement_issued', 'EDD Software Licensing key issued');
ok($license['edd_license_id'] === (int) $edd['edd_license_id'] && $license['source'] === 'edd_software_licensing', 'key source is EDD only');
ok($license['issuance_surface'] === 'edd_authority_only' && $license['duplicate_license'] === false, 'no local/self-issued entitlement');
$journey[] = $license['state'];
$replayLicense = $svc->issueLicense(array_merge(['registration_uuid' => $reg], $correlation(9, 'license')));
ok($replayLicense['replayed'] === true && $replayLicense['zero_new_rows'] === true, 'license issuance replay writes zero rows');
$keyRow = $db->query("SELECT license_key FROM wp_wpuiai_webpaid_licenses WHERE edd_license_id = " . (int) $edd['edd_license_id'])->fetchColumn();
ok(preg_match('/^FOCUSA-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/', (string) $keyRow) === 1, 'human key carries the canonical FOCUSA shape');
ok($keyRow === 'FOCUSA-B031-FBA5-70FB-85AB', 'human key matches the deterministic synthetic fixture vector');

// Delivery: transactional email + terminal-independent account, same canonical key.
$delivered = $svc->deliver(array_merge(['registration_uuid' => $reg], $correlation(10, 'deliver')));
ok($delivered['ok'] === true && $delivered['state'] === 'delivered', 'key delivered');
ok($delivered['channels'] === ['email' => 'sent', 'account' => 'sent'], 'dual-channel delivery (email + account)');
ok($delivered['same_canonical_key_both_channels'] === true, 'same canonical key on both channels');
ok($delivered['promotional_content'] === false, 'transactional delivery carries no promotional content');
ok($delivered['key_mask'] === 'FOCUSA-B031-****-****-****', 'delivery receipt masks the human key');
$journey[] = $delivered['state'];
$deliveryMasks = $db->query("SELECT key_mask, channel FROM wp_wpuiai_webpaid_deliveries ORDER BY channel")->fetchAll(PDO::FETCH_ASSOC);
ok(count($deliveryMasks) === 2, 'exactly two delivery records');
ok($deliveryMasks[0]['key_mask'] === $deliveryMasks[1]['key_mask'], 'email and account deliveries carry the same key mask');

// Node registration: device-bound node under the verified account + EDD license.
okThrows(static fn() => $svc->registerNode(array_merge(['registration_uuid' => $reg, 'node_id' => 'bad node id', 'device_public_key' => $device['device_public_key_b64']], $correlation(11, 'node'))), 'NODE_NOT_FOUND', 'malformed node id denied');
$node = $svc->registerNode(array_merge(['registration_uuid' => $reg, 'node_id' => $device['node_id'], 'device_public_key' => $device['device_public_key_b64']], $correlation(11, 'node')));
ok($node['ok'] === true && $node['state'] === 'device_registered', 'node registered');
ok($node['binding'] === 'account_and_edd_license' && $node['install_channel_telemetry_only'] === true, 'node bound to account + EDD license; channel is telemetry only');
$journey[] = $node['state'];

// Signed lease: monotonic sequence 1, canonical Ed25519 envelope.
okThrows(static fn() => $svc->issueLease(array_merge(['registration_uuid' => $reg, 'features' => ['all' => true]], $correlation(12, 'lease'))), 'CALLER_CONTROLLED_GRANT_DENIED', 'caller grants denied at lease');
$lease = $svc->issueLease(array_merge(['registration_uuid' => $reg], $correlation(12, 'lease')));
ok($lease['ok'] === true && $lease['state'] === 'lease_issued', 'signed lease issued');
ok((int) $lease['sequence'] === (int) $fixture['lease']['sequence_after_lease'], 'lease sequence is monotonic 1');
ok($lease['posture'] === 'paid' && $lease['authority_key_id'] === $fixture['lease']['lease_key_id'], 'paid posture under the authority lease key');
ok($lease['runtime_authorization'] === 'signed_device_bound_lease', 'runtime authorization is the signed device-bound lease');
$journey[] = $lease['state'];
$leaseRow = $db->query("SELECT payload_b64, signature_b64, state FROM wp_wpuiai_webpaid_leases WHERE lease_uuid = '" . $lease['lease_uuid'] . "'")->fetch(PDO::FETCH_ASSOC);
ok($leaseRow !== false && $leaseRow['state'] === 'active', 'lease stored active');
$leaseEnvelope = [
    'payload_b64' => $leaseRow['payload_b64'],
    'signature_b64' => $leaseRow['signature_b64'],
    'lease_public_key_b64' => $fixture['lease']['lease_public_key_b64'],
    'domain' => $fixture['lease']['domain'],
];

// Redacted receipt before refund: masked email/key, immutable handle.
$receiptBefore = $svc->receipt(['registration_uuid' => $reg]);
ok($receiptBefore['schema'] === 'focusa.spec152e.website_paid_receipt.v1', 'receipt schema');
ok($receiptBefore['state'] === 'lease_issued' && $receiptBefore['lease_sequence'] === 1 && $receiptBefore['lease_state'] === 'active', 'receipt reflects the signed lease');
ok($receiptBefore['install_site_authority'] === 'none' && $receiptBefore['spec158'] === 'excluded', 'no install-site authority; spec 158 excluded');
ok(preg_match('/^[0-9a-f]{64}$/', (string) $receiptBefore['receipt_sha256']) === 1, 'receipt carries an immutable sha256 handle');

// Refund cleanup: sequence increment, lease revoked, refresh denied, truth preserved.
$refund = $svc->refund(array_merge(['registration_uuid' => $reg, 'reason' => 'synthetic_proof_cleanup'], $correlation(13, 'refund')));
ok($refund['ok'] === true && $refund['state'] === 'refunded', 'EDD refund processed');
ok((int) $refund['sequence_after'] === (int) $fixture['lease']['sequence_after_refund'], 'refund increments the monotonic sequence to 2');
ok($refund['refresh_denied'] === true && $refund['posture'] === 'recovery_only', 'refresh denied; recovery-only posture');
ok($refund['account_order_delivery_node_evidence_preserved'] === true, 'refund cleanup preserves account/order/delivery/node/evidence');
$journey[] = $refund['state'];
$orderState = $db->query("SELECT state FROM wp_wpuiai_webpaid_orders WHERE order_id = " . (int) $edd['order_id'])->fetchColumn();
$licenseState = $db->query("SELECT state FROM wp_wpuiai_webpaid_licenses WHERE edd_license_id = " . (int) $edd['edd_license_id'])->fetchColumn();
$leaseState = $db->query("SELECT state FROM wp_wpuiai_webpaid_leases WHERE lease_uuid = '" . $lease['lease_uuid'] . "'")->fetchColumn();
ok($orderState === 'refunded' && $licenseState === 'refunded' && $leaseState === 'refunded', 'EDD refund propagates to order/license/lease');
$replayRefund = $svc->refund(array_merge(['registration_uuid' => $reg, 'reason' => 'synthetic_proof_cleanup'], $correlation(13, 'refund')));
ok($replayRefund['replayed'] === true && $replayRefund['zero_new_rows'] === true, 'refund replay writes zero new rows');

// Redacted receipt after refund.
$receiptAfter = $svc->receipt(['registration_uuid' => $reg]);
ok($receiptAfter['state'] === 'refunded' && $receiptAfter['lease_state'] === 'refunded' && $receiptAfter['lease_sequence'] === 2, 'post-refund receipt shows revoked lease and sequence 2');
ok($receiptAfter['masked_email'] === $customer['email_prefix_char'] . '***@' . $customer['email_domain'], 'post-refund receipt keeps the masked email');
ok($receiptAfter['key_mask'] === 'FOCUSA-B031-****-****-****', 'post-refund receipt keeps the masked key');

// ── Final counts: one account/order/license/node, refund truth preserved ────
$final = $counts();
$vectors = $fixture['journey']['journal_vectors'];
ok($final['registrations'] === $vectors['registrations'], 'registration row count pinned');
ok($final['identities'] === $vectors['identities'] && $final['accounts'] === $vectors['accounts'], 'identity/account row counts pinned');
ok($final['orders'] === $vectors['orders'] && $final['order_items'] === $vectors['order_items'], 'order/order-item row counts pinned');
ok($final['licenses'] === $vectors['licenses'] && $final['deliveries'] === $vectors['deliveries'], 'license/delivery row counts pinned');
ok($final['nodes'] === $vectors['nodes'] && $final['leases'] === $vectors['leases'], 'node/lease row counts pinned');
ok($final['sequences'] === $vectors['sequences'] && $final['refunds'] === $vectors['refunds'], 'sequence/refund row counts pinned');
ok($final['journal'] === $vectors['journal_events'], 'journal event count pinned');
$seqValue = (int) $db->query("SELECT current_sequence FROM wp_wpuiai_webpaid_sequences")->fetchColumn();
ok($seqValue === (int) $fixture['lease']['sequence_after_refund'], 'sequence ledger ends at 2');

// Rollback preservation: nothing destructive exists; preservation is recorded.
$preserved = $schema->preserveForRollback('2026-08-09T04:00:00Z', ['source' => 'website_paid_facade_rollback']);
ok($preserved['action'] === 'preserve', 'rollback is preservation-only');

$summary = [
    'schema' => 'focusa.spec152e.website_paid_facade_test.v1',
    'positive_checks' => $positive,
    'negative_checks' => $negative,
    'journey_states' => $journey,
    'counts' => $final,
    'sequence_after_refund' => $seqValue,
    'receipt_sha256' => $receiptAfter['receipt_sha256'],
    'lease_envelope' => $leaseEnvelope,
    'result' => 'passed_fail_closed',
];
fwrite(STDOUT, json_encode($summary, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES) . "\n");
"""


def run_harness() -> str:
    if not PHP:
        raise AssertionError("FAIL: php is required to execute the website paid facade journey")
    with tempfile.TemporaryDirectory() as tmp:
        harness_path = Path(tmp) / "website_paid_harness.php"
        harness_path.write_text(HARNESS, encoding="utf-8")
        proc = subprocess.run(
            [PHP, str(harness_path), str(CONTRACT), str(LEASE_CONTRACT), str(FIXTURE)],
            capture_output=True, text=True, timeout=180,
        )
        if proc.returncode != 0:
            raise AssertionError(f"FAIL: php harness exited {proc.returncode}: {proc.stderr[:2000]}")
        return proc.stdout.strip()


first = run_harness()
second = run_harness()
expect(first == second, "harness output is byte-identical across runs (replayable)")
result = json.loads(first)
expect(result["result"] == "passed_fail_closed", "harness passed fail-closed")

# ── Signed lease: independent Ed25519 verification (byte-compatible) ────────

lease_env = result["lease_envelope"]
lease_domain = lease_env["domain"].encode()
payload_bytes = base64.b64decode(lease_env["payload_b64"])
signature = base64.b64decode(lease_env["signature_b64"])
public_key = Ed25519PublicKey.from_public_bytes(base64.b64decode(lease_env["lease_public_key_b64"]))
try:
    public_key.verify(signature, lease_domain + payload_bytes)
    expect(True, "signed lease verifies with Ed25519 over the domain-separated payload")
except InvalidSignature as exc:  # pragma: no cover - only on signature breakage
    raise AssertionError(f"FAIL: signed lease did not verify: {exc}")
lease_payload = json.loads(payload_bytes)
expect(lease_payload["schema"] == "focusa.authority_lease.v1", "lease payload schema")
expect(lease_payload["posture"] == "paid" and lease_payload["product_code"] == "focusa_operator_lifetime_v1", "lease carries paid Focusa product posture")
expect(lease_payload["sequence"] == 1, "lease payload sequence 1")
expect(lease_payload["status"] == "active", "lease payload active at issuance")
expect(lease_payload["customer_id"] == 1001 and lease_payload["order_id"] == 9001 and lease_payload["edd_license_id"] == 7001, "lease binds customer/order/license truth")
expect(re.fullmatch(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", lease_payload["node_id"]) is not None and "device_public_key_hash" in lease_payload, "lease binds the registered node/device")

# ── Fixture structure and expectations ──────────────────────────────────────

fixture_raw = FIXTURE.read_text(encoding="utf-8")
fixture = json.loads(fixture_raw)
expect(fixture["schema"] == "focusa.spec152e.website_paid_facade_fixture.v1", "fixture schema id")
expect(fixture["fixture_id"] == "focusa-vbcqu.20.13.56", "fixture_id")
expect(fixture["fixture_kind"] == "public_synthetic_nonproduction", "public synthetic non-production fixture")
expect(fixture["authority"]["canonical"] == "WPUIAI.com EDD", "canonical authority")
expect(fixture["authority"]["new_issuance"] == "edd_authority_only", "new issuance edd only")
expect(fixture["authority"]["facade_role"] == "presenter_and_bounded_proxy_only", "facade presenter/proxy only")
expect(fixture["authority"]["install_site_authority"] == "none", "no install-site authority")
expect(fixture["authority"]["spec158"] == "excluded", "spec158 excluded")
expect(fixture["redaction"] == {
    "raw_email": "absent", "raw_key": "absent", "payment_id_stored": False,
    "secret_material": "absent", "receipt": "masked_email_and_key_mask_only",
}, "redaction posture")
expect(re.fullmatch(r"[0-9a-f]{64}", fixture["customer"]["email_digest"]) is not None, "email digest 64-hex")
expect(re.fullmatch(r"[0-9a-f]{64}", fixture["customer"]["invalid_email_digest"]) is not None, "invalid email digest 64-hex")
expect(fixture["customer"]["verification_code"] == "483921", "deterministic one-time verification code")
expect(fixture["product"]["product_code"] == "focusa_operator_lifetime_v1", "public product code")
expect(fixture["journey"]["expectations"]["pending_email_never_promotes"] is True, "pending email never promotes")
expect(fixture["journey"]["expectations"]["no_local_self_issued_entitlement"] is True, "no local/self-issued entitlement")
expect(fixture["journey"]["expectations"]["no_independent_facade_authority"] is True, "no independent facade authority")
expect(fixture["journey"]["expectations"]["client_price_grant_rejected"] is True, "client price/grants rejected")
expect(fixture["journey"]["expectations"]["checkout_email_mismatch_holds_fulfillment"] is True, "checkout email mismatch holds fulfillment")
expect(fixture["journey"]["expectations"]["payment_alone_never_verifies"] is True, "payment alone never verifies")
expect(fixture["journey"]["expectations"]["one_account_one_order_one_license_one_node"] is True, "one account/order/license/node")
expect(fixture["journey"]["expectations"]["same_canonical_key_email_and_account"] is True, "same canonical key both channels")
expect(fixture["journey"]["expectations"]["signed_lease_verifies"] is True, "signed lease verifies")
expect(fixture["journey"]["expectations"]["refund_increments_sequence_and_preserves_truth"] is True, "refund increments sequence and preserves truth")
expect(fixture["journey"]["expectations"]["receipt_redacted"] is True, "receipt redacted")
expect(fixture["journey"]["expectations"]["spec158_excluded"] is True, "spec158 excluded")

# ── Contract static invariants ──────────────────────────────────────────────

contract_raw = CONTRACT.read_text(encoding="utf-8")
expect("final class FocusaSpec152eWebsitePaidFacadeMigration" in contract_raw, "migration class")
expect("final class FocusaSpec152eWebsitePaidFacadeService" in contract_raw, "service class")
expect("focusa.spec152e.website_paid_facade.v1" in contract_raw, "contract schema id")
for table in (
    "wpuiai_webpaid_registrations", "wpuiai_webpaid_identities", "wpuiai_webpaid_accounts",
    "wpuiai_webpaid_orders", "wpuiai_webpaid_order_items", "wpuiai_webpaid_licenses",
    "wpuiai_webpaid_deliveries", "wpuiai_webpaid_nodes", "wpuiai_webpaid_leases",
    "wpuiai_webpaid_sequences", "wpuiai_webpaid_refunds", "wpuiai_webpaid_journal",
):
    expect(table in contract_raw, f"table {table}")
for method in (
    "function startRegistration", "function verifyEmail", "function promote",
    "function createCheckoutIntent", "function completePayment", "function issueLicense",
    "function deliver", "function registerNode", "function issueLease",
    "function refund", "function receipt",
):
    expect(method in contract_raw, f"method {method}")
for code in (
    "FACADE_ORIGIN_DENIED", "PRODUCT_MAPPING_REQUIRED", "CALLER_CONTROLLED_GRANT_DENIED",
    "EMAIL_VERIFICATION_REQUIRED", "EMAIL_VERIFICATION_FAILED", "EMAIL_VERIFICATION_EXPIRED",
    "EDD_CHECKOUT_REQUIRED", "EDD_ORDER_UNVERIFIED", "EDD_ORDER_PENDING",
    "EDD_LICENSE_PENDING", "EDD_LICENSE_UNUSABLE", "NODE_NOT_FOUND",
    "NODE_REQUIRED", "REFUND_STATE_REQUIRED", "REQUEST_ID_REQUIRED",
    "IDEMPOTENCY_KEY_REQUIRED", "IDEMPOTENCY_CONFLICT", "REGISTRATION_NOT_FOUND",
    "LICENSE_DELIVERY_PENDING",
):
    expect(code in contract_raw, f"fail-closed code {code}")
expect("PRODUCT_MAPPING" in contract_raw and "edd_download_id" in contract_raw, "server-owned product mapping")
expect("FACADE_ALLOWLIST" in contract_raw and "focusa_marketing_v1" in contract_raw, "registered facade allowlist")
expect("FocusaSpec152eEd25519Signer::LEASE_DOMAIN" in contract_raw, "canonical lease-signing domain")
expect("hash_equals" in contract_raw, "constant-time digest comparison")
expect("spec158" not in contract_raw or "excluded" in contract_raw, "spec158 excluded asserted")
expect("install_site_authority" in contract_raw, "install-site authority posture asserted")
expect("INSERT OR IGNORE" not in contract_raw or "preserveForRollback" in contract_raw, "preservation seam present")
# Preservation-only: no destructive path may exist anywhere in the contract.
for forbidden in ("DELETE FROM", "TRUNCATE", "DROP TABLE", "DROP INDEX"):
    expect(forbidden not in contract_raw, f"no destructive statement {forbidden}")
# No raw email or client-controlled price/grant inputs in the contract.
expect("customer_email" not in contract_raw and "raw_email TEXT" not in contract_raw and "raw_email VARCHAR" not in contract_raw, "no raw email storage field")
expect("'price' =>" not in contract_raw and "['price']" not in contract_raw, "no client-controlled price input")
expect("['grant']" not in contract_raw and "['grants']" not in contract_raw, "no client-controlled grant input")
expect("challenge_hash" in contract_raw and "challenge_used" in contract_raw, "challenge hashed, single-use at rest")

# ── Redaction: no secret or unmasked real-email evidence in artifacts ───────

EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
SECRET_RE = re.compile(r"(?i)(?:sk|rk|pk)_(?:live|test)_[A-Za-z0-9]+")
SYNTHETIC_KEY_RE = re.compile(r"(?i)focusa_live_[0-9]+_[0-9a-f]+")
PRIVATE_KEY_RE = re.compile(r"BEGIN (?:RSA |EC |)PRIVATE KEY")
GITHUB_TOKEN_RE = re.compile(r"ghp_[A-Za-z0-9]{8,}")
LICENSE_SHAPE_RE = re.compile(r"FOCUSA-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}")
for name, raw in (("fixture", fixture_raw), ("contract", contract_raw)):
    expect(EMAIL_RE.search(raw) is None, f"no email literal in {name}")
    expect(SECRET_RE.search(raw) is None, f"no stripe secret prefix in {name}")
    expect(SYNTHETIC_KEY_RE.search(raw) is None, f"no synthetic focusa_live key in {name}")
    expect(PRIVATE_KEY_RE.search(raw) is None, f"no private key material in {name}")
    expect(GITHUB_TOKEN_RE.search(raw) is None, f"no GitHub token in {name}")
    expect(LICENSE_SHAPE_RE.search(raw) is None, f"no raw license-shaped evidence in {name}")
    expect("payment_intent_id" not in raw, f"no payment intent id in {name}")
# The masked human key uses asterisk groups only; never a full key.
expect("FOCUSA-****-****-****-****" in fixture_raw, "fixture pins the masked key form")
expect("s***@invalid.example" not in fixture_raw and "s***[AT]invalid.example" not in fixture_raw, "fixture carries no email literal at all")

# ── Journey/journal vectors from the harness ────────────────────────────────

expect(result["journey_states"] == fixture["journey"]["states"], "journey states match the pinned state machine")
expected_counts = dict(fixture["journey"]["journal_vectors"])
expected_counts["journal"] = expected_counts.pop("journal_events")
expect(result["counts"] == expected_counts, "row counts match the pinned journal vectors")
expect(result["sequence_after_refund"] == 2, "sequence ledger ends at 2 after refund")
expect(re.fullmatch(r"[0-9a-f]{64}", result["receipt_sha256"]) is not None, "immutable receipt handle is 64-hex")

positive_checks = result["positive_checks"]
negative_checks = result["negative_checks"]

summary = {
    "schema": "focusa.spec152e.website_paid_e2e_validation.v1",
    "atom": "focusa-vbcqu.20.13.56",
    "fixture_sha256": sha256_text(fixture_raw),
    "contract_sha256": sha256_text(contract_raw),
    "harness_sha256": sha256_text(first),
    "positive_checks": positive_checks,
    "negative_checks": negative_checks,
    "journey_states": len(result["journey_states"]),
    "sequence_after_refund": result["sequence_after_refund"],
    "receipt_sha256": result["receipt_sha256"],
    "lease_signature_verified": True,
    "harness_replay_identical": True,
    "result": "passed",
}
print(json.dumps(summary, sort_keys=True))
