#!/usr/bin/env python3
"""Guard Spec 135 OpenAPI → TypeScript generation and portable contract parity."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "docs/contracts/spec135/generated-contract-v1/openapi-3.0.3.json"
TS = ROOT / "packages/generated/spec135/typescript/schema.d.ts"
GENERATOR = ROOT / "scripts/generate-spec135-clients.sh"

contract = json.loads(CONTRACT.read_text())
ts = TS.read_text()
generator = GENERATOR.read_text()

assert contract["openapi"] == "3.0.3"
assert (
    contract["x-focusa-json-schema-dialect"]
    == "https://json-schema.org/draft/2020-12/schema"
)
assert contract["paths"] and contract["components"]["schemas"]

methods = {"get", "post", "put", "patch", "delete"}
operations = [
    operation["operationId"]
    for path in contract["paths"].values()
    for method, operation in path.items()
    if method in methods
]
assert len(operations) == len(set(operations)) >= 45

for operation_id in operations:
    assert f'operations["{operation_id}"]' in ts, f"TypeScript missing {operation_id}"

assert "This file was auto-generated by openapi-typescript" in ts
assert "openapi-typescript@7.10.1" in generator
assert "oapi-codegen" not in generator
assert "go run" not in generator

print(f"Spec 135 generated clients: PASS ({len(operations)} operations)")
