#!/usr/bin/env python3
"""Spec 152E.07.07 prove refund, revoke, node-limit, sequence, and outage
behavior end-to-end (atom focusa-vbcqu.20.13.61).

Exact verification:
    python3 tests/spec152e_lifecycle_outage_e2e_test.py

Executes the Spec 152E §23 acceptance-matrix rows — Node limit, Refund,
Revocation, and Authority outage — plus the §17 lifecycle/outbox integration,
§18 refund/revoke/recovery chain, and §20 stable failure semantics on one
deterministic sqlite kernel (fixed clock, synthetic EDD fixture tables, frozen
contracts loaded read-only):

- EDD lifecycle (spec 152E §7.5/§17): order complete, refund, chargeback,
  revoke, expiry, subscription cancel, and upgrade/suspend transitions are
  projected to the exact EDD license state with a strictly monotonic authority
  sequence and an idempotent append-audited journal. Terminal states
  (refunded | revoked | expired | superseded | cancelled | denied) can never
  reactivate (LICENSE_TERMINAL_REACTIVATION_DENIED); out-of-order events can
  never roll the sequence back (ENTITLEMENT_SEQUENCE_ROLLBACK_DENIED);
  duplicate redeliveries journal as replayed with no bump; unknown statuses,
  raw email, and client-controlled commerce fields fail closed.
- Outbox/reconciler (spec 152E §7.6/§17): every EDD hook appends a signed
  outbox event in the same transaction as the projection; dispatch failure
  cannot lose canonical state (retry with backoff, tampered envelopes dead-
  letter, replay idempotent, delivery exactly once). A MISSED callback
  (canonical EDD license revoked with no projection and no outbox event) is
  repaired by the reconciler — the terminal projection is applied, the signed
  outbox event is appended, the run converges, and stale access can no longer
  refresh (signed REVOKED recovery-only refusal). Refund/revoke/sequence/
  callback truth is never rolled back and canonical EDD rows are preserved.
- Node reservations (spec 152E §10 / §23 "Node limit"): concurrent registrations
  are atomic reservation+settlement with a write-locked counter; the fourth
  concurrent node fails closed with NODE_LIMIT_EXHAUSTED; deactivation releases
  the slot exactly once and the explicit reserve/settle flow reuses it.
- Signer/refresh (spec 152E §10 POST /v1/lease/refresh, §15, §18): refresh with
  a current credential rotates the signed lease at a strictly higher sequence
  and re-seeds a one-time credential; refund/revoke/expiry/cancel/stale-sequence
  refresh returns a SIGNED recovery-only refusal (verifyRefusal proves it);
  a stale envelope is rejected client-side (STALE_SEQUENCE).
- Offline policy / authority outage (spec 152E §18/§20/§23 "Authority outage",
  §22.4): during an EDD outage no new local license can be issued
  (issueLease fails closed, lease count unchanged) and refresh denies with a
  signed EDD_LICENSE_UNUSABLE recovery-only refusal; the existing signed lease
  remains the only offline authority — verifyEnvelope returns active inside
  expiry, offline_grace inside expiry+grace, and EXPIRED past grace. Recovery
  remains available: signed refusals still verify and the recovery-only surface
  contract (spec 152E §18) preserves account verification, license status,
  export, diagnostics, repair, update, and uninstall while protected mutations
  stay forbidden.
- Rollback is preservation-only: preserveForRollback journals schema events on
  every surface and deletes nothing; EDD customer/order/refund truth, verified
  identities, licenses, nodes, sequences, credentials, and migration journals
  are preserved.

The php harness runs twice and its stdout is byte-identical (replayable from
the pinned commit). The bounded immutable result handle is the SHA-256 of the
exact harness output. Secrets and unmasked real email are absent from every
artifact. No push, deploy, release, merge, or Beads mutation is performed.
"""

import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ROOT / "docs/contracts"
SPEC = ROOT / "docs/152e-edd-centered-universal-multi-surface-licensing-and-branded-facade-addendum.md"
TESTS = ROOT / "tests"

PHP = "/usr/local/bin/php" if Path("/usr/local/bin/php").exists() else shutil.which("php")

positive = 0
negative = 0


def expect(condition: bool, message: str, is_negative: bool = False) -> None:
    global positive, negative
    if is_negative:
        negative += 1
    else:
        positive += 1
    if not condition:
        raise AssertionError(f"FAIL: {message}")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ── Deterministic PHP journey harness ───────────────────────────────────────

HARNESS = r"""<?php
// Spec 152E.07.07 lifecycle + outage e2e journey harness (generated by the
// python gate). Proves refund/chargeback/revoke/expiry/subscription-cancel
// projection, missed-callback reconciliation, concurrent node-limit
// reservations, signed refresh rotation/refusal, stale sequence/software
// denial, offline policy during an authority outage, and preservation-only
// rollback on one deterministic sqlite kernel with a fixed clock. Emits a
// deterministic redacted summary; every positive/negative check is counted.
// No raw email, raw EDD key, payment reference, or secret ever appears.
declare(strict_types=1);
$root = $argv[1];
require_once $root . '/docs/contracts/spec152e-authority-account.v1.php';
require_once $root . '/docs/contracts/spec152e-edd-lifecycle-projection.v1.php';
require_once $root . '/docs/contracts/spec152e-authority-outbox.v1.php';
require_once $root . '/docs/contracts/spec152e-authority-node.v1.php';
require_once $root . '/docs/contracts/spec152e-edd-bound-lease-issuer.v1.php';
require_once $root . '/docs/contracts/spec152e-lease-refresh-service.v1.php';
require_once $root . '/docs/contracts/spec152e-authority-reconciliation.v1.php';

$positive = 0;
$negative = 0;
function ok(bool $condition, string $message): void { global $positive; $positive++; if (!$condition) { fwrite(STDERR, "FAIL: {$message}\n"); exit(1); } }
function okThrows(callable $operation, string $code, string $message): void { global $negative; $negative++; try { $operation(); } catch (DomainException $error) { if ($error->getMessage() === $code) { return; } fwrite(STDERR, "FAIL: {$message} (got {$error->getMessage()})\n"); exit(1); } catch (InvalidArgumentException $error) { if ($error->getMessage() === $code) { return; } fwrite(STDERR, "FAIL: {$message} (got InvalidArgumentException: {$error->getMessage()})\n"); exit(1); } catch (RuntimeException $error) { if ($error->getMessage() === $code) { return; } fwrite(STDERR, "FAIL: {$message} (got RuntimeException: {$error->getMessage()})\n"); exit(1); } catch (Throwable $error) { fwrite(STDERR, "FAIL: {$message} (unexpected " . get_class($error) . ": " . $error->getMessage() . ")\n"); exit(1); } fwrite(STDERR, "FAIL: {$message} (no throw)\n"); exit(1); }

$db = new PDO('sqlite::memory:');
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$nowValue = '2026-08-08T20:00:00Z';
$clock = static function () use (&$nowValue): string { return $nowValue; };
$tick = static function (int $seconds) use (&$nowValue): void {
    $nowValue = gmdate('Y-m-d\TH:i:s\Z', (int) (new DateTimeImmutable($nowValue))->format('U') + $seconds);
};

$counts = static function (string $table) use ($db): int {
    return (int) $db->query("SELECT COUNT(*) FROM {$table}")->fetchColumn();
};
$deviceKey = static function (string $seed): string {
    return rtrim(strtr(base64_encode(hash('sha256', $seed, true)), '+/', '-_'), '=');
};

// ── EDD fixture tables (superset views; never the authority surface) ──
$db->exec("CREATE TABLE wp_edd_customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER,
    email TEXT NOT NULL, name TEXT NOT NULL, purchase_value TEXT NOT NULL DEFAULT '0.00',
    purchase_count INTEGER NOT NULL DEFAULT 0, notes TEXT NOT NULL DEFAULT '',
    date_created TEXT NOT NULL, stripe_customer_id TEXT NULL
)");
$db->exec("CREATE TABLE wp_edd_orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER,
    customer_id INTEGER NOT NULL, status TEXT NOT NULL, total TEXT NOT NULL,
    date_created TEXT NOT NULL, date_completed TEXT NULL
)");
$db->exec("CREATE TABLE wp_edd_order_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT, order_item_id INTEGER,
    order_id INTEGER NOT NULL, product_id INTEGER NOT NULL, price_id INTEGER NOT NULL DEFAULT 0,
    quantity INTEGER NOT NULL DEFAULT 1, subtotal TEXT NOT NULL, total TEXT NOT NULL
)");
$db->exec("CREATE TABLE wp_edd_licenses (
    id INTEGER PRIMARY KEY AUTOINCREMENT, license_id INTEGER,
    customer_id INTEGER NOT NULL, download_id INTEGER NOT NULL, payment_id INTEGER NULL,
    license_key TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active',
    activation_limit INTEGER NOT NULL DEFAULT 1, expiration TEXT NULL,
    date_created TEXT NOT NULL, order_id INTEGER NULL
)");
$db->exec("CREATE TABLE wp_edd_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT, subscription_id INTEGER,
    customer_id INTEGER NOT NULL, product_id INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'active', date_created TEXT NOT NULL
)");
// Authority account superset view (account repository / projector / outbox /
// issuer read different subsets of these columns).
$db->exec("CREATE TABLE wp_wpuiai_authority_accounts (
    account_uuid TEXT PRIMARY KEY, edd_customer_id INTEGER UNIQUE, customer_id INTEGER,
    wordpress_user_id INTEGER NULL, stripe_customer_id TEXT NULL, status TEXT, status_reason TEXT,
    highest_entitlement_sequence INTEGER, migration_provenance TEXT, created_at TEXT, updated_at TEXT
)");

function seed_paid(PDO $db, int $customerId, string $accountUuid, int $highest, int $orderId, int $itemId, int $licenseId, ?string $nodeId, string $deviceKey, int $nodeLimit = 3, string $licenseStatus = 'active', string $orderStatus = 'complete'): void
{
    $db->exec("INSERT OR IGNORE INTO wp_edd_customers (id, customer_id, email, name, purchase_value, purchase_count, notes, date_created, stripe_customer_id)
        VALUES ({$customerId}, {$customerId}, 'c{$customerId}@example.invalid', 'Fixture', '697.00', 1, '', '2026-08-01T00:00:00Z', NULL)");
    $db->exec("INSERT OR IGNORE INTO wp_wpuiai_authority_accounts (account_uuid, edd_customer_id, customer_id, wordpress_user_id, stripe_customer_id, status, status_reason, highest_entitlement_sequence, migration_provenance, created_at, updated_at)
        VALUES ('{$accountUuid}', {$customerId}, {$customerId}, NULL, NULL, 'active', 'mailbox_verified', {$highest}, '{}', '2026-08-01T00:00:00Z', '2026-08-01T00:00:00Z')");
    $db->exec("INSERT INTO wp_edd_orders (id, order_id, customer_id, status, total, date_created, date_completed)
        VALUES ({$orderId}, {$orderId}, {$customerId}, '{$orderStatus}', '697.00', '2026-08-01T00:00:00Z', '2026-08-01T00:00:01Z')");
    $db->exec("INSERT INTO wp_edd_order_items (id, order_item_id, order_id, product_id, price_id, quantity, subtotal, total)
        VALUES ({$itemId}, {$itemId}, {$orderId}, 1001, 0, 1, '697.00', '697.00')");
    $db->exec("INSERT INTO wp_edd_licenses (id, license_id, customer_id, download_id, payment_id, license_key, status, activation_limit, expiration, date_created, order_id)
        VALUES ({$licenseId}, {$licenseId}, {$customerId}, 1001, {$orderId}, 'LO-{$licenseId}-0001-0001-0001', '{$licenseStatus}', {$nodeLimit}, NULL, '2026-08-01T00:00:00Z', {$orderId})");
    if ($nodeId !== null) {
        $db->exec("INSERT INTO wp_wpuiai_authority_nodes (node_uuid, account_uuid, edd_license_id, product_code, device_public_key, assurance_class, status, status_reason, activated_at, reservation_id, settlement_id, migration_provenance, created_at, updated_at)
            VALUES ('{$nodeId}', '{$accountUuid}', {$licenseId}, 'focusa_operator_lifetime_v1', '{$deviceKey}', 'device_key_v1', 'active', 'device_registered', '2026-08-01T00:00:00Z', 'nr_seed_{$nodeId}', NULL, '{}', '2026-08-01T00:00:00Z', '2026-08-01T00:00:00Z')");
    }
}

// ── Migrations (all canonical schemas) ──
$accountMigration = new FocusaSpec152eAuthorityAccountMigration($db, 'wp_');
$accountMigration->migrate('2026-08-08T05:00:00Z', ['source' => 'lifecycle_outage_e2e']);
$accounts = new FocusaSpec152eAuthorityAccountRepository($db, $accountMigration, $clock);
$lifecycleSchema = new FocusaSpec152eEddLifecycleProjectionMigration($db, 'wp_');
$lifecycleSchema->migrate('2026-08-08T05:00:00Z', ['source' => 'lifecycle_outage_e2e']);
$projector = new FocusaSpec152eEddLifecycleProjector($db, $accounts, $lifecycleSchema, 'wp_', $clock);
$outboxSchema = new FocusaSpec152eAuthorityOutboxMigration($db, 'wp_');
$outboxSchema->migrate('2026-08-08T05:00:00Z', ['source' => 'lifecycle_outage_e2e']);
$eventSchema = new FocusaSpec152eAuthorityEventSchema();
$signer = new FocusaSpec152eAuthorityEventSigner('test-server-side-secret-for-spec152e-lifecycle-outage-e2e!', FocusaSpec152eAuthorityEventSchema::KEY_ID);
$hook = new FocusaSpec152eEddAuthorityHook($db, $outboxSchema, $eventSchema, $signer, $accounts, 'wp_', $clock);
$reconciliationMigration = new FocusaSpec152eAuthorityReconciliationMigration($db, 'wp_');
$reconciliationMigration->migrate('2026-08-08T05:00:00Z', ['source' => 'lifecycle_outage_e2e']);
$classifier = new FocusaSpec152eDiscrepancyClassifier();
$reconciler = new FocusaSpec152eAuthorityReconciler($db, $reconciliationMigration, $accounts, $projector, $hook, $classifier, 'wp_', $clock);
$nodeMigration = new FocusaSpec152eAuthorityNodeMigration($db, 'wp_');
$nodeMigration->migrate('2026-08-08T05:00:00Z', ['source' => 'lifecycle_outage_e2e']);
$nodes = new FocusaSpec152eAuthorityNodeRepository($db, $nodeMigration, $clock);
$keySet = new FocusaSpec152eAuthorityKeySetSeam(
    implode('', array_map('chr', range(0, 31))),
    implode('', array_map('chr', range(32, 63))),
    $clock,
);
$issuer = new FocusaSpec152eEddBoundLeaseIssuer($db, $keySet, $clock, 'wp_');
$issuer->migrate('2026-08-08T05:00:00Z', ['source' => 'lifecycle_outage_e2e']);
$refreshSchema = new FocusaSpec152eLeaseRefreshMigration($db, 'wp_');
$refreshSchema->migrate('2026-08-08T05:00:00Z', ['source' => 'lifecycle_outage_e2e']);
$refresh = new FocusaSpec152eLeaseRefreshService($db, $issuer, $keySet, $projector, $hook, $refreshSchema, 'wp_', $clock);
$failDeliver = static function (array $event): void {
    throw new RuntimeException('DELIVERY_CONSUMER_DOWN');
};
$deliverCalls = 0;
$goodDeliver = static function (array $event) use (&$deliverCalls): void {
    $deliverCalls++;
};
$failDispatcher = new FocusaSpec152eAuthorityOutboxDispatcher($db, $outboxSchema, $signer, $eventSchema, $failDeliver, $clock, 'wp_');
$goodDispatcher = new FocusaSpec152eAuthorityOutboxDispatcher($db, $outboxSchema, $signer, $eventSchema, $goodDeliver, $clock, 'wp_');

// ── Fixture accounts (fixed UUIDs; deterministic) ──
$A = 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d';   // node-limit + rotation
$R = 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e';   // refund
$C = 'c3d4e5f6-a7b8-4c9d-9a1f-2a3b4c5d6e7f';   // chargeback
$V = 'd4e5f6a7-b8c9-4d0e-8f2a-3b4c5d6e7f80';   // revoke
$E = 'e5f6a7b8-c9d0-4e1f-9a3b-4c5d6e7f8091';   // expiry
$S = 'f6a7b8c9-d0e1-4f2a-9b4c-5d6e7f8a90b2';   // subscription cancel
$B = 'a7b8c9d0-e1f2-4a3b-9c5d-6e7f8a90b1c3';   // stale sequence/software (upgrade+suspend)
$M = 'b8c9d0e1-f2a3-4b4c-9d6e-7f8a90b1c2d4';   // missed callback (reconciler)
$O = 'c9d0e1f2-a3b4-4c5d-9e7f-8a90b1c2d3e5';   // authority outage / offline policy
$Q = 'd0e1f2a3-b4c5-4d6e-8f8a-90b1c2d3e4f6';   // lease without credential
$Q2 = 'e1f2a3b4-c5d6-4e7f-8a90-b1c2d3e4f5a7';  // wrong credential refusal

$PAID = 'focusa_operator_lifetime_v1';
$DK1 = $deviceKey('lifecycle-outage-e2e-device-0001');
$DK2 = $deviceKey('lifecycle-outage-e2e-device-0002');
$DK3 = $deviceKey('lifecycle-outage-e2e-device-0003');
$DK4 = $deviceKey('lifecycle-outage-e2e-device-0004');
$DK5 = $deviceKey('lifecycle-outage-e2e-device-0005');

// A: node-limit + rotation account (license limit 3; no node seeded directly).
seed_paid($db, 1001, $A, 10, 9001, 91001, 7001, null, $DK1, 3);
// Lifecycle terminal-state accounts.
seed_paid($db, 2001, $R, 10, 9002, 91002, 7002, 'node-refund-0001', $deviceKey('node-refund-0001'), 3);
seed_paid($db, 2002, $C, 10, 9003, 91003, 7003, 'node-chargeback-0001', $deviceKey('node-chargeback-0001'), 3);
seed_paid($db, 2003, $V, 10, 9004, 91004, 7004, 'node-revoke-0001', $deviceKey('node-revoke-0001'), 3);
seed_paid($db, 2004, $E, 10, 9005, 91005, 7005, 'node-expiry-0001', $deviceKey('node-expiry-0001'), 3);
seed_paid($db, 2005, $S, 10, 9006, 91006, 7006, 'node-cancel-0001', $deviceKey('node-cancel-0001'), 3);
// B: stale sequence/software.
seed_paid($db, 2006, $B, 30, 9007, 91007, 7007, 'node-stale-0001', $deviceKey('node-stale-0001'), 3);
// M: missed callback (license revoked later; no EDD hook fired).
seed_paid($db, 2007, $M, 10, 9008, 91008, 7008, 'node-missed-0001', $deviceKey('node-missed-0001'), 3);
// O: outage / offline policy.
seed_paid($db, 2008, $O, 10, 9009, 91009, 7009, 'node-outage-0001', $deviceKey('node-outage-0001'), 3);
// Q / Q2: refresh-credential negatives.
seed_paid($db, 2009, $Q, 10, 9010, 91010, 7010, 'node-credless-0001', $deviceKey('node-credless-0001'), 3);
seed_paid($db, 2010, $Q2, 10, 9011, 91011, 7011, 'node-wrongcred-0001', $deviceKey('node-wrongcred-0001'), 3);
$db->exec("INSERT INTO wp_edd_subscriptions (id, subscription_id, customer_id, product_id, status, date_created)
    VALUES (61001, 61001, 2005, 1001, 'active', '2026-08-01T00:00:00Z')");

// ── 1. Concurrent node limit: register / exhaust / release / re-reserve ──

$nodeSeq = 0;
$register = static function (string $nodeUuid, string $account, int $licenseId, string $device) use ($nodes, &$nodeSeq): array {
    $nodeSeq++;
    return $nodes->registerNode([
        'node_uuid' => $nodeUuid,
        'account_uuid' => $account,
        'edd_license_id' => $licenseId,
        'product_code' => 'focusa_operator_lifetime_v1',
        'device_public_key' => $device,
        'assurance_class' => 'device_key_v1',
        'idempotency_key' => 'idem-node-limit-' . $nodeSeq,
        'migration_provenance' => ['source' => 'lifecycle_outage_e2e', 'record' => 'node-limit-' . $nodeSeq],
    ]);
};
$n1 = $register('11111111-1111-4111-8111-111111111111', $A, 7001, $DK1);
$n2 = $register('22222222-2222-4222-8222-222222222222', $A, 7001, $DK2);
$n3 = $register('33333333-3333-4333-8333-333333333333', $A, 7001, $DK3);
ok($n1['status'] === 'active' && $n2['status'] === 'active' && $n3['status'] === 'active', 'three concurrent nodes register within the limit');
$ledger = $nodes->limitLedger($A, 'focusa_operator_lifetime_v1');
ok((int) $ledger['node_limit'] === 3 && (int) $ledger['reserved_count'] === 3, 'node-limit ledger reserves exactly three slots of three');
okThrows(
    static fn() => $register('44444444-4444-4444-8444-444444444444', $A, 7001, $DK4),
    'NODE_LIMIT_EXHAUSTED',
    'the fourth concurrent node is denied at the limit',
);
$nodeCountA = (int) $db->query("SELECT COUNT(*) FROM wp_wpuiai_authority_nodes WHERE account_uuid = '{$A}'")->fetchColumn();
ok($nodeCountA === 3, 'the denied fourth node created no node row for the account');
ok($counts('wp_wpuiai_authority_node_reservations') === 3, 'the denied fourth node created no reservation row');
// Explicit node management: deactivation releases the slot exactly once.
$deactivated = $nodes->deactivateNode([
    'node_uuid' => '33333333-3333-4333-8333-333333333333',
    'account_uuid' => $A,
    'status_reason' => 'user_requested',
    'idempotency_key' => 'idem-node-deactivate-0001',
]);
ok($deactivated['status'] === 'deactivated', 'explicit deactivation succeeds');
$ledgerAfter = $nodes->limitLedger($A, 'focusa_operator_lifetime_v1');
ok((int) $ledgerAfter['reserved_count'] === 2, 'deactivation releases the node slot exactly once');
// The freed slot is reused through the explicit reserve/settle flow.
$reservation = $nodes->reserve([
    'node_uuid' => '44444444-4444-4444-8444-444444444444',
    'account_uuid' => $A,
    'edd_license_id' => 7001,
    'product_code' => 'focusa_operator_lifetime_v1',
    'device_public_key' => $DK4,
    'assurance_class' => 'device_key_v1',
    'idempotency_key' => 'idem-node-reserve-0001',
    'migration_provenance' => ['source' => 'lifecycle_outage_e2e', 'record' => 'reserve-0001'],
]);
ok(($reservation['state'] ?? '') === 'reserved', 'freed slot is reserved by the explicit two-phase flow');
$settled = $nodes->settleReservation((string) $reservation['reservation_id'], 'ns_reuse_0001', 'idem-node-settle-0001');
ok($settled['status'] === 'active', 'reserved slot settles to an active node');
okThrows(
    static fn() => $nodes->reserve([
        'node_uuid' => '55555555-5555-4555-8555-555555555555',
        'account_uuid' => $A,
        'edd_license_id' => 7001,
        'product_code' => 'focusa_operator_lifetime_v1',
        'device_public_key' => $DK5,
        'assurance_class' => 'device_key_v1',
        'idempotency_key' => 'idem-node-reserve-0002',
        'migration_provenance' => ['source' => 'lifecycle_outage_e2e', 'record' => 'reserve-0002'],
    ]),
    'NODE_LIMIT_EXHAUSTED',
    'a sixth reservation attempt is again denied at the limit',
);
$ledgerFinal = $nodes->limitLedger($A, 'focusa_operator_lifetime_v1');
ok((int) $ledgerFinal['reserved_count'] === 3, 'ledger holds exactly three live slots after deactivate + re-reserve');
okThrows(
    static fn() => $register('66666666-6666-4666-8666-666666666666', $A, 7001, 'not-a-valid-device-key!!'),
    'NODE_PUBLIC_KEY_REQUIRED',
    'a malformed device key fails closed before any reservation',
);

// ── 2. Account A: signed lease issuance + refresh rotation ──

$completeA = $projector->projectOrder([
    'status' => 'completed', 'account_uuid' => $A, 'edd_customer_id' => 1001,
    'order_id' => 9001, 'license_id' => 7001,
    'request_id' => 'req-complete-a-0001', 'idempotency_key' => 'idem-complete-a-0001',
]);
ok($completeA['decision'] === 'applied' && $completeA['to_state'] === 'active' && (int) $completeA['result_sequence'] === 11, 'order completion projects active at sequence 11');
$leaseA = $issuer->issueLease([
    'account_uuid' => $A, 'product_code' => $PAID, 'node_id' => '11111111-1111-4111-8111-111111111111',
    'device_public_key' => $DK1, 'idempotency_key' => 'lease-a-0001', 'request_id' => 'req-lease-a-0001',
]);
ok((int) $leaseA['sequence'] === 12, 'lease A issued at server sequence 12');
$credA = (string) $refresh->issueRefreshCredential(['lease_uuid' => $leaseA['lease_uuid'], 'idempotency_key' => 'cred-a-0001', 'request_id' => 'req-cred-a-0001'])['refresh_credential'];
ok(str_starts_with($credA, 'rc_'), 'refresh credential is an opaque bounded token');
$rotation = $refresh->refresh([
    'account_uuid' => $A, 'product_code' => $PAID, 'node_id' => '11111111-1111-4111-8111-111111111111',
    'refresh_credential' => $credA, 'current_sequence' => 12,
    'idempotency_key' => 'refresh-a-0001', 'request_id' => 'req-refresh-a-0001',
]);
ok(($rotation['decision'] ?? '') === 'rotated' && ($rotation['state'] ?? '') === 'activated', 'refresh with a current credential rotates to activated');
ok((int) $rotation['lease']['sequence'] === 13, 'rotated lease sequence is strictly monotonic (13)');
ok((string) $rotation['lease']['claims']['previous_lease_digest'] === 'sha256:' . hash('sha256', FocusaSpec152eAuthorityKeySetSeam::decodePayload($leaseA['envelope']['payload_b64']), ), 'rotated lease chains the exact prior payload digest');
$oldLeaseRow = $issuer->findLease($leaseA['lease_uuid']);
ok(($oldLeaseRow['status'] ?? '') === 'superseded' && ($oldLeaseRow['status_reason'] ?? '') === 'refresh_rotated', 'presented lease settled superseded on rotation');
$highestA = $refresh->highestSequence($A, $PAID);
ok((int) $highestA['highest_sequence'] === 13, 'highest sequence surface reports 13 after rotation');
$rotCredA = (string) $rotation['refresh_credential'];
ok(str_starts_with($rotCredA, 'rc_') && ($refresh->credentialRow((string) $rotation['lease']['lease_uuid'])['credential_digest'] ?? '') === hash('sha256', $rotCredA), 'rotation re-seeds a one-time credential bound to the rotated lease');
$eventTypesA = array_column($db->query("SELECT event_type FROM wp_wpuiai_authority_outbox ORDER BY created_at")->fetchAll(PDO::FETCH_ASSOC), 'event_type');
ok(in_array('lease_superseded', $eventTypesA, true) && in_array('lease_issued', $eventTypesA, true), 'rotation journals lease_superseded + lease_issued outbox events');

// ── 3. EDD lifecycle matrix: terminal projections + signed refresh refusals ──

/** One complete -> lease -> credential -> hook -> terminal projection -> refresh chain. */
$issuePaidJourney = static function (string $account, int $customer, int $orderId, int $licenseId, string $nodeId, string $device, string $tag, string $issuedAt = '2026-08-08T20:00:00Z', bool $withCredential = true) use ($projector, $issuer, $refresh, $hook, $PAID, $db, $clock): array {
    $projector->projectOrder([
        'status' => 'completed', 'account_uuid' => $account, 'edd_customer_id' => $customer,
        'order_id' => $orderId, 'license_id' => $licenseId,
        'request_id' => 'req-complete-' . $tag, 'idempotency_key' => 'idem-complete-' . $tag,
    ]);
    $db->beginTransaction();
    try {
        $hook->appendFromEdd([
            'surface' => 'order', 'status' => 'completed', 'account_uuid' => $account,
            'edd_customer_id' => $customer, 'order_id' => $orderId, 'license_id' => $licenseId,
            'request_id' => 'req-hook-complete-' . $tag, 'idempotency_key' => 'idem-hook-complete-' . $tag,
        ]);
        $db->commit();
    } catch (Throwable $error) {
        if ($db->inTransaction()) { $db->rollBack(); }
        throw $error;
    }
    $lease = $issuer->issueLease([
        'account_uuid' => $account, 'product_code' => $PAID, 'node_id' => $nodeId,
        'device_public_key' => $device, 'idempotency_key' => 'lease-' . $tag,
        'request_id' => 'req-lease-' . $tag, 'issued_at' => $issuedAt,
    ]);
    $credential = '';
    if ($withCredential) {
        $credential = (string) $refresh->issueRefreshCredential(['lease_uuid' => $lease['lease_uuid'], 'idempotency_key' => 'cred-' . $tag, 'request_id' => 'req-cred-' . $tag])['refresh_credential'];
    }
    return ['lease' => $lease, 'credential' => $credential];
};

$refreshRequest = static function (string $account, string $nodeId, string $credential, string $ikey, ?int $currentSequence = null, string $product = '') use ($PAID): array {
    $product = $product === '' ? $PAID : $product;
    return array_filter([
        'account_uuid' => $account, 'product_code' => $product, 'node_id' => $nodeId,
        'refresh_credential' => $credential, 'current_sequence' => $currentSequence,
        'idempotency_key' => $ikey, 'request_id' => 'req-' . $ikey,
    ], static fn(mixed $value): bool => $value !== null);
};

/** Assert a signed recovery-only refusal with the exact reason. */
$expectRefusal = static function (array $result, string $reason, string $message) use ($refresh, &$positive): void {
    $positive++;
    $decisionValue = $result['decision'] ?? 'none';
    $stateValue = $result['state'] ?? 'none';
    $errorValue = $result['error'] ?? 'none';
    if ($decisionValue !== 'denied' || $stateValue !== 'recovery_only' || $errorValue !== $reason) {
        fwrite(STDERR, "FAIL: {$message} (decision={$decisionValue} state={$stateValue} error={$errorValue})\n");
        exit(1);
    }
    $refusal = $result['refusal'] ?? null;
    if (!is_array($refusal) || ($refusal['schema'] ?? '') !== 'focusa.signed_envelope.v1') {
        fwrite(STDERR, "FAIL: {$message} (signed refusal envelope missing)\n");
        exit(1);
    }
    $verified = $refresh->verifyRefusal($refusal, ['now' => (string) ($result['created_at'] ?? '2026-08-08T20:00:00Z')]);
    if (($verified['reason_code'] ?? '') !== $reason || ($verified['posture'] ?? '') !== 'recovery_only') {
        fwrite(STDERR, "FAIL: {$message} (verified reason=" . ($verified['reason_code'] ?? 'none') . " posture=" . ($verified['posture'] ?? 'none') . ")\n");
        exit(1);
    }
    $positive++;
};

// R: refund — EDD refunded -> sequence increment -> refresh denied / recovery-only.
$rJourney = $issuePaidJourney($R, 2001, 9002, 7002, 'node-refund-0001', $deviceKey('node-refund-0001'), 'r0001');
$db->beginTransaction();
try {
    $hook->appendFromEdd([
        'surface' => 'refund', 'status' => 'refunded', 'account_uuid' => $R, 'edd_customer_id' => 2001,
        'order_id' => 9002, 'license_id' => 7002,
        'request_id' => 'req-hook-refund-r0001', 'idempotency_key' => 'idem-hook-refund-r0001',
    ]);
    $db->commit();
} catch (Throwable $error) {
    if ($db->inTransaction()) { $db->rollBack(); }
    throw $error;
}
$db->exec("UPDATE wp_edd_licenses SET status = 'refunded' WHERE id = 7002");
$refund = $projector->projectRefund([
    'status' => 'refunded', 'account_uuid' => $R, 'edd_customer_id' => 2001,
    'order_id' => 9002, 'license_id' => 7002,
    'request_id' => 'req-refund-r0001', 'idempotency_key' => 'idem-refund-r0001',
]);
ok($refund['decision'] === 'applied' && $refund['to_state'] === 'refunded' && $refund['refresh_posture'] === 'recovery_only' && (int) $refund['result_sequence'] === 12, 'refund projects refunded / recovery_only at sequence 12');
$refundRefusal = $refresh->refresh($refreshRequest($R, 'node-refund-0001', $rJourney['credential'], 'refresh-r0001', 12));
$expectRefusal($refundRefusal, 'REFUNDED', 'refunded license refresh is denied with a signed recovery-only refusal');
$refundLeaseRow = $issuer->findLease($rJourney['lease']['lease_uuid']);
ok(($refundLeaseRow['status'] ?? '') === 'refunded' && ($refundLeaseRow['status_reason'] ?? '') === 'edd_refunded', 'refund refusal settles the lease to refunded/edd_refunded');
$replayRefund = $projector->projectRefund([
    'status' => 'refunded', 'account_uuid' => $R, 'edd_customer_id' => 2001,
    'order_id' => 9002, 'license_id' => 7002,
    'request_id' => 'req-refund-r0001', 'idempotency_key' => 'idem-refund-r0001',
]);
ok($replayRefund['decision'] === 'replayed', 'refund redelivery journals as replayed');
ok((int) $db->query("SELECT highest_entitlement_sequence FROM wp_wpuiai_authority_accounts WHERE account_uuid = '{$R}'")->fetchColumn() === 12, 'replayed refund never bumps the sequence');
$reactivate = $projector->projectOrder([
    'status' => 'completed', 'account_uuid' => $R, 'edd_customer_id' => 2001,
    'order_id' => 9002, 'license_id' => 7002,
    'request_id' => 'req-reactivate-r0001', 'idempotency_key' => 'idem-reactivate-r0001',
]);
ok($reactivate['decision'] === 'denied' && $reactivate['error_code'] === 'LICENSE_TERMINAL_REACTIVATION_DENIED', 'a completed order can never reactivate a refunded license');
$rollback = $projector->projectOrder([
    'status' => 'completed', 'account_uuid' => $R, 'edd_customer_id' => 2001,
    'order_id' => 9002, 'license_id' => 7002, 'authority_sequence' => 5,
    'request_id' => 'req-rollback-r0001', 'idempotency_key' => 'idem-rollback-r0001',
]);
ok($rollback['decision'] === 'denied' && $rollback['error_code'] === 'ENTITLEMENT_SEQUENCE_ROLLBACK_DENIED', 'an out-of-order authority ordinal can never roll the sequence back');
$replayRefusal = $refresh->refresh($refreshRequest($R, 'node-refund-0001', $rJourney['credential'], 'refresh-r0001', 12));
ok(($replayRefusal['replayed'] ?? false) === true && ($replayRefusal['decision'] ?? '') === 'denied', 'refresh refusal replay is idempotent under the same key');
$rLifecycle = $db->query("SELECT license_state, refresh_posture FROM wp_wpuiai_edd_lifecycle_events WHERE account_uuid = '{$R}' AND decision IN ('applied','replayed') ORDER BY result_sequence DESC, created_at DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);
ok($rLifecycle['license_state'] === 'refunded' && $rLifecycle['refresh_posture'] === 'recovery_only', 'account posture settles to recovery_only after refund');

// C: chargeback — Stripe disputed -> refunded / recovery_only.
$cJourney = $issuePaidJourney($C, 2002, 9003, 7003, 'node-chargeback-0001', $deviceKey('node-chargeback-0001'), 'c0001');
$db->beginTransaction();
try {
    $hook->appendFromEdd([
        'surface' => 'refund', 'status' => 'chargeback', 'account_uuid' => $C, 'edd_customer_id' => 2002,
        'order_id' => 9003, 'license_id' => 7003,
        'request_id' => 'req-hook-chargeback-c0001', 'idempotency_key' => 'idem-hook-chargeback-c0001',
    ]);
    $db->commit();
} catch (Throwable $error) {
    if ($db->inTransaction()) { $db->rollBack(); }
    throw $error;
}
$chargeback = $projector->projectStripe([
    'status' => 'disputed', 'account_uuid' => $C, 'edd_customer_id' => 2002,
    'order_id' => 9003, 'license_id' => 7003,
    'request_id' => 'req-chargeback-c0001', 'idempotency_key' => 'idem-chargeback-c0001',
]);
ok($chargeback['decision'] === 'applied' && $chargeback['transition'] === 'chargeback' && $chargeback['to_state'] === 'refunded' && $chargeback['refresh_posture'] === 'recovery_only', 'Stripe dispute projects a chargeback to refunded / recovery_only');
$db->exec("UPDATE wp_edd_licenses SET status = 'refunded' WHERE id = 7003");
$chargebackRefusal = $refresh->refresh($refreshRequest($C, 'node-chargeback-0001', $cJourney['credential'], 'refresh-c0001', 12));
$expectRefusal($chargebackRefusal, 'REFUNDED', 'chargeback refresh is denied with a signed recovery-only refusal');

// V: revoke — immediate authority denial with durable audit.
$vJourney = $issuePaidJourney($V, 2003, 9004, 7004, 'node-revoke-0001', $deviceKey('node-revoke-0001'), 'v0001');
$db->beginTransaction();
try {
    $hook->appendFromEdd([
        'surface' => 'license', 'status' => 'revoked', 'account_uuid' => $V, 'edd_customer_id' => 2003,
        'license_id' => 7004, 'request_id' => 'req-hook-revoke-v0001', 'idempotency_key' => 'idem-hook-revoke-v0001',
    ]);
    $db->commit();
} catch (Throwable $error) {
    if ($db->inTransaction()) { $db->rollBack(); }
    throw $error;
}
$revoke = $projector->projectLicense([
    'from_status' => 'active', 'to_status' => 'revoked', 'account_uuid' => $V, 'edd_customer_id' => 2003,
    'license_id' => 7004, 'request_id' => 'req-revoke-v0001', 'idempotency_key' => 'idem-revoke-v0001',
]);
ok($revoke['decision'] === 'applied' && $revoke['to_state'] === 'revoked' && $revoke['refresh_posture'] === 'recovery_only', 'revocation projects revoked / recovery_only');
$db->exec("UPDATE wp_edd_licenses SET status = 'revoked' WHERE id = 7004");
$revokeRefusal = $refresh->refresh($refreshRequest($V, 'node-revoke-0001', $vJourney['credential'], 'refresh-v0001', 12));
$expectRefusal($revokeRefusal, 'REVOKED', 'revocation denies refresh immediately with a signed recovery-only refusal');
$vLeaseRow = $issuer->findLease($vJourney['lease']['lease_uuid']);
ok(($vLeaseRow['status'] ?? '') === 'revoked' && ($vLeaseRow['status_reason'] ?? '') === 'edd_revoked', 'revoke refusal settles the lease to revoked/edd_revoked');
$vOutbox = $db->query("SELECT event_type FROM wp_wpuiai_authority_outbox WHERE account_uuid = '{$V}'")->fetchAll(PDO::FETCH_ASSOC);
$vEventTypes = array_column($vOutbox, 'event_type');
ok(in_array('license_revoked', $vEventTypes, true) && in_array('lease_revoked', $vEventTypes, true), 'revocation carries a durable audit trail (license_revoked + lease_revoked outbox events)');
ok((int) $db->query("SELECT COUNT(*) FROM wp_wpuiai_edd_lifecycle_events WHERE account_uuid = '{$V}' AND decision IN ('applied','replayed')")->fetchColumn() === 2, 'revocation journal retains the complete + revoke projection history');

// E: expiry — expired / recovery_only, refresh denied.
$eJourney = $issuePaidJourney($E, 2004, 9005, 7005, 'node-expiry-0001', $deviceKey('node-expiry-0001'), 'e0001');
$db->beginTransaction();
try {
    $hook->appendFromEdd([
        'surface' => 'license', 'status' => 'expired', 'account_uuid' => $E, 'edd_customer_id' => 2004,
        'license_id' => 7005, 'request_id' => 'req-hook-expiry-e0001', 'idempotency_key' => 'idem-hook-expiry-e0001',
    ]);
    $db->commit();
} catch (Throwable $error) {
    if ($db->inTransaction()) { $db->rollBack(); }
    throw $error;
}
$expiry = $projector->projectLicense([
    'from_status' => 'active', 'to_status' => 'expired', 'account_uuid' => $E, 'edd_customer_id' => 2004,
    'license_id' => 7005, 'request_id' => 'req-expiry-e0001', 'idempotency_key' => 'idem-expiry-e0001',
]);
ok($expiry['decision'] === 'applied' && $expiry['to_state'] === 'expired' && $expiry['refresh_posture'] === 'recovery_only', 'expiry projects expired / recovery_only');
$db->exec("UPDATE wp_edd_licenses SET status = 'expired' WHERE id = 7005");
$expiryRefusal = $refresh->refresh($refreshRequest($E, 'node-expiry-0001', $eJourney['credential'], 'refresh-e0001', 12));
$expectRefusal($expiryRefusal, 'EXPIRED', 'expired license refresh is denied with a signed recovery-only refusal');

// S: subscription cancel — cancelled / recovery_only, refresh denied.
$sJourney = $issuePaidJourney($S, 2005, 9006, 7006, 'node-cancel-0001', $deviceKey('node-cancel-0001'), 's0001');
$db->beginTransaction();
try {
    $hook->appendFromEdd([
        'surface' => 'subscription', 'status' => 'cancelled', 'account_uuid' => $S, 'edd_customer_id' => 2005,
        'subscription_id' => 61001, 'request_id' => 'req-hook-cancel-s0001', 'idempotency_key' => 'idem-hook-cancel-s0001',
    ]);
    $db->commit();
} catch (Throwable $error) {
    if ($db->inTransaction()) { $db->rollBack(); }
    throw $error;
}
$cancel = $projector->projectSubscription([
    'status' => 'cancelled', 'account_uuid' => $S, 'edd_customer_id' => 2005,
    'subscription_id' => 61001, 'license_id' => 7006,
    'request_id' => 'req-cancel-s0001', 'idempotency_key' => 'idem-cancel-s0001',
]);
ok($cancel['decision'] === 'applied' && $cancel['to_state'] === 'cancelled' && $cancel['refresh_posture'] === 'recovery_only', 'subscription cancellation projects cancelled / recovery_only');
$db->exec("UPDATE wp_edd_subscriptions SET status = 'cancelled' WHERE id = 61001");
$cancelRefusal = $refresh->refresh($refreshRequest($S, 'node-cancel-0001', $sJourney['credential'], 'refresh-s0001', 12));
$expectRefusal($cancelRefusal, 'CANCELLED', 'cancelled subscription refresh is denied with a signed recovery-only refusal');

// ── 4. Stale sequence / stale software (account B) ──

$bJourney = $issuePaidJourney($B, 2006, 9007, 7007, 'node-stale-0001', $deviceKey('node-stale-0001'), 'b0001');
ok((int) $bJourney['lease']['sequence'] === 32, 'stale-account lease issued at sequence 32');
$upgrade = $projector->projectTransition([
    'surface' => 'order', 'transition' => 'upgrade', 'account_uuid' => $B, 'edd_customer_id' => 2006,
    'license_id' => 7007, 'request_id' => 'req-upgrade-b0001', 'idempotency_key' => 'idem-upgrade-b0001',
]);
ok($upgrade['decision'] === 'applied' && $upgrade['to_state'] === 'superseded', 'upgrade supersedes the prior entitlement state');
$suspend = $projector->projectTransition([
    'surface' => 'order', 'transition' => 'suspend', 'account_uuid' => $B, 'edd_customer_id' => 2006,
    'license_id' => 7007, 'request_id' => 'req-suspend-b0001', 'idempotency_key' => 'idem-suspend-b0001',
]);
ok($suspend['decision'] === 'applied' && $suspend['refresh_posture'] === 'denied', 'suspend projects denied refresh posture');
$staleRefusal = $refresh->refresh($refreshRequest($B, 'node-stale-0001', $bJourney['credential'], 'refresh-b0001', 32));
$expectRefusal($staleRefusal, 'STALE_SEQUENCE', 'a stale-sequence lease (old software) cannot refresh');
$bLeaseRow = $issuer->findLease($bJourney['lease']['lease_uuid']);
ok(($bLeaseRow['status'] ?? '') === 'superseded' && ($bLeaseRow['status_reason'] ?? '') === 'stale_sequence', 'stale lease settles superseded/stale_sequence');
okThrows(
    static fn() => $issuer->verifyEnvelope($bJourney['lease']['envelope'], [
        'expected_product' => 'focusa', 'expected_node_id' => 'node-stale-0001',
        'now' => ($clock)(), 'minimum_sequence' => 33,
    ]),
    'STALE_SEQUENCE',
    'client-side verification rejects a stale envelope below the authority sequence',
);
okThrows(
    static fn() => $issuer->verifyEnvelope($bJourney['lease']['envelope'], [
        'expected_product' => 'focusa', 'expected_node_id' => 'node-other-0001',
        'now' => ($clock)(),
    ]),
    'WRONG_NODE',
    'client-side verification rejects an envelope bound to another node',
);

// ── 5. Missed callback: reconciler repairs canonical truth, access cannot persist ──

$mJourney = $issuePaidJourney($M, 2007, 9008, 7008, 'node-missed-0001', $deviceKey('node-missed-0001'), 'm0001');
// The EDD hook NEVER fired: the canonical license row is revoked with no
// projection and no outbox event (a missed callback).
$db->exec("UPDATE wp_edd_licenses SET status = 'revoked' WHERE id = 7008");
$dryRun = $reconciler->run('dry_run', ['license']);
ok(($dryRun['summary']['repairs_applied'] ?? 0) === 0, 'dry-run applies zero repairs');
ok(($dryRun['summary']['repairable'] ?? 0) >= 1, 'dry-run reports the missed-callback repair candidate');
$applyRun = $reconciler->run('apply', ['license']);
ok(($applyRun['summary']['repairs_applied'] ?? 0) === 2, 'apply repairs the missed callback (projection + signed outbox event)');
ok(($applyRun['summary']['converged'] ?? false) === true, 'apply run converges on the license surface');
$missedProjection = $db->query("SELECT license_state, refresh_posture FROM wp_wpuiai_edd_lifecycle_events WHERE account_uuid = '{$M}' AND decision IN ('applied','replayed') ORDER BY result_sequence DESC, created_at DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);
ok($missedProjection['license_state'] === 'revoked' && $missedProjection['refresh_posture'] === 'recovery_only', 'reconciler projects the missed revoke callback to revoked / recovery_only');
ok($db->query("SELECT COUNT(*) FROM wp_wpuiai_authority_outbox WHERE account_uuid = '{$M}' AND event_type = 'license_revoked'")->fetchColumn() === 1, 'reconciler appends the missing signed license_revoked outbox event');
$secondApply = $reconciler->run('apply', ['license']);
ok(($secondApply['summary']['repairs_applied'] ?? 0) === 0 && ($secondApply['summary']['converged'] ?? false) === true, 'repeated apply converges with zero new repairs');
$missedRefusal = $refresh->refresh($refreshRequest($M, 'node-missed-0001', $mJourney['credential'], 'refresh-m0001', 12));
$expectRefusal($missedRefusal, 'REVOKED', 'after the missed callback is repaired, stale access cannot refresh (signed REVOKED refusal)');
$mLicenseStatus = $db->query("SELECT status FROM wp_edd_licenses WHERE id = 7008")->fetchColumn();
ok($mLicenseStatus === 'revoked', 'canonical EDD revoke truth is preserved untouched by the reconciler');
ok((int) $db->query("SELECT highest_entitlement_sequence FROM wp_wpuiai_authority_accounts WHERE account_uuid = '{$M}'")->fetchColumn() === 12, 'missed-callback repair advances the authority sequence strictly monotonically (12)');
okThrows(static fn() => $reconciler->run('invented_mode'), 'RECONCILIATION_MODE_UNKNOWN', 'unknown reconciliation mode fails closed');
okThrows(static fn() => $reconciler->run('apply', ['invented_surface']), 'RECONCILIATION_SCOPE_UNKNOWN', 'unknown reconciliation scope fails closed');
okThrows(static fn() => $reconciler->run('apply', ['price' => 9.99]), 'CLIENT_COMMERCIAL_FIELDS_FORBIDDEN', 'client-controlled commerce fields in reconciliation scope are forbidden');

// ── 6. Authority outage: no new local license; existing signed offline policy only ──

$oJourney = $issuePaidJourney($O, 2008, 9009, 7009, 'node-outage-0001', $deviceKey('node-outage-0001'), 'o0001');
ok((int) $oJourney['lease']['sequence'] === 12, 'outage-account lease issued at sequence 12');
$leasesBefore = $counts('wp_wpuiai_authority_leases');
// Adverse authority truth: the canonical EDD license row is unusable (the authority
// is still reachable, so the refusal itself is durably journaled).
$db->exec("UPDATE wp_edd_licenses SET status = 'inactive' WHERE id = 7009");
$outageRefusal = $refresh->refresh($refreshRequest($O, 'node-outage-0001', $oJourney['credential'], 'refresh-o0001', 12));
$expectRefusal($outageRefusal, 'EDD_LICENSE_UNUSABLE', 'adverse EDD truth denies refresh with a signed recovery-only refusal');
ok((int) $db->query("SELECT COUNT(*) FROM wp_wpuiai_authority_outbox WHERE account_uuid = '{$O}' AND event_type = 'lease_superseded'")->fetchColumn() === 1, 'the outage refusal journals a durable lease_superseded outbox event');
// Hard outage: canonical EDD truth is no longer reachable at all.
$db->exec("DELETE FROM wp_edd_licenses WHERE id = 7009");
// No outage or rollback creates a new local license.
okThrows(
    static fn() => $issuer->issueLease([
        'account_uuid' => $O, 'product_code' => $PAID, 'node_id' => 'node-outage-0001',
        'device_public_key' => $deviceKey('node-outage-0001'), 'idempotency_key' => 'lease-o-outage-0001',
        'request_id' => 'req-lease-o-outage-0001',
    ]),
    'EDD_LICENSE_UNUSABLE',
    'a new lease cannot be issued while EDD truth is unreachable',
);
ok($counts('wp_wpuiai_authority_leases') === $leasesBefore, 'no new local license is created during the outage');
// Existing signed offline policy only: the stored lease stays the sole authority.
$offlineActive = $issuer->verifyEnvelope($oJourney['lease']['envelope'], [
    'expected_product' => 'focusa', 'expected_node_id' => 'node-outage-0001', 'now' => '2026-10-01T00:00:00Z',
]);
ok(($offlineActive['state'] ?? '') === 'active', 'offline policy: inside expiry the existing signed lease remains active');
$offlineGrace = $issuer->verifyEnvelope($oJourney['lease']['envelope'], [
    'expected_product' => 'focusa', 'expected_node_id' => 'node-outage-0001', 'now' => '2026-11-20T00:00:00Z',
]);
ok(($offlineGrace['state'] ?? '') === 'offline_grace', 'offline policy: past expiry inside grace the signed lease degrades to offline_grace (never a new license)');
okThrows(
    static fn() => $issuer->verifyEnvelope($oJourney['lease']['envelope'], [
        'expected_product' => 'focusa', 'expected_node_id' => 'node-outage-0001', 'now' => '2027-01-01T00:00:00Z',
    ]),
    'EXPIRED',
    'offline policy: past grace the signed lease expires and grants nothing',
);
// Recovery remains available: the signed outage refusal still verifies.
$outageVerified = $refresh->verifyRefusal($outageRefusal['refusal'], ['now' => (string) $outageRefusal['created_at']]);
ok(($outageVerified['posture'] ?? '') === 'recovery_only' && ($outageVerified['reason_code'] ?? '') === 'EDD_LICENSE_UNUSABLE', 'during the outage the signed refusal still verifies (recovery remains available)');

// ── 7. Refresh-credential negatives ──

$qJourney = $issuePaidJourney($Q, 2009, 9010, 7010, 'node-credless-0001', $deviceKey('node-credless-0001'), 'q0001', '2026-08-08T20:00:00Z', false);
okThrows(
    static fn() => $refresh->refresh($refreshRequest($Q, 'node-credless-0001', 'rc_unused_placeholder', 'refresh-q0001', 12)),
    'REFRESH_CREDENTIAL_REQUIRED',
    'refresh without an issued credential fails closed',
);
$q2Journey = $issuePaidJourney($Q2, 2010, 9011, 7011, 'node-wrongcred-0001', $deviceKey('node-wrongcred-0001'), 'q2-0001');
$wrongCred = $refresh->refresh($refreshRequest($Q2, 'node-wrongcred-0001', 'rc_wrong_credential_000000000000', 'refresh-q2-0001', 12));
$expectRefusal($wrongCred, 'REFRESH_CREDENTIAL_INVALID', 'a wrong refresh credential is denied with a signed recovery-only refusal');
ok(($issuer->findLease($q2Journey['lease']['lease_uuid'])['status'] ?? '') === 'active', 'credential refusal does not settle the lease (authentication-only denial)');
okThrows(
    static fn() => $refresh->refresh($refreshRequest($Q2, 'node-other-0001', $q2Journey['credential'], 'refresh-q2-0002', 12)),
    'LEASE_NOT_FOUND',
    'refresh for an unknown node fails closed',
);
okThrows(
    static fn() => $issuer->issueLease([
        'account_uuid' => $A, 'product_code' => $PAID, 'node_id' => '11111111-1111-4111-8111-111111111111',
        'device_public_key' => $DK1, 'features' => ['base_focusa' => true],
        'idempotency_key' => 'lease-grant-0001', 'request_id' => 'req-lease-grant-0001',
    ]),
    'CALLER_CONTROLLED_GRANT_DENIED',
    'caller-controlled grant fields on issuance fail closed',
);
okThrows(
    static fn() => $issuer->issueLease([
        'account_uuid' => $A, 'product_code' => 'invented_product', 'node_id' => '11111111-1111-4111-8111-111111111111',
        'device_public_key' => $DK1, 'idempotency_key' => 'lease-product-0001', 'request_id' => 'req-lease-product-0001',
    ]),
    'PRODUCT_MAPPING_REQUIRED',
    'an unknown product code can never resolve a grant',
);

// ── 8. Outbox: dispatch failure cannot lose state; delivery exactly once ──

$pendingBefore = (int) $db->query("SELECT COUNT(*) FROM wp_wpuiai_authority_outbox WHERE dispatch_state IN ('pending','failed')")->fetchColumn();
ok($pendingBefore === 26, 'exactly 26 signed outbox events are pending across all journeys');
$beforeOutbox = $counts('wp_wpuiai_authority_outbox');
$beforeLifecycle = $counts('wp_wpuiai_edd_lifecycle_events');
// A fresh tamper-probe event (appended after the pending snapshot, never legitimately delivered).
$db->beginTransaction();
try {
    $hook->appendFromEdd([
        'surface' => 'order', 'status' => 'completed', 'account_uuid' => $Q2, 'edd_customer_id' => 2010,
        'order_id' => 9011, 'license_id' => 7011,
        'request_id' => 'req-hook-tamper-0001', 'idempotency_key' => 'idem-hook-tamper-0001',
    ]);
    $db->commit();
} catch (Throwable $error) {
    if ($db->inTransaction()) { $db->rollBack(); }
    throw $error;
}
$tamperedUuid = (string) $db->query("SELECT event_uuid FROM wp_wpuiai_authority_outbox WHERE idempotency_key = 'idem-hook-tamper-0001' LIMIT 1")->fetchColumn();
$db->exec("UPDATE wp_wpuiai_authority_outbox SET payload = payload || 'tampered' WHERE event_uuid = '{$tamperedUuid}'");
$failSummary = $failDispatcher->dispatchReady();
ok($failSummary['dispatched'] === 0 && $failSummary['failed'] === $pendingBefore && $failSummary['tampered'] === 1, 'dispatch failure cannot lose canonical state (every event retries; the tampered probe dead-letters)');
ok($counts('wp_wpuiai_authority_outbox') === $beforeOutbox + 1 && $counts('wp_wpuiai_edd_lifecycle_events') === $beforeLifecycle, 'failed dispatch preserves every outbox and lifecycle row');
ok((int) $db->query("SELECT COUNT(*) FROM wp_wpuiai_outbox_deliveries")->fetchColumn() === 0, 'failed dispatch records no delivery');
$failedState = $db->query("SELECT dispatch_state, attempts FROM wp_wpuiai_authority_outbox WHERE event_type = 'refund_issued' LIMIT 1")->fetch(PDO::FETCH_ASSOC);
ok($failedState['dispatch_state'] === 'failed' && (int) $failedState['attempts'] === 1, 'failed events hold bounded retry state (failed, attempts 1)');
$tamperedRow = $db->query("SELECT dispatch_state, last_error FROM wp_wpuiai_authority_outbox WHERE event_uuid = '{$tamperedUuid}'")->fetch(PDO::FETCH_ASSOC);
ok($tamperedRow['dispatch_state'] === 'dead_letter' && $tamperedRow['last_error'] === 'OUTBOX_ENVELOPE_TAMPERED', 'tampered envelope dead-letters with the exact bounded error');
$tick(120); // past the exponential backoff
$goodSummary = $goodDispatcher->dispatchReady();
ok($goodSummary['dispatched'] === $pendingBefore && $goodSummary['failed'] === 0, 'retry dispatches every legitimate event exactly once');
ok($deliverCalls === $pendingBefore, 'consumer applied exactly the pending event set');
ok((int) $db->query("SELECT COUNT(*) FROM wp_wpuiai_outbox_deliveries")->fetchColumn() === $pendingBefore, 'delivery ledger records exactly-once deliveries');
$idleSummary = $goodDispatcher->dispatchReady();
ok($idleSummary['dispatched'] === 0 && $deliverCalls === $pendingBefore, 'a second dispatch pass duplicates nothing (exactly once)');
// A tampered envelope dead-letters and never delivers.
okThrows(
    static fn() => $goodDispatcher->replay($tamperedUuid),
    'OUTBOX_DISPATCH_FAILED',
    'a tampered envelope fails closed on replay',
);
$requeued = $goodDispatcher->retryDeadLetter([$tamperedUuid]);
ok($requeued === 1, 'dead-letter repair re-queues the bounded row');
$tamperSummary = $goodDispatcher->dispatchReady();
ok($tamperSummary['tampered'] === 1, 're-dispatched tampered envelope is again rejected');
ok($goodDispatcher->stateCount('dead_letter') === 1, 'repairState sees exactly one stable dead-letter row');
ok($goodDispatcher->stateCount('dispatched') === $pendingBefore, 'the twenty-six legitimate events remain dispatched exactly once');
$repairState = $goodDispatcher->repairState();
ok(($repairState['states']['dead_letter'] ?? 0) === 1, 'repairState() exposes the bounded dead-letter repair state');
ok($goodDispatcher->deliveryCount() === $pendingBefore, 'tampered envelope never produces a delivery');
okThrows(
    static fn() => $hook->append(['event_type' => 'order_completed', 'account_uuid' => $A, 'edd_customer_id' => 1001, 'order_id' => 9001, 'request_id' => 'req-no-tx-0001', 'idempotency_key' => 'idem-no-tx-0001']),
    'OUTBOX_APPEND_REQUIRES_TRANSACTION',
    'outbox append outside a transaction fails closed',
);
okThrows(
    static fn() => $hook->appendFromEdd(['surface' => 'order', 'status' => 'invented', 'account_uuid' => $A, 'edd_customer_id' => 1001, 'order_id' => 9001]),
    'EDD_STATUS_UNKNOWN',
    'an unmapped EDD status can never create an outbox event',
);

// ── 9. Lifecycle fail-closed negatives ──

okThrows(
    static fn() => $projector->projectOrder(['status' => 'mystery', 'account_uuid' => $A, 'edd_customer_id' => 1001, 'order_id' => 9001]),
    'EDD_STATUS_UNKNOWN',
    'an unmapped EDD status fails closed',
);
okThrows(
    static fn() => $projector->projectTransition(['surface' => 'order', 'transition' => 'invented', 'account_uuid' => $A, 'edd_customer_id' => 1001, 'order_id' => 9001, 'request_id' => 'req-invented-0001', 'idempotency_key' => 'idem-invented-0001']),
    'EDD_TRANSITION_UNKNOWN',
    'an invented transition fails closed',
);
okThrows(
    static fn() => $projector->projectOrder(['status' => 'completed', 'account_uuid' => $A, 'edd_customer_id' => 1001, 'order_id' => 9001, 'price' => '0.00', 'request_id' => 'req-price-0001', 'idempotency_key' => 'idem-price-0001']),
    'CLIENT_COMMERCIAL_FIELDS_FORBIDDEN',
    'client-controlled price on a lifecycle event fails closed',
);
okThrows(
    static fn() => $projector->projectOrder(['status' => 'completed', 'account_uuid' => $A, 'edd_customer_id' => 1001, 'order_id' => 9001, 'state_reason' => 'owner at x@example.invalid', 'request_id' => 'req-email-0001', 'idempotency_key' => 'idem-email-0001']),
    'INPUT_RAW_EMAIL_FORBIDDEN',
    'raw email on a lifecycle event fails closed',
);
okThrows(
    static fn() => $projector->projectOrder(['status' => 'completed', 'account_uuid' => $A, 'edd_customer_id' => 9999, 'order_id' => 9001, 'request_id' => 'req-customer-0001', 'idempotency_key' => 'idem-customer-0001']),
    'EDD_CUSTOMER_RESOLUTION_FAILED',
    'a mismatched EDD customer on a lifecycle event fails closed',
);
// A terminal transition against an account with no prior entitlement truth never invents truth.
$db->exec("INSERT INTO wp_wpuiai_authority_accounts (account_uuid, edd_customer_id, customer_id, wordpress_user_id, stripe_customer_id, status, status_reason, highest_entitlement_sequence, migration_provenance, created_at, updated_at)
    VALUES ('f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c', 2011, 2011, NULL, NULL, 'active', 'mailbox_verified', 0, '{}', '2026-08-01T00:00:00Z', '2026-08-01T00:00:00Z')");
$db->exec("INSERT INTO wp_edd_customers (id, customer_id, email, name, purchase_value, purchase_count, notes, date_created, stripe_customer_id)
    VALUES (2011, 2011, 'c2011@example.invalid', 'Fixture', '697.00', 1, '', '2026-08-01T00:00:00Z', NULL)");
$db->exec("INSERT INTO wp_edd_orders (id, order_id, customer_id, status, total, date_created, date_completed)
    VALUES (9012, 9012, 2011, 'refunded', '697.00', '2026-08-01T00:00:00Z', NULL)");
$db->exec("INSERT INTO wp_edd_licenses (id, license_id, customer_id, download_id, payment_id, license_key, status, activation_limit, expiration, date_created, order_id)
    VALUES (7012, 7012, 2011, 1001, 9012, 'LO-7012-0001-0001-0001', 'refunded', 3, NULL, '2026-08-01T00:00:00Z', 9012)");
$noTruth = $projector->projectRefund([
    'status' => 'refunded', 'account_uuid' => 'f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c', 'edd_customer_id' => 2011,
    'order_id' => 9012, 'license_id' => 7012,
    'request_id' => 'req-notruth-0001', 'idempotency_key' => 'idem-notruth-0001',
]);
ok($noTruth['decision'] === 'denied' && $noTruth['error_code'] === 'ENTITLEMENT_REQUIRED', 'a terminal event with no prior entitlement truth never invents truth');
okThrows(
    static fn() => $refresh->verifyRefusal(['schema' => 'focusa.signed_envelope.v1', 'signer_key_id' => 'authority-lease-2026-01', 'payload_b64' => 'AAAA', 'signature_b64' => 'AAAA'], ['now' => ($clock)()]),
    'INVALID_SIGNATURE',
    'a forged refusal envelope fails closed',
);

// ── 10. Preservation-only rollback ──

$baselineCounts = [
    'customers' => $counts('wp_edd_customers'),
    'orders' => $counts('wp_edd_orders'),
    'licenses' => $counts('wp_edd_licenses'),
    'lifecycle' => $counts('wp_wpuiai_edd_lifecycle_events'),
    'outbox' => $counts('wp_wpuiai_authority_outbox'),
    'leases' => $counts('wp_wpuiai_authority_leases'),
    'nodes' => $counts('wp_wpuiai_authority_nodes'),
    'credentials' => $counts('wp_wpuiai_lease_refresh_credentials'),
];
$lifecycleSchema->preserveForRollback('2026-08-09T00:00:00Z', ['source' => 'lifecycle_outage_e2e_rollback']);
$outboxSchema->preserveForRollback('2026-08-09T00:00:00Z', ['source' => 'lifecycle_outage_e2e_rollback']);
$reconciliationMigration->preserveForRollback('2026-08-09T00:00:00Z', ['source' => 'lifecycle_outage_e2e_rollback']);
$nodeMigration->preserveForRollback('2026-08-09T00:00:00Z', ['source' => 'lifecycle_outage_e2e_rollback']);
$refreshSchema->preserveForRollback('2026-08-09T00:00:00Z', ['source' => 'lifecycle_outage_e2e_rollback']);
$accountMigration->preserveForRollback('2026-08-09T00:00:00Z', ['source' => 'lifecycle_outage_e2e_rollback']);
ok($counts('wp_edd_customers') === $baselineCounts['customers'] && $counts('wp_edd_orders') === $baselineCounts['orders'], 'rollback preserves EDD customer and order truth');
ok($counts('wp_edd_licenses') === $baselineCounts['licenses'], 'rollback preserves license truth (including the refunded/revoked/expired rows)');
ok($counts('wp_wpuiai_edd_lifecycle_events') === $baselineCounts['lifecycle'] && $counts('wp_wpuiai_authority_outbox') === $baselineCounts['outbox'], 'rollback preserves lifecycle and outbox journals');
ok($counts('wp_wpuiai_authority_leases') === $baselineCounts['leases'] && $counts('wp_wpuiai_authority_nodes') === $baselineCounts['nodes'], 'rollback preserves leases and node registries');
ok($counts('wp_wpuiai_lease_refresh_credentials') === $baselineCounts['credentials'], 'rollback preserves refresh credentials');
$refundTruth = $db->query("SELECT status FROM wp_edd_licenses WHERE id = 7002")->fetchColumn();
ok($refundTruth === 'refunded', 'rollback never rolls back EDD refund truth');
$refundProjection = $db->query("SELECT license_state FROM wp_wpuiai_edd_lifecycle_events WHERE account_uuid = '{$R}' AND decision IN ('applied','replayed') ORDER BY result_sequence DESC, created_at DESC LIMIT 1")->fetchColumn();
ok($refundProjection === 'refunded', 'rollback never rolls back the refund projection');
$revokeProjection = $db->query("SELECT license_state FROM wp_wpuiai_edd_lifecycle_events WHERE account_uuid = '{$M}' AND decision IN ('applied','replayed') ORDER BY result_sequence DESC, created_at DESC LIMIT 1")->fetchColumn();
ok($revokeProjection === 'revoked', 'rollback never rolls back the reconciled revoke projection');
$schemaEvents = $counts('wp_wpuiai_edd_lifecycle_schema_events');
ok($schemaEvents >= 1, 'rollback preservation is durably journaled on the lifecycle schema');
ok($counts('wp_wpuiai_authority_lease_schema_migrations') === 1, 'lease schema migration journal is preserved');
ok($counts('wp_wpuiai_authority_outbox_schema_events') >= 1 && $counts('wp_wpuiai_reconciliation_schema_events') >= 1 && $counts('wp_wpuiai_lease_refresh_schema_events') >= 1 && $counts('wp_wpuiai_authority_node_schema_events') >= 1, 'every authority surface journals preservation-only rollback');

// ── 11. Redaction: no email, no secrets, no key material in stored state ──

$allStoredJson = '';
foreach ([
    'wp_wpuiai_edd_lifecycle_events', 'wp_wpuiai_authority_outbox', 'wp_wpuiai_outbox_deliveries',
    'wp_wpuiai_authority_leases', 'wp_wpuiai_lease_refresh_log', 'wp_wpuiai_lease_refresh_credentials',
    'wp_wpuiai_authority_node_reservations', 'wp_wpuiai_reconciliation_runs',
] as $table) {
    $allStoredJson .= json_encode($db->query("SELECT * FROM {$table}")->fetchAll(PDO::FETCH_ASSOC), JSON_THROW_ON_ERROR);
}
ok(strpos($allStoredJson, '@') === false, 'no raw email in any lifecycle/outbox/lease/reconciliation storage');
ok(strpos($allStoredJson, 'cus_') === false && strpos($allStoredJson, 'sk_live') === false && strpos($allStoredJson, 'sk_test') === false, 'no payment or signing secret in storage');
ok(strpos($allStoredJson, 'FOCUSA-') === false, 'no EDD key material in storage');
ok(strpos($allStoredJson, 'rc_') === false, 'no plaintext refresh credential in storage (hash-at-rest)');

// ── Summary (deterministic; no uuids, tokens, or random values) ──

$lifecycleTotal = $counts('wp_wpuiai_edd_lifecycle_events');
$outboxTotal = $counts('wp_wpuiai_authority_outbox');
$leasesTotal = $counts('wp_wpuiai_authority_leases');
$summary = [
    'schema' => 'focusa.spec152e.lifecycle_outage_e2e.v1',
    'positive_checks' => $positive,
    'negative_checks' => $negative,
    'node_limit_three_registered' => true,
    'node_limit_exhausted' => true,
    'node_slot_released_on_deactivate' => true,
    'explicit_reservation_reused_slot' => true,
    'lease_issued_sequence' => 12,
    'lease_rotation_sequence' => 13,
    'rotation_outbox_events' => true,
    'refund_projected_recovery_only' => true,
    'chargeback_projected_recovery_only' => true,
    'revoke_projected_recovery_only' => true,
    'expiry_projected_recovery_only' => true,
    'subscription_cancel_projected_recovery_only' => true,
    'terminal_reactivation_denied' => true,
    'sequence_rollback_denied' => true,
    'lifecycle_replay_no_bump' => true,
    'refund_refresh_denied_recovery_only' => true,
    'chargeback_refresh_denied_recovery_only' => true,
    'revoke_refresh_denied_recovery_only' => true,
    'expiry_refresh_denied_recovery_only' => true,
    'cancel_refresh_denied_recovery_only' => true,
    'stale_sequence_refresh_denied' => true,
    'stale_envelope_rejected' => true,
    'revoke_durable_audit' => true,
    'missed_callback_repaired' => true,
    'missed_callback_converged' => true,
    'missed_callback_refresh_denied' => true,
    'outbox_pending_events' => $pendingBefore,
    'outbox_failed_dispatch_state_preserved' => true,
    'outbox_exactly_once_delivery' => true,
    'outbox_tampered_dead_letter' => true,
    'outage_no_new_lease' => true,
    'outage_refresh_denied_recovery_only' => true,
    'offline_policy_active' => true,
    'offline_policy_grace' => true,
    'offline_policy_expired' => true,
    'recovery_refusal_verifiable' => true,
    'rollback_preservation_intact' => true,
    'canonical_refund_truth_preserved' => true,
    'lifecycle_events_total' => $lifecycleTotal,
    'lifecycle_replay_journals_no_row' => true,
    'outbox_events_total' => $outboxTotal,
    'leases_total' => $leasesTotal,
    'sequence_refund_account' => 12,
    'sequence_missed_callback_account' => 12,
    'result' => 'passed_fail_closed',
];
fwrite(STDOUT, json_encode($summary, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES) . "\n");
"""


def run_harness(root: Path, php: str) -> tuple[int, str, str]:
    import tempfile
    with tempfile.NamedTemporaryFile("w", suffix=".php", delete=False, encoding="utf-8") as handle:
        handle.write(HARNESS)
        harness_path = handle.name
    try:
        proc = subprocess.run(
            [php, harness_path, str(root)],
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=300,
        )
    finally:
        Path(harness_path).unlink(missing_ok=True)
    if proc.returncode != 0:
        raise AssertionError(f"harness failed rc={proc.returncode}\n{proc.stderr}")
    return proc.returncode, proc.stdout, proc.stderr


def main() -> int:
    global positive, negative
    if PHP is None:
        raise AssertionError("php runtime is required")

    # ── Dynamic journey proof (php harness, run twice for replay identity) ──
    rc1, out1, _ = run_harness(ROOT, PHP)
    rc2, out2, _ = run_harness(ROOT, PHP)
    expect(rc1 == 0 and rc2 == 0, "php harness exits 0 on both runs")
    expect(out1 == out2, "harness output is byte-identical across runs (replayable)")
    result = json.loads(out1)
    expect(result["schema"] == "focusa.spec152e.lifecycle_outage_e2e.v1", "harness summary schema pinned")
    expect(result["result"] == "passed_fail_closed", "harness result passed fail-closed")
    expect(result["node_limit_three_registered"] is True and result["node_limit_exhausted"] is True,
           "concurrent node limit proven: three register, the fourth is denied")
    expect(result["node_slot_released_on_deactivate"] is True and result["explicit_reservation_reused_slot"] is True,
           "explicit node management proven: deactivation releases the slot, reserve/settle reuses it")
    expect(result["lease_issued_sequence"] == 12 and result["lease_rotation_sequence"] == 13,
           "signed lease issuance and refresh rotation are strictly monotonic (12 -> 13)")
    expect(result["rotation_outbox_events"] is True, "rotation journals lease_superseded + lease_issued outbox events")
    for key in ["refund_projected_recovery_only", "chargeback_projected_recovery_only",
                "revoke_projected_recovery_only", "expiry_projected_recovery_only",
                "subscription_cancel_projected_recovery_only"]:
        expect(result[key] is True, f"terminal lifecycle projection proven: {key}")
    expect(result["terminal_reactivation_denied"] is True, "terminal states can never reactivate")
    expect(result["sequence_rollback_denied"] is True, "out-of-order authority ordinals can never roll back the sequence")
    expect(result["lifecycle_replay_no_bump"] is True, "duplicate redeliveries journal as replayed without a bump")
    for key in ["refund_refresh_denied_recovery_only", "chargeback_refresh_denied_recovery_only",
                "revoke_refresh_denied_recovery_only", "expiry_refresh_denied_recovery_only",
                "cancel_refresh_denied_recovery_only"]:
        expect(result[key] is True, f"signed recovery-only refresh denial proven: {key}")
    expect(result["stale_sequence_refresh_denied"] is True and result["stale_envelope_rejected"] is True,
           "stale sequence/software cannot refresh or verify")
    expect(result["revoke_durable_audit"] is True, "revocation carries a durable audit trail")
    expect(result["missed_callback_repaired"] is True and result["missed_callback_converged"] is True,
           "missed callback repaired by the reconciler; runs converge")
    expect(result["missed_callback_refresh_denied"] is True, "stale access cannot persist after a missed callback is repaired")
    expect(result["outbox_pending_events"] == 26, "exactly 26 signed outbox events across all journeys")
    expect(result["outbox_failed_dispatch_state_preserved"] is True, "dispatch failure cannot lose canonical state")
    expect(result["outbox_exactly_once_delivery"] is True, "outbox delivery is exactly once")
    expect(result["outbox_tampered_dead_letter"] is True, "tampered envelopes dead-letter and never deliver")
    expect(result["outage_no_new_lease"] is True and result["outage_refresh_denied_recovery_only"] is True,
           "authority outage creates no new local license and denies refresh with recovery-only")
    expect(result["offline_policy_active"] is True and result["offline_policy_grace"] is True
           and result["offline_policy_expired"] is True,
           "existing signed offline policy only: active -> offline_grace -> expired")
    expect(result["recovery_refusal_verifiable"] is True, "recovery remains available (signed refusals verify during outage)")
    expect(result["rollback_preservation_intact"] is True and result["canonical_refund_truth_preserved"] is True,
           "rollback is preservation-only and never rolls back refund truth")
    expect(result["lifecycle_events_total"] == 22, "lifecycle journal holds exactly 22 bounded events (idempotent replays journal no new row)")
    expect(result["outbox_events_total"] == 27, "outbox holds 26 journey events plus the tamper-probe event")
    expect(result["leases_total"] == 12, "lease registry holds exactly 12 bounded rows")
    expect(result["sequence_refund_account"] == 12 and result["sequence_missed_callback_account"] == 12,
           "refund and missed-callback accounts advanced strictly monotonically to sequence 12")
    harness_positive = int(result["positive_checks"])
    harness_negative = int(result["negative_checks"])
    expect(harness_positive >= 70, "harness positive check count is bounded and non-trivial")
    expect(harness_negative >= 15, "harness negative check count is bounded and non-trivial")

    # ── Static binding: recovery-only surface contract (spec 152E §18/§20) ──
    RECOVERY = json.loads((CONTRACTS / "spec152e-recovery-only-surface.v1.json").read_text(encoding="utf-8"))
    expect(RECOVERY["schema"] == "focusa.spec152e.recovery_only_surface.v1", "recovery-only surface schema pinned")
    expect(RECOVERY["invariants"]["recovery_never_grants_entitlement"] is True
           and RECOVERY["invariants"]["no_local_or_self_issued_entitlement"] is True,
           "recovery surface never grants entitlement and never self-issues")
    denial_by_code = {}
    for binding in RECOVERY["denial_bindings"]:
        for code in binding["codes"]:
            denial_by_code[code] = binding
    for code in ["REFUNDED", "REVOKED"]:
        expect(denial_by_code[code]["class"] == "license"
               and denial_by_code[code]["recovery_action"] == "authenticated_recovery"
               and denial_by_code[code]["posture"] == "recovery_only",
               f"recovery binding for {code} is authenticated_recovery / recovery_only")
    expect(denial_by_code["NODE_LIMIT_EXHAUSTED"]["recovery_action"] == "manage_nodes"
           and denial_by_code["NODE_LIMIT_EXHAUSTED"]["safe_next_actions"] == ["manage_nodes"],
           "node-limit denial offers explicit node management")
    expect(denial_by_code["AUTHORITY_UNAVAILABLE"]["class"] == "lease"
           and denial_by_code["AUTHORITY_UNAVAILABLE"]["recovery_action"] == "refresh_or_reactivate_lease",
           "authority outage maps to the lease recovery surface")
    expect(len(RECOVERY["forbidden_protected_mutations"]) >= 10
           and "/v1/evidence/capture" in RECOVERY["forbidden_protected_mutations"],
           "protected mutations are forbidden during recovery (no side effects)")
    recovery_actions = {surface["action"] for surface in RECOVERY["recovery_surfaces"]}
    expect({"verify_email", "manage_license", "export_customer_data", "run_diagnostics",
            "repair_rollback", "stable_security_update", "uninstall_preserving_user_data"} <= recovery_actions,
           "recovery preserves account verification, license status, export, diagnostics, repair, update, and uninstall")
    expect({"health", "version", "license_status", "export", "diagnostics", "repair",
            "update_for_recovery", "uninstall", "safe_read"} <= set(RECOVERY["consistency"]["envelope_allowed"]),
           "recovery envelope allows only safe read/recovery surfaces")

    # ── Static binding: signed refusal posture maps (spec 152E §18) ──
    REFRESH_PHP = (CONTRACTS / "spec152e-lease-refresh-service.v1.php").read_text(encoding="utf-8")
    REFUSAL_POSTURES = {
        "REFUNDED": "recovery_only", "REVOKED": "recovery_only", "EXPIRED": "recovery_only",
        "STALE_SEQUENCE": "recovery_only", "SUSPENDED": "denied", "CANCELLED": "recovery_only",
        "SUPERSEDED": "recovery_only", "NODE_NOT_FOUND": "recovery_only", "NODE_NOT_ACTIVE": "recovery_only",
        "EDD_LICENSE_UNUSABLE": "recovery_only", "REFRESH_CREDENTIAL_INVALID": "recovery_only",
    }
    for reason, posture in REFUSAL_POSTURES.items():
        expect(f"'{reason}' => '{posture}'" in REFRESH_PHP,
               f"lease-refresh REFUSAL_POSTURES pins {reason} -> {posture}")
    expect("'REVOKED' => 'lease_revoked'" in REFRESH_PHP, "revocation journals a durable lease_revoked outbox event")
    expect("'REFUNDED' => ['refunded', 'edd_refunded']" in REFRESH_PHP, "refund refusal settles refunded/edd_refunded")
    expect("'REVOKED' => ['revoked', 'edd_revoked']" in REFRESH_PHP, "revoke refusal settles revoked/edd_revoked")
    expect("'STALE_SEQUENCE' => ['superseded', 'stale_sequence']" in REFRESH_PHP, "stale sequence settles superseded/stale_sequence")

    # ── Static binding: EDD lifecycle projector (spec 152E §17) ──
    LIFECYCLE_PHP = (CONTRACTS / "spec152e-edd-lifecycle-projection.v1.php").read_text(encoding="utf-8")
    expect("'refunded', 'revoked', 'expired', 'superseded', 'cancelled', 'denied'" in LIFECYCLE_PHP,
           "lifecycle projector TERMINAL_STATES are exactly the six terminal states")
    for transition in ["refund", "chargeback", "revoke", "expire", "cancel"]:
        expect(f"'{transition}' => ['license_state' =>" in LIFECYCLE_PHP
               and "'refresh_posture' => 'recovery_only'" in LIFECYCLE_PHP,
               f"lifecycle projector maps {transition} to recovery_only")
    expect("'suspend' => ['license_state' => 'suspended', 'refresh_posture' => 'denied'" in LIFECYCLE_PHP,
           "suspend maps to denied refresh posture")
    expect("LICENSE_TERMINAL_REACTIVATION_DENIED" in LIFECYCLE_PHP, "terminal reactivation fails closed")
    expect("ENTITLEMENT_SEQUENCE_ROLLBACK_DENIED" in LIFECYCLE_PHP, "sequence rollback fails closed")

    # ── Static binding: outbox/reconciler (spec 152E §7.6) ──
    OUTBOX_PHP = (CONTRACTS / "spec152e-authority-outbox.v1.php").read_text(encoding="utf-8")
    expect("'pending', 'dispatched', 'failed', 'dead_letter'" in OUTBOX_PHP, "outbox dispatch states are bounded")
    for event_type in ["refund_issued", "chargeback_recorded", "license_revoked", "license_expired",
                       "subscription_cancelled", "lease_revoked", "lease_superseded"]:
        expect(f"'{event_type}'" in OUTBOX_PHP, f"outbox event registry pins {event_type}")
    RECONCILIATION_PHP = (CONTRACTS / "spec152e-authority-reconciliation.v1.php").read_text(encoding="utf-8")
    expect("'dry_run', 'apply'" in RECONCILIATION_PHP, "reconciler modes are dry_run/apply")
    expect("'project_lifecycle', 'append_outbox_event'" in RECONCILIATION_PHP, "reconciler repairs are projection + outbox append")
    expect("LICENSE_TERMINAL_REACTIVATION_DENIED" in RECONCILIATION_PHP, "reconciler never reactivates terminal truth")

    # ── Static binding: spec 152E §23 acceptance matrix rows exist ──
    spec_text = SPEC.read_text(encoding="utf-8")
    for row in ["| Node limit |", "| Refund |", "| Revocation |", "| Authority outage |"]:
        expect(row in spec_text, f"spec 152E acceptance matrix pins the '{row.strip(' |')}' row")

    # ── Hygiene: no raw email, secret, or raw-key evidence in artifacts ──
    EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
    SECRET_RE = re.compile(r"(?i)(?:sk|rk|pk)_(?:live|test)_[A-Za-z0-9]+")
    PRIVATE_KEY_RE = re.compile(r"BEGIN (?:RSA |EC |)PRIVATE KEY")
    GITHUB_TOKEN_RE = re.compile(r"ghp_[A-Za-z0-9]{8,}")
    LICENSE_SHAPE_RE = re.compile(r"FOCUSA-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}")
    expect(EMAIL_RE.search(out1) is None, "harness output carries no email literal")
    expect(SECRET_RE.search(out1) is None and PRIVATE_KEY_RE.search(out1) is None
           and GITHUB_TOKEN_RE.search(out1) is None and LICENSE_SHAPE_RE.search(out1) is None,
           "harness output carries no secret or raw-key evidence")
    for match in EMAIL_RE.findall(Path(__file__).read_text(encoding="utf-8")):
        expect(match.endswith("@example.invalid"), f"gate uses only synthetic reserved-domain email ({match})")

    # ── Bounded immutable result handle (SHA-256 of the exact harness output) ──
    result_handle = sha256_text(out1.strip())

    summary = {
        "schema": "focusa.spec152e.lifecycle_outage_e2e_validation.v1",
        "atom": "focusa-vbcqu.20.13.61",
        "harness_sha256": sha256_text(HARNESS),
        "harness_output_sha256": result_handle,
        "harness_positive_checks": harness_positive,
        "harness_negative_checks": harness_negative,
        "static_positive_checks": positive,
        "static_negative_checks": negative,
        "node_limit": {"three_registered": True, "exhausted": True, "slot_released": True},
        "lifecycle": {
            "refund": True, "chargeback": True, "revoke": True, "expiry": True,
            "subscription_cancel": True, "reactivation_denied": True, "rollback_denied": True,
        },
        "refresh": {
            "rotation_sequence": result["lease_rotation_sequence"],
            "refund_denied": True, "revoke_denied": True, "expiry_denied": True,
            "cancel_denied": True, "stale_sequence_denied": True,
        },
        "missed_callback": {"repaired": True, "converged": True, "refresh_denied": True},
        "outbox": {
            "pending": result["outbox_pending_events"],
            "exactly_once": True, "tampered_dead_letter": True, "state_preserved": True,
        },
        "outage": {"no_new_lease": True, "refresh_denied_recovery_only": True,
                   "offline_policy": {"active": True, "grace": True, "expired": True}},
        "recovery": {"refusals_verifiable": True, "surface_contract": "focusa.spec152e.recovery_only_surface.v1"},
        "rollback_preservation_only": True,
        "lifecycle_events_total": result["lifecycle_events_total"],
        "outbox_events_total": result["outbox_events_total"],
        "leases_total": result["leases_total"],
        "result_handle": result_handle,
        "harness_replay_identical": True,
        "result": "passed",
    }
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
