import { createFocusaSpec135Client, type components } from "@focusa/spec135-client";
import bindings from "../../../docs/contracts/spec135/generated-contract-v1/ui-action-bindings.fixture.json" with { type: "json" };
import { FOCUSA_A2UI_CATALOG_ID, FocusaA2uiRenderer, type A2uiMessage } from "../src/index.js";

type Session = components["schemas"]["focusa_project_interview_session_mutation_result_v1"]["session"];
type Request = components["schemas"]["focusa_project_interview_session_mutation_request_v1"];
const scope={project_root:"/example/focusa",continuity_id:"focusa-cont-ri3-generated-ui",attachment_id:"attachment:ri3-interview"};
const actionId="focusa.interview.session.mutate";
if(!bindings.bindings.some(b=>b.action_id===actionId))throw new Error("Interview session binding unavailable");
const client=createFocusaSpec135Client({baseUrl:location.origin});
const mount=document.querySelector<HTMLElement>("#interview-resume-surface")!;const status=document.querySelector<HTMLElement>("#resume-result")!;
let response:unknown,lastError:unknown;const observedActions:unknown[]=[];
async function list(id?:string){const r=await client.GET("/v1/interviews/sessions",{params:{query:{...scope,interview_session_id:id}}});if(!r.data)throw r.error;return r.data}
async function mutate(action:Request["action"],key:string,session?:Session,extra:Partial<Request>={}){const current=await list(session?.interview_session_id);const body={...scope,idempotency_key:key,expected_state_version:current.state_version,expected_session_revision:session?.state_revision??0,action,interview_session_id:session?.interview_session_id,...extra} as Request;const r=await client.POST("/v1/interviews/sessions/mutate",{params:{query:scope},body});if(!r.data)throw r.error;return r.data.session}
const renderer=new FocusaA2uiRenderer({allowedActionNames:new Set([actionId]),async onAction(action){observedActions.push(action);document.body.dataset.resumeStatus="running";status.textContent="Opening, branching, asking, closing, and resuming…";try{
 const [contexts,roles]=await Promise.all([client.GET("/v1/context/sources",{params:{query:scope}}),client.GET("/v1/roles/profiles",{params:{query:scope}})]);const source=contexts.data?.sources[0]?.source_id,role=roles.data?.approved?.role_profile_id;if(!source||!role)throw new Error("Seed canonical Context and approved Role first");
 let s=await mutate("open","ri3-ui-open",undefined,{approved_role_profile_ref:role});
 s=await mutate("upsert_branch","ri3-ui-scope",s,{branch:{decision_branch_id:"scope",tranche:"boundary",label:"Scope and non-goals"}});
 s=await mutate("upsert_branch","ri3-ui-risks",s,{branch:{decision_branch_id:"risks",tranche:"failure",label:"Known failure boundaries"}});
 s=await mutate("defer_branch","ri3-ui-defer",s,{decision_branch_id:"risks",deferred_reason:"Awaiting compliance owner"});
 s=await mutate("queue_question","ri3-ui-question",s,{question:{decision_branch_id:"scope",question:"Should Alpha 2 exclude operational permission grants?",reason_for_asking:"Operator owns this boundary.",triggering_gap:"Non-goal is not accepted.",recommendation:"Keep grants outside Alpha 2.",recommendation_basis_refs:[source],environment_facts_checked:[source],contradiction_refs:[],linked_context_refs:[source],linked_spec_sections:["135H §4"],decision_required:true,priority:"blocker",answer_type:"boolean",sensitivity:"consequential",readiness_effect:"Closes permission blocker.",stop_condition:"Operator accepts or rejects."}});
 const pointer=`${s.active_branch_id}/${s.current_question_id}`;s=await mutate("close","ri3-ui-close",s);s=await mutate("reopen","ri3-ui-reopen",s);if(`${s.active_branch_id}/${s.current_question_id}`!==pointer)throw new Error("Exact resume pointer changed");response=s;const deferred=s.branches.find(b=>b.decision_branch_id==="risks");
 renderer.processDelta([{version:"v0.9",updateComponents:{surfaceId:"ri3-interview-resume",components:[{id:"stage",component:"FocusaStageShell",label:"Interview resumed exactly",description:`Question ${s.current_question_id} in branch ${s.active_branch_id}`,status:"completed",details:`revision=${s.state_revision}; status=${s.status}`},{id:"branch",component:"FocusaContradictionCard",label:"Deferred branch remains governed",description:`${deferred?.label}: ${deferred?.status}`,status:"pending",details:deferred?.deferred_reason??""},{id:"evidence",component:"FocusaEvidenceSummary",label:"Durable resume proof",description:"Close/reopen preserved exact branch and question pointers.",status:"verified"}]}}]);status.textContent=`Completed at revision ${s.state_revision}: ${pointer}; deferred branch visible.`;document.body.dataset.resumeStatus="completed";
 }catch(e){lastError=e;status.textContent=`Recovery required: ${e instanceof Error?e.message:String(e)}`;document.body.dataset.resumeStatus="recovery"}}});
const snapshot:A2uiMessage[]=[{version:"v0.9",createSurface:{surfaceId:"ri3-interview-resume",catalogId:FOCUSA_A2UI_CATALOG_ID}},{version:"v0.9",updateComponents:{surfaceId:"ri3-interview-resume",components:[{id:"root",component:"Column",children:["stage","branch","evidence","run"]},{id:"stage",component:"FocusaStageShell",label:"Continue the Interview",description:"Durable questions and answers survive pause, close, and daemon restart.",status:"ready"},{id:"branch",component:"FocusaContradictionCard",label:"Branch governance",description:"Deferred work remains visible instead of disappearing.",status:"pending"},{id:"evidence",component:"FocusaEvidenceSummary",label:"Exact resume",description:"Branch and question pointers are preserved across close/reopen.",status:"pending"},{id:"run",component:"FocusaPrimaryAction",label:"Prove durable continuation",description:"Creates branches, defers one, asks one question, closes, and reopens.",primaryActionLabel:"Run Resume Proof",action:{event:{name:actionId,context:scope}}}]}}];renderer.processSnapshot(snapshot);renderer.mount(mount,"ri3-interview-resume");Object.assign(window,{focusaInterviewResumeEval:{renderer,scope,observedActions,get response(){return response},get lastError(){return lastError}}});
