import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const commands = readFileSync(resolve(root, "src/commands.ts"), "utf8");
const index = readFileSync(resolve(root, "src/index.ts"), "utf8");
const widget = readFileSync(resolve(root, "src/mission-canvas-widget.ts"), "utf8");
const config = readFileSync(resolve(root, "src/config.ts"), "utf8");
const view = readFileSync(resolve(root, "src/mission-canvas-view.ts"), "utf8");
const model = readFileSync(resolve(root, "src/mission-canvas-model.ts"), "utf8");
const turns = readFileSync(resolve(root, "src/turns.ts"), "utf8");
const inventory = readFileSync(resolve(root, "src/mission-canvas-session-inventory.ts"), "utf8");

assert.match(commands, /registerCommand\("mission-canvas"/);
assert.match(commands, /registerCommand\("mission-canvas-mode"/);
assert.match(commands, /registerCommand\("mission-canvas-profile"/);
assert.match(commands, /canvas-guided/);
assert.match(commands, /terminal-guided/);
assert.match(commands, /headless/);
assert.match(commands, /refreshMissionCanvasWidget\(ctx\)/);
assert.match(commands, /ctx\.ui\.custom/);
assert.match(commands, /Focusa Mission Canvas/);
assert.match(commands, /\/v1\/workpoint\/resume/);
assert.match(commands, /\/v1\/trajectory\/view/);
assert.match(commands, /MissionCanvasView/);
assert.match(commands, /\/v1\/session\/discover/);
assert.match(commands, /\/v1\/silent-sessions/);
assert.match(commands, /projectSessionInventory/);
assert.match(commands, /\/v1\/mission-canvas\/surfaces/);
assert.match(commands, /\/v1\/interviews\/sessions/);
assert.match(commands, /\/v1\/interviews\/closure-package/);
assert.match(commands, /\/v1\/workspace\/artifacts/);
assert.match(index, /registerMissionCanvasWidget\(pi\)/);
assert.match(widget, /setWidget\("focusa-mission-canvas-work-rail"/);
assert.match(commands, /workRailDetailRows/);
assert.match(widget, /placement: "aboveEditor"/);
assert.match(widget, /session_start/);
assert.match(widget, /turn_end/);
assert.match(widget, /session_shutdown/);
assert.match(widget, /stopRefreshLifecycle/);
assert.match(widget, /LifecycleGenerationGuard/);
assert.doesNotMatch(widget, /pollScopedSurfaceState\(ctx\)/);
assert.match(widget, /interactionMode\.mode !== "canvas-guided"/);
assert.match(config, /interactionMode: FocusaInteractionMode/);
assert.match(config, /FOCUSA_PI_INTERACTION_MODE/);
assert.match(config, /missionCanvasWorkspaceProfile/);
assert.match(config, /missionCanvasVisualVariant/);
assert.match(config, /source: "session-env" \| "project" \| "user" \| "default"/);
assert.match(config, /bounded session env > project override > user default > defaults/);
assert.match(view, /class MissionCanvasView implements Component/);
assert.match(view, /Key\.left/);
assert.match(view, /Key\.right/);
assert.match(view, /Key\.alt\("left"\)/);
assert.match(view, /Key\.alt\("right"\)/);
assert.match(view, /setInterval\(\(\) => void this\.refresh\(\), 5_000\)/);
assert.match(view, /clearInterval\(this\.refreshTimer\)/);
assert.match(view, /key === "r"/);
assert.match(view, /key === "y"/);
assert.match(commands, /setEditorText\(reference\)/);
assert.match(view, /WORK SURFACES/);
assert.match(view, /"Now"/);
assert.match(view, /"Work"/);
assert.match(view, /"Sessions"/);
assert.match(view, /"Contention"/);
assert.match(view, /"Proof"/);
assert.match(view, /"Research"/);
assert.match(view, /"History"/);
assert.match(view, /"Context"/);
assert.match(view, /"Role"/);
assert.match(view, /"Interview"/);
assert.match(view, /"Spec"/);
assert.match(view, /"Controls"/);
assert.match(model, /interface WorkSurfaceProjection/);
assert.match(model, /workSurfaceDetail/);
assert.match(view, /FOCUSED WORK SURFACE/);
assert.match(model, /browserIsolationClass/);
assert.match(model, /writerLeaseRef/);
assert.match(model, /pendingApprovalCount/);
assert.match(model, /conflictCount/);
assert.match(inventory, /interface MissionCanvasSessionInventoryRow/);
assert.match(inventory, /browserIsolation/);
assert.match(inventory, /writerLease/);
assert.match(inventory, /pendingApprovalCount/);
assert.match(turns, /## Focusa Interaction Mode/);
assert.match(turns, /Do not prompt to open or enable Mission Canvas/);
assert.match(turns, /Operate noninteractively through canonical APIs/);

console.log("Mission Canvas Pi surface registration passed");
