/usr/local/bin/focusa-tui --no-intro
[[1m[31mroot[0m[39m[49m][[1m[33mhost[0m[39m[49m][1m[36m~[0m[39m[49m [[1m[35m master[0m[39m[49m][1m[31m[!][0m[39m[49m
[[1;2m[31m⬢ [OpenVZ][0m[39m[49m][1m[32m❯[0m[39m[49m /usr/local/bin/focusa-tui --no-intro
?^[/[1;3m#[0m[39m[49m
[[1m[31mroot[0m[39m[49m][[1m[33mhost[0m[39m[49m][1m[36m~[0m[39m[49m [[1m[35m master[0m[39m[49m][1m[31m[!][0m[39m[49m[[1m[33m⏱ 2s[0m[39m[49m]
[[1;2m[31m⬢ [OpenVZ][0m[39m[49m][1m[32m❯[0m[39m[49m /
[[1m[31mroot[0m[39m[49m][[1m[33mhost[0m[39m[49m][1m[36m/[0m[39m[49m
[[1;2m[31m⬢ [OpenVZ][0m[39m[49m][1m[32m❯[0m[39m[49m /23456789


































