//! Spec 172 §14 — lifetime entitlement is separate from bounded device
//! credentials (atom focusa-vbcqu.20.15.22, 172.03.05).
//!
//! The focusa-license authority verifier/store/refresh lifecycle state machine
//! (`lifetime_entitlement`) decides from two SEPARATE records: the perpetual
//! License Type entitlement and the bounded signed device lease. These tests
//! prove the acceptance criterion: lifetime survives credential rotation and
//! outage recovery, while refund/revoke/higher sequence defeats stale and
//! offline credentials. The fixture (`spec172-lifetime-credential-vectors
//! .v1.json`) is generated by the WPUIAI PHP issuer and independently
//! signature-verified here with ed25519-dalek over the same canonical bytes.

use std::{collections::BTreeMap, fs, path::PathBuf};

use chrono::{DateTime, Duration, Utc};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use focusa_license::{
    DeviceCredentialStatus, DeviceCredentialWindow, LifetimeCredentialMachine,
    LifetimeCredentialState, LifetimeEntitlement, LifetimeEntitlementStatus, OFFLINE_GRACE_DAYS,
    PersistedLifetimeState, REFRESH_WINDOW_DAYS,
};
use serde_json::Value;

fn at(value: &str) -> DateTime<Utc> {
    value.parse().expect("fixture timestamp")
}

fn entitled(sequence: u64, updated_at: &str) -> LifetimeEntitlement {
    LifetimeEntitlement::new(
        "focusa",
        "focusa_operator_lifetime_v1",
        sequence,
        "v1.0.0",
        "sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
        3,
        1,
        at(updated_at),
    )
    .expect("canonical lifetime entitlement")
}

fn credential(
    sequence: u64,
    issued_at: &str,
    status: DeviceCredentialStatus,
) -> DeviceCredentialWindow {
    let issued = at(issued_at);
    let expires_at = issued + Duration::days(REFRESH_WINDOW_DAYS as i64);
    let offline_grace_until = expires_at + Duration::days(OFFLINE_GRACE_DAYS as i64);
    DeviceCredentialWindow {
        schema: focusa_license::DEVICE_CREDENTIAL_SCHEMA.to_string(),
        lease_id: LifetimeCredentialMachine::lease_id("focusa", "node-operator-lt-001", sequence),
        product: "focusa".to_string(),
        node_id: "node-operator-lt-001".to_string(),
        sequence,
        issued_at: issued,
        expires_at,
        offline_grace_until,
        authority_key_id: "authority-lease-2026-01".to_string(),
        status,
    }
}

fn vectors_fixture() -> Value {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "../../docs/contracts/spec172-lifetime-credential-vectors.v1.json",
    ]
    .iter()
    .collect();
    let payload =
        fs::read_to_string(path).expect("lifetime credential vectors fixture should exist");
    serde_json::from_str(&payload).expect("valid JSON fixture")
}

// ── machine semantics: lifetime survives credential rotation/outage ─────

#[test]
fn spec172_lifetime_credential_lifetime_survives_credential_rotation() {
    let entitlement = entitled(1, "2026-08-09T06:00:00Z");
    let initial = credential(1, "2026-08-09T06:00:00Z", DeviceCredentialStatus::Active);
    let now = at("2026-09-01T00:00:00Z");

    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&entitlement), Some(&initial), now),
        LifetimeCredentialState::Active
    );
    assert!(
        LifetimeCredentialMachine::resolve(Some(&entitlement), Some(&initial), now)
            .allows_product_use()
    );

    // Refresh/rotation issues a strictly higher sequence with a fresh bounded
    // window; the lifetime entitlement stays entitled.
    let rotated = LifetimeCredentialMachine::rotate_credential(
        &entitlement,
        &initial,
        at("2026-08-09T07:00:00Z"),
        REFRESH_WINDOW_DAYS,
        OFFLINE_GRACE_DAYS,
        "authority-lease-2026-01",
    )
    .expect("rotation allowed while entitled");
    assert_eq!(rotated.sequence, 2);
    assert!(rotated.sequence > initial.sequence);
    assert_eq!(rotated.expires_at - rotated.issued_at, Duration::days(90));
    assert_eq!(
        rotated.offline_grace_until - rotated.expires_at,
        Duration::days(30)
    );
    // The entitlement record itself is untouched by credential rotation.
    assert_eq!(entitlement.status, LifetimeEntitlementStatus::Entitled);
    assert_eq!(entitlement.term, "lifetime");
    // The rotated credential is usable under the same lifetime entitlement.
    let mut entitlement_advanced = entitlement.clone();
    entitlement_advanced.sequence = rotated.sequence;
    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&entitlement_advanced), Some(&rotated), now),
        LifetimeCredentialState::Active
    );
}

#[test]
fn spec172_lifetime_credential_credential_expiry_preserves_lifetime_and_recovery_reissues() {
    let entitlement = entitled(1, "2026-08-09T06:00:00Z");
    let credential = credential(1, "2026-08-09T06:00:00Z", DeviceCredentialStatus::Active);

    // Inside the bounded offline grace: offline_grace (never an expansion).
    let in_grace = at("2026-11-20T00:00:00Z");
    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&entitlement), Some(&credential), in_grace),
        LifetimeCredentialState::OfflineGrace
    );

    // Past the bounded grace: credential expired. The lifetime entitlement is
    // NOT destroyed — recovery_only keeps the right and opens recovery.
    let after_grace = at("2026-12-20T00:00:00Z");
    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&entitlement), Some(&credential), after_grace),
        LifetimeCredentialState::RecoveryOnly
    );
    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&entitlement), None, after_grace),
        LifetimeCredentialState::RecoveryOnly
    );
    assert!(
        !LifetimeCredentialMachine::resolve(Some(&entitlement), None, after_grace)
            .allows_product_use()
    );

    // Verified recovery issuance: a replacement bounded lease at a strictly
    // higher sequence, still lifetime-entitled.
    let recovered = LifetimeCredentialMachine::recover_credential(
        &entitlement,
        "node-operator-lt-001",
        at("2026-12-10T00:00:00Z"),
        REFRESH_WINDOW_DAYS,
        OFFLINE_GRACE_DAYS,
        "authority-lease-2026-01",
    )
    .expect("recovery issuance allowed while entitled");
    assert_eq!(recovered.sequence, 2);
    assert_eq!(
        LifetimeCredentialMachine::resolve(
            Some(&entitlement),
            Some(&recovered),
            at("2027-01-10T00:00:00Z"),
        ),
        LifetimeCredentialState::Active
    );
}

#[test]
fn spec172_lifetime_credential_refund_revoke_defeats_stale_and_offline_credentials() {
    let entitlement = entitled(1, "2026-08-09T06:00:00Z");
    let credential = credential(1, "2026-08-09T06:00:00Z", DeviceCredentialStatus::Active);

    // Refund/revoke at a strictly higher authority sequence revokes the
    // lifetime entitlement; stale or offline credentials can never override.
    let revoked =
        LifetimeCredentialMachine::revoke_entitlement(&entitlement, 5, at("2026-12-14T00:00:00Z"))
            .expect("higher authority sequence revokes");
    assert_eq!(revoked.status, LifetimeEntitlementStatus::Revoked);
    assert_eq!(revoked.sequence, 5);

    // Even though the device credential is still inside its signed window, the
    // revoked lifetime entitlement defeats it.
    assert_eq!(
        LifetimeCredentialMachine::resolve(
            Some(&revoked),
            Some(&credential),
            at("2026-09-01T00:00:00Z")
        ),
        LifetimeCredentialState::DeniedRevoked
    );
    // Offline credential (in grace) also defeated.
    assert_eq!(
        LifetimeCredentialMachine::resolve(
            Some(&revoked),
            Some(&credential),
            at("2026-11-20T00:00:00Z")
        ),
        LifetimeCredentialState::DeniedRevoked
    );
    // And no credential at all is still denied.
    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&revoked), None, at("2026-09-01T00:00:00Z")),
        LifetimeCredentialState::DeniedRevoked
    );
    // Recovery issuance is refused for a revoked entitlement.
    assert!(
        LifetimeCredentialMachine::recover_credential(
            &revoked,
            "node-operator-lt-001",
            at("2026-12-20T00:00:00Z"),
            REFRESH_WINDOW_DAYS,
            OFFLINE_GRACE_DAYS,
            "authority-lease-2026-01",
        )
        .is_err()
    );
}

#[test]
fn spec172_lifetime_credential_stale_credential_and_unknown_entitlement_fail_closed() {
    let entitlement_seq2 = entitled(2, "2026-08-09T07:00:00Z");
    let stale = credential(1, "2026-08-09T06:00:00Z", DeviceCredentialStatus::Active);
    let now = at("2026-09-01T00:00:00Z");
    // A replayed pre-rotation credential is never trusted even though its
    // window is still valid.
    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&entitlement_seq2), Some(&stale), now),
        LifetimeCredentialState::DeniedStale
    );
    // A revoked device credential (lost device) fails closed; stale-sequence
    // detection precedes status so a stale+revoked replay reports stale.
    let revoked_device = credential(2, "2026-08-09T07:00:00Z", DeviceCredentialStatus::Revoked);
    assert_eq!(
        LifetimeCredentialMachine::resolve(Some(&entitlement_seq2), Some(&revoked_device), now),
        LifetimeCredentialState::DeniedRevoked
    );
    // No lifetime entitlement record denies everything, even with a credential.
    assert_eq!(
        LifetimeCredentialMachine::resolve(None, Some(&stale), now),
        LifetimeCredentialState::DeniedUnknown
    );
    // Non-lifetime terms are rejected at record construction.
    assert!(
        LifetimeEntitlement::new(
            "focusa",
            "focusa_operator_lifetime_v1",
            1,
            "v1.0.0",
            "sha256:00",
            3,
            1,
            now,
        )
        .is_ok()
    );
    assert!(
        LifetimeEntitlement::new(
            "focusa",
            "uiai_operator_lifetime_v1",
            1,
            "v1.0.0",
            "sha256:00",
            3,
            1,
            now,
        )
        .is_err(),
        "cross-product License Type pairing must fail closed"
    );
    assert!(
        LifetimeEntitlement::new(
            "focusa",
            "focusa_operator_lifetime_v1",
            1,
            "v1.0.0",
            "sha256:00",
            0,
            1,
            now,
        )
        .is_err(),
        "zero node limit must fail closed"
    );
}

#[test]
fn spec172_lifetime_credential_key_rotation_never_widens_entitlement() {
    let entitlement = entitled(1, "2026-08-09T06:00:00Z");
    let credential = credential(1, "2026-08-09T06:00:00Z", DeviceCredentialStatus::Active);
    let rotated_key = LifetimeCredentialMachine::rotate_key(&credential, "authority-lease-2026-02")
        .expect("key rotation re-signs the bounded credential");
    assert_eq!(rotated_key.authority_key_id, "authority-lease-2026-02");
    assert_eq!(rotated_key.sequence, credential.sequence);
    assert_eq!(rotated_key.expires_at, credential.expires_at);
    // The lifetime entitlement is untouched: same sequence, same status, and
    // the rotated credential stays usable under it.
    assert_eq!(entitlement.sequence, 1);
    assert_eq!(entitlement.status, LifetimeEntitlementStatus::Entitled);
    assert_eq!(
        LifetimeCredentialMachine::resolve(
            Some(&entitlement),
            Some(&rotated_key),
            at("2026-09-01T00:00:00Z")
        ),
        LifetimeCredentialState::Active
    );
}

// ── store/refresh surface ───────────────────────────────────────────────

#[test]
fn spec172_lifetime_credential_persisted_state_transitions_are_fail_closed() {
    let now = at("2026-09-01T00:00:00Z");
    let mut state = PersistedLifetimeState::new(entitled(1, "2026-08-09T06:00:00Z"), now);
    assert_eq!(state.resolve(now), LifetimeCredentialState::RecoveryOnly);

    let issued = at("2026-08-09T07:00:00Z");
    state = state
        .recover_credential(
            "node-operator-lt-001",
            issued,
            REFRESH_WINDOW_DAYS,
            OFFLINE_GRACE_DAYS,
            "authority-lease-2026-01",
        )
        .expect("first credential issuance");
    assert_eq!(state.resolve(now), LifetimeCredentialState::Active);

    // Rotation advances the highest sequence; the old credential becomes stale.
    let rotated = state
        .rotate_credential(
            at("2026-08-09T08:00:00Z"),
            REFRESH_WINDOW_DAYS,
            OFFLINE_GRACE_DAYS,
            "authority-lease-2026-01",
        )
        .expect("refresh while entitled");
    assert_eq!(rotated.entitlement.sequence, 3);
    assert_eq!(rotated.resolve(now), LifetimeCredentialState::Active);
    assert_eq!(
        LifetimeCredentialMachine::resolve(
            Some(&rotated.entitlement),
            Some(
                &state
                    .device_credential
                    .clone()
                    .expect("old credential kept")
            ),
            now,
        ),
        LifetimeCredentialState::DeniedStale
    );

    // Refund/revoke at a higher sequence revokes the lifetime entitlement and
    // defeats the still-valid rotated credential.
    let revoked = rotated
        .apply_refund_or_revoke(5, at("2026-12-14T00:00:00Z"))
        .expect("refund at higher sequence");
    assert_eq!(
        revoked.entitlement.status,
        LifetimeEntitlementStatus::Revoked
    );
    assert_eq!(
        revoked.resolve(at("2026-09-01T00:00:00Z")),
        LifetimeCredentialState::DeniedRevoked
    );
    assert!(
        revoked
            .rotate_credential(
                at("2026-09-02T00:00:00Z"),
                REFRESH_WINDOW_DAYS,
                OFFLINE_GRACE_DAYS,
                "authority-lease-2026-01",
            )
            .is_err(),
        "refresh is refused once the lifetime entitlement is revoked"
    );
}

// ── cross-language vectors from the WPUIAI issuer ───────────────────────

#[test]
fn spec172_lifetime_credential_cross_language_vectors_verify_and_decide() {
    let fixture = vectors_fixture();
    assert_eq!(
        fixture["schema"],
        "focusa.spec172.lifetime_credential_vectors.v1"
    );
    assert_eq!(fixture["fixture_kind"], "public_synthetic_nonproduction");
    assert_eq!(fixture["term"], "lifetime");
    assert_eq!(fixture["refresh_window_days"], 90);
    assert_eq!(fixture["offline_grace_days"], 30);

    // Cross-language Ed25519: PHP signs, Rust verifies the same bytes.
    let public_key_hex = fixture["public_key_hex"].as_str().expect("public key hex");
    let mut key_bytes = [0u8; 32];
    hex_decode_into(public_key_hex, &mut key_bytes);
    let public_key = VerifyingKey::from_bytes(&key_bytes).expect("valid Ed25519 key");

    let mut credentials: BTreeMap<&str, &Value> = BTreeMap::new();
    for credential in fixture["credentials"].as_array().expect("credentials list") {
        let id = credential["id"].as_str().expect("credential id");
        let payload = &credential["payload"];
        let signature = credential["signature_hex"].as_str().expect("signature");
        let message = serde_json::to_vec(payload).expect("canonical payload bytes");
        let mut signature_bytes = [0u8; 64];
        hex_decode_into(signature, &mut signature_bytes);
        public_key
            .verify(
                &message,
                &Signature::from_slice(&signature_bytes).expect("64-byte signature"),
            )
            .unwrap_or_else(|_| panic!("fixture signature must verify for {id}"));
        credentials.insert(id, payload);
    }
    assert_eq!(credentials.len(), 5);

    let mut entitlements: BTreeMap<&str, &Value> = BTreeMap::new();
    for entitlement in fixture["entitlements"]
        .as_array()
        .expect("entitlements list")
    {
        let id = entitlement["id"].as_str().expect("entitlement id");
        entitlements.insert(id, entitlement);
    }
    assert_eq!(entitlements.len(), 4);

    // Every vector must match the Rust machine exactly (the PHP issuer
    // computed the expected labels with the same state machine).
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for vector in fixture["vectors"].as_array().expect("vectors list") {
        let id = vector["id"].as_str().expect("vector id");
        let entitlement = vector["entitlement"]
            .as_str()
            .and_then(|key| entitlements.get(key).copied())
            .map(entitlement_from_fixture);
        let credential = vector["credential"]
            .as_str()
            .and_then(|key| credentials.get(key).copied())
            .map(credential_from_fixture);
        let now = at(vector["now"].as_str().expect("vector timestamp"));
        let expected = vector["expected"].as_str().expect("expected state");
        let actual =
            LifetimeCredentialMachine::resolve(entitlement.as_ref(), credential.as_ref(), now);
        assert_eq!(
            actual.label(),
            expected,
            "vector {id}: machine must agree with the WPUIAI issuer"
        );
        *counts.entry(expected).or_default() += 1;
    }
    assert_eq!(fixture["vectors"].as_array().expect("vectors").len(), 14);

    // The acceptance criterion vectors must all be present with the expected
    // polarity.
    let covered: BTreeMap<&str, &str> = fixture["vectors"]
        .as_array()
        .expect("vectors")
        .iter()
        .map(|vector| {
            (
                vector["id"].as_str().expect("vector id"),
                vector["expected"].as_str().expect("expected"),
            )
        })
        .collect();
    for required in [
        ("lifetime_active_within_window", "active"),
        ("lifetime_offline_grace_bounded", "offline_grace"),
        ("lifetime_survives_credential_expiry", "recovery_only"),
        ("recovery_issuance_replaces_expired_lease", "active"),
        ("credential_rotation_preserves_lifetime", "active"),
        ("rotation_makes_old_credential_stale", "denied_stale"),
        ("key_rotation_preserves_lifetime", "active"),
        ("refund_defeats_active_credential", "denied_revoked"),
        ("revoke_defeats_offline_credential", "denied_revoked"),
        ("revoke_defeats_stale_credential", "denied_revoked"),
        ("missing_entitlement_denies", "denied_unknown"),
    ] {
        assert_eq!(
            covered.get(required.0),
            Some(&required.1),
            "required vector {} must exist with expected {}",
            required.0,
            required.1
        );
    }
}

fn entitlement_from_fixture(value: &Value) -> LifetimeEntitlement {
    let mut entitlement = LifetimeEntitlement::new(
        value["product"].as_str().expect("product"),
        value["license_type"].as_str().expect("license type"),
        value["sequence"].as_u64().expect("sequence"),
        value["price_version"].as_str().expect("price version"),
        value["family_digest"].as_str().expect("family digest"),
        value["node_limit"].as_u64().expect("node limit"),
        value["operator_seats"].as_u64().expect("operator seats"),
        at(value["updated_at"].as_str().expect("updated at")),
    )
    .expect("fixture entitlements are canonical");
    if value["status"].as_str() == Some("revoked") {
        entitlement.status = LifetimeEntitlementStatus::Revoked;
    }
    entitlement
}

fn credential_from_fixture(value: &Value) -> DeviceCredentialWindow {
    DeviceCredentialWindow {
        schema: value["schema"].as_str().expect("schema").to_string(),
        lease_id: value["lease_id"].as_str().expect("lease id").to_string(),
        product: value["product"].as_str().expect("product").to_string(),
        node_id: value["node_id"].as_str().expect("node id").to_string(),
        sequence: value["sequence"].as_u64().expect("sequence"),
        issued_at: at(value["issued_at"].as_str().expect("issued at")),
        expires_at: at(value["expires_at"].as_str().expect("expires at")),
        offline_grace_until: at(value["offline_grace_until"].as_str().expect("grace until")),
        authority_key_id: value["authority_key_id"]
            .as_str()
            .expect("authority key id")
            .to_string(),
        status: if value["status"].as_str() == Some("revoked") {
            DeviceCredentialStatus::Revoked
        } else {
            DeviceCredentialStatus::Active
        },
    }
}

fn hex_decode_into(hex: &str, out: &mut [u8]) {
    assert_eq!(hex.len(), out.len() * 2, "hex length");
    for (index, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[index * 2..index * 2 + 2], 16).expect("hex byte");
    }
}
