#!/usr/bin/env python3
"""Generate `CHANGELOG.md` from `release-proof/audit/audit.jsonl`.

For each unique release tag in scope (here, `v0.9.42-dev` for now), the
script emits a section listing the guard additions + self-heals that
landed, with links to the audit rows.

This is invoked by the release workflow and by `create-dev-release-tag.sh`.
Idempotent: regenerating the file produces the same bytes if the audit
ledger is unchanged.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from typing import Iterable

CATEGORIES_BY_LAYER = {
    "Layer 1 — Runner": ("runner",),
    "Layer 2 — Script": ("deploy",),
    "Layer 3 — Workflow": ("workflow", "ci", "release"),
    "Layer 4 — Audit": ("audit",),
    "Layer 5 — Repo / Ops": ("git", "ops"),
}


def _layer_for(subsystem: str) -> str:
    for layer, subs in CATEGORIES_BY_LAYER.items():
        if subsystem in subs:
            return layer
    return "Layer 5 — Repo / Ops"


def _format_row(row: dict, ledger_relpath: str) -> str:
    rid = row.get("id", "(no-id)")
    cat = row.get("category", "policy_violation")
    severity = row.get("severity", "info")
    summary = row.get("summary") or row.get("change") or row.get("symptom", "")
    fix = row.get("fix", "")
    guard = row.get("guard", "")
    test = row.get("test", "")
    linked = row.get("linked_run", "")
    failure_class = row.get("failure_class", "")
    retry_policy = row.get("retry_policy", "")
    remediation = row.get("remediation_template", "")
    source_refs = row.get("source_refs") or []
    pieces = [f"- **{rid}** (`{cat}`, `{severity}`): {summary}"]
    if failure_class:
        retry_suffix = f"; retry: `{retry_policy}`" if retry_policy else ""
        pieces.append(f"  - classifier: `{failure_class}`{retry_suffix}")
    if source_refs:
        rendered_refs = ", ".join(f"`{ref}`" for ref in source_refs[:5])
        pieces.append(f"  - source refs: {rendered_refs}")
    if remediation and remediation != fix:
        pieces.append(f"  - remediation: {remediation}")
    if fix and fix != "open":
        pieces.append(f"  - fix: {fix}")
    if guard and guard != "open":
        pieces.append(f"  - guard: {guard}")
    if test and test != "open":
        pieces.append(f"  - test: {test}")
    if linked and linked not in ("open", "", "self-test"):
        pieces.append(f"  - linked run: `{linked}`")
    return "\n".join(pieces)


def _format_heal(row: dict) -> str:
    rid = row.get("derived_from", "?")
    cat = row.get("category", "")
    auto = row.get("auto_generated", False)
    flag = "auto" if auto else "manual"
    return f"- **{rid}** (`{cat}`, `{flag}`)"


def generate(ledger_path: str, out_path: str, tag: str = "v0.9.42-dev") -> int:
    rows: list[dict] = []
    if os.path.exists(ledger_path):
        with open(ledger_path, "r", encoding="utf-8") as fh:
            for raw in fh:
                raw = raw.strip()
                if not raw:
                    continue
                rows.append(json.loads(raw))
    else:
        print(f"warn: ledger {ledger_path} missing; emitting empty changelog")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out: list[str] = []
    out.append(f"# Changelog — auto-generated from `release-proof/audit/audit.jsonl`")
    out.append("")
    out.append(f"_Last regenerated: {today}._")
    out.append("")
    out.append("> Do not edit this file by hand. Regenerate via:")
    out.append("> `python3 scripts/changelog-gen.py`")
    out.append(">")
    out.append("> See also: `docs/self-heal-chain.md` · `docs/failures-playbook.md` · `release-proof/audit/categories.md`")
    out.append("")
    out.append("## How to read this")
    out.append("")
    out.append("Each section groups audit rows by **self-heal layer**:")
    out.append("")
    for layer in CATEGORIES_BY_LAYER.keys():
        out.append(f"- {layer}")
    out.append("")
    out.append("Each row links back to the canonical ledger entry by `id`.")
    out.append("")

    out.append(f"## {tag} — release in scope")
    out.append("")
    by_layer: dict[str, list[dict]] = {layer: [] for layer in CATEGORIES_BY_LAYER}
    for row in rows:
        sub = row.get("subsystem", "ops")
        layer = _layer_for(sub)
        by_layer.setdefault(layer, []).append(row)
    for layer, layer_rows in by_layer.items():
        if not layer_rows:
            continue
        out.append(f"### {layer}")
        out.append("")
        for row in sorted(layer_rows, key=lambda r: r.get("ts", "")):
            if row.get("event") == "self_heal":
                out.append(_format_heal(row))
            else:
                out.append(_format_row(row, ledger_path))
        out.append("")

    out.append("## At-a-glance")
    out.append("")
    counts: dict[str, int] = {}
    for row in rows:
        kind = row.get("event", "other")
        counts[kind] = counts.get(kind, 0) + 1
    for kind, n in sorted(counts.items()):
        out.append(f"- {kind}: {n}")
    class_counts: dict[str, int] = {}
    for row in rows:
        failure_class = row.get("failure_class")
        if failure_class:
            class_counts[failure_class] = class_counts.get(failure_class, 0) + 1
    if class_counts:
        out.append("")
        out.append("### Failure classes")
        out.append("")
        for failure_class, n in sorted(class_counts.items()):
            out.append(f"- {failure_class}: {n}")
    out.append("")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {out_path} ({len(rows)} rows)")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ledger", default="release-proof/audit/audit.jsonl")
    parser.add_argument("--out", default="CHANGELOG.md")
    parser.add_argument("--tag", default="v0.9.42-dev")
    args = parser.parse_args(argv)
    return generate(args.ledger, args.out, args.tag)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))