#!/usr/bin/env python3
"""Generate deterministic JSON and PHP views of the Spec 152E EDD registry."""

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/contracts/spec152e-edd-product-registry.v1.yaml"
JSON_OUTPUT = ROOT / "docs/contracts/spec152e-edd-product-registry.v1.json"
PHP_OUTPUT = ROOT / "docs/contracts/spec152e-edd-product-registry.v1.php"


def build():
    registry = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    offers = registry["protected_offers"]
    catalog = registry["current_edd_catalog"]["entries"]
    legacy = registry["legacy_record_classes"]
    registry["counts"] = {
        "protected_offers": len(offers),
        "checkout_enabled": sum(bool(row["checkout_enabled"]) for row in offers),
        "assigned_edd_downloads": sum(row["edd_download_id"] is not None for row in offers),
        "catalog_entries": len(catalog),
        "legacy_record_classes": len(legacy),
        "legacy_migrate": sum(row["disposition"] == "migrate" for row in legacy),
        "legacy_quarantine": sum(row["disposition"] == "quarantine" for row in legacy),
        "legacy_retire": sum(row["disposition"] == "retire" for row in legacy),
    }
    return registry


def render_json(registry):
    return json.dumps(registry, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def render_php(registry):
    compact = json.dumps(registry, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return """<?php
// Generated by scripts/generate-spec152e-product-registry.py; do not hand-edit.
declare(strict_types=1);
return json_decode(<<<'FOCUSA_PRODUCT_REGISTRY_JSON'
%s
FOCUSA_PRODUCT_REGISTRY_JSON, true, 512, JSON_THROW_ON_ERROR);
""" % compact


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    registry = build()
    outputs = {
        JSON_OUTPUT: render_json(registry),
        PHP_OUTPUT: render_php(registry),
    }
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            raise SystemExit("stale Spec 152E product registry outputs: " + ", ".join(stale))
    else:
        for path, content in outputs.items():
            path.write_text(content, encoding="utf-8")
    print(json.dumps(registry["counts"], sort_keys=True))


if __name__ == "__main__":
    main()
