#!/usr/bin/env python3
"""Generate deterministic JSON and PHP views of the Spec 172 dedicated EDD Operator v1 downloads contract."""

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/contracts/spec172-edd-operator-v1-downloads.v1.yaml"
JSON_OUTPUT = ROOT / "docs/contracts/spec172-edd-operator-v1-downloads.v1.json"
PHP_OUTPUT = ROOT / "docs/contracts/spec172-edd-operator-v1-downloads.v1.php"


def build():
    contract = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    records = contract["records"]
    contract["counts"] = {
        "records": len(records),
        "checkout_enabled": sum(bool(row["checkout_enabled"]) for row in records),
        "assigned_edd_downloads": sum(row["edd_download_id"] is not None for row in records),
        "sum_amount_minor": sum(int(row["amount_minor"]) for row in records),
    }
    return contract


def render_json(contract):
    return json.dumps(contract, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def render_php(contract):
    compact = json.dumps(contract, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return """<?php
// Generated by scripts/generate-spec172-edd-operator-v1-downloads.py; do not hand-edit.
declare(strict_types=1);
return json_decode(<<<'FOCUSA_DEDICATED_DOWNLOADS_JSON'
%s
FOCUSA_DEDICATED_DOWNLOADS_JSON, true, 512, JSON_THROW_ON_ERROR);
""" % compact


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = build()
    outputs = {
        JSON_OUTPUT: render_json(contract),
        PHP_OUTPUT: render_php(contract),
    }
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            raise SystemExit("stale Spec 172 dedicated EDD downloads outputs: " + ", ".join(stale))
    else:
        for path, content in outputs.items():
            path.write_text(content, encoding="utf-8")
    print(json.dumps(contract["counts"], sort_keys=True))


if __name__ == "__main__":
    main()
