#!/usr/bin/env python3
"""Generate exact REST route → entitlement requirements from canonical descriptors."""

import importlib.util
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ROUTES = ROOT / "docs/contracts/spec141/generated-capability-v2/route-classification.json"
OPERATIONS = ROOT / "docs/contracts/spec135/generated-contract-v1/operation-registry.json"
FEATURES = ROOT / "docs/contracts/spec152-feature-registry.v1.yaml"
OUTPUT = ROOT / "crates/focusa-api/src/middleware/entitlement_routes.rs"
# Explicit overrides only where segment-based family resolution gives a different feature.
# Routes whose segment already maps to the correct feature are resolved by inheritance.
EXPLICIT_ROUTE_FEATURES = {
    "/v1/export/run": "focusa.export.packaged",
    "/v1/update/admin": "focusa.update.unattended",
    "/v1/update/apply": "focusa.update.apply",
    "/v1/update/notifications": "focusa.update.unattended",
    "/v1/update/policy": "focusa.update.unattended",
    "/v1/update/scheduler": "focusa.update.unattended",
}

# Recovery-excluded paths: the middleware's route_recovery_allowance handles these
# before the table is consulted; they must not appear as entitlement requirements.
RECOVERY_PATHS = {
    "/v1/update/rollback",
}

def _rest_segment(path):
    """Extract the first /v1/ segment from a REST path, normalising hyphens to underscores."""
    parts = path.strip("/").split("/")
    segment = parts[1] if len(parts) > 1 and parts[0] == "v1" else parts[0]
    return segment.replace("-", "_")

spec = importlib.util.spec_from_file_location("coverage", ROOT / "scripts/generate-spec152-entitlement-coverage.py")
coverage = importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(coverage)


def requirements():
    routes = json.loads(ROUTES.read_text())["routes"]
    operations = {item["operation_id"]: item for item in json.loads(OPERATIONS.read_text())["operations"]}
    feature_registry = yaml.safe_load(FEATURES.read_text())["features"]
    buckets = {item["key"]: item["limit_bucket"] for item in feature_registry}
    result = []
    for route in routes:
        # Recovery paths are handled by the middleware's route_recovery_allowance
        if route["path"] in RECOVERY_PATHS:
            continue
        features = set()
        # 1) Canonical operation refs (exact family → feature)
        for ref in route.get("operation_refs", []):
            if ref in operations:
                family_feature = coverage.FAMILY_FEATURE.get(operations[ref].get("family"))
                if family_feature:
                    features.add(family_feature)
        # 2) Explicit override (route-specific)
        if not features and route["path"] in EXPLICIT_ROUTE_FEATURES:
            features.add(EXPLICIT_ROUTE_FEATURES[route["path"]])
        # 3) Segment-based family inheritance (normalise hyphens → underscores)
        if not features:
            seg = _rest_segment(route["path"])
            family_feature = coverage.FAMILY_FEATURE.get(seg)
            if family_feature:
                features.add(family_feature)
        if len(features) > 1:
            raise ValueError(f"conflicting entitlement features for {route['path']}: {sorted(features)}")
        if len(features) == 1:
            feature = next(iter(features))
            if feature not in buckets:
                raise ValueError(f"unregistered feature {feature}")
            result.append((route["path"], feature, buckets[feature]))
    if len({path for path, _, _ in result}) != len(result):
        raise ValueError("duplicate governed route")
    return sorted(result)


def render():
    rows = requirements()
    entries = "\n".join(
        "\n".join([
            "    RouteEntitlementRequirement {",
            f"        template: {json.dumps(path)},",
            f"        feature: {json.dumps(feature)},",
            f'        limit_bucket: {"Some(" + json.dumps(bucket) + ")" if bucket else "None"},',
            "    },",
        ])
        for path, feature, bucket in rows
    )
    return f'''//! Generated by scripts/generate-spec152-route-entitlement-table.py. Do not hand-edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct RouteEntitlementRequirement {{
    pub template: &'static str,
    pub feature: &'static str,
    pub limit_bucket: Option<&'static str>,
}}

pub(crate) static ROUTE_ENTITLEMENT_REQUIREMENTS: &[RouteEntitlementRequirement] = &[
{entries}
];

pub(crate) fn requirement_for_path(path: &str) -> Option<&'static RouteEntitlementRequirement> {{
    ROUTE_ENTITLEMENT_REQUIREMENTS
        .iter()
        .find(|requirement| template_matches(requirement.template, path))
}}

fn template_matches(template: &str, path: &str) -> bool {{
    let template_segments: Vec<_> = template.trim_matches('/').split('/').collect();
    let path_segments: Vec<_> = path.trim_matches('/').split('/').collect();
    template_segments.len() == path_segments.len()
        && template_segments
            .iter()
            .zip(path_segments)
            .all(|(expected, actual)| {{
                (expected.starts_with('{{') && expected.ends_with('}}'))
                    || expected.starts_with(':')
                    || *expected == actual
            }})
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn exact_and_parameterized_routes_match_without_prefix_guessing() {{
        assert!(requirement_for_path("/v1/workpoint/checkpoint").is_some());
        assert!(requirement_for_path("/not/a/focusa/route").is_none());
        assert!(!template_matches("/v1/items/{{id}}", "/v1/items"));
        assert!(template_matches("/v1/items/{{id}}", "/v1/items/item-1"));
    }}
}}
'''


if __name__ == "__main__":
    rendered = render()
    OUTPUT.write_text(rendered)
    print(json.dumps({"routes": len(requirements()), "output": str(OUTPUT.relative_to(ROOT))}))
