#!/usr/bin/env python3
"""Generate exact REST route → entitlement requirements from canonical descriptors."""

import importlib.util
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ROUTES = ROOT / "docs/contracts/spec141/generated-capability-v2/route-classification.json"
OPERATIONS = ROOT / "docs/contracts/spec135/generated-contract-v1/operation-registry.json"
FEATURES = ROOT / "docs/contracts/spec152-feature-registry.v1.yaml"
OUTPUT = ROOT / "crates/focusa-api/src/middleware/entitlement_routes.rs"
EXPLICIT_ROUTE_FEATURES = {
    "/v1/connect/approve": "focusa.team.multi_operator",
    "/v1/connect/room/create": "focusa.team.multi_operator",
    "/v1/connect/room/start": "focusa.team.multi_operator",
    "/v1/connect/room/{room_id}/approve": "focusa.team.multi_operator",
    "/v1/connect/room/{room_id}/join": "focusa.team.multi_operator",
    "/v1/connect/room/{room_id}/mac-offer": "focusa.team.multi_operator",
    "/v1/connect/start": "focusa.team.multi_operator",
    "/v1/device/pair/complete": "focusa.team.multi_operator",
    "/v1/device/pair/revoke": "focusa.team.multi_operator",
    "/v1/device/pair/start": "focusa.team.multi_operator",
    "/v1/export/run": "focusa.export.packaged",
    "/v1/update/admin": "focusa.update.unattended",
    "/v1/update/apply": "focusa.update.apply",
    "/v1/update/notifications": "focusa.update.unattended",
    "/v1/update/policy": "focusa.update.unattended",
    "/v1/update/scheduler": "focusa.update.unattended",
    "/v1/work-loop/checkpoint": "focusa.core.workpoint",
    "/v1/work-loop/context": "focusa.core.workpoint",
    "/v1/work-loop/degraded": "focusa.core.workpoint",
    "/v1/work-loop/delegation/clear": "focusa.core.workpoint",
    "/v1/work-loop/delegation/enable": "focusa.core.workpoint",
    "/v1/work-loop/enable": "focusa.core.workpoint",
    "/v1/work-loop/events": "focusa.core.workpoint",
    "/v1/work-loop/heartbeat": "focusa.core.workpoint",
    "/v1/work-loop/pause": "focusa.core.workpoint",
    "/v1/work-loop/pause-flags": "focusa.core.workpoint",
    "/v1/work-loop/resume": "focusa.core.workpoint",
    "/v1/work-loop/select-next": "focusa.core.workpoint",
    "/v1/work-loop/session/abort": "focusa.core.workpoint",
    "/v1/work-loop/session/attach": "focusa.core.workpoint",
    "/v1/work-loop/stop": "focusa.core.workpoint",
}

spec = importlib.util.spec_from_file_location("coverage", ROOT / "scripts/generate-spec152-entitlement-coverage.py")
coverage = importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(coverage)


def requirements():
    routes = json.loads(ROUTES.read_text())["routes"]
    operations = {item["operation_id"]: item for item in json.loads(OPERATIONS.read_text())["operations"]}
    feature_registry = yaml.safe_load(FEATURES.read_text())["features"]
    buckets = {item["key"]: item["limit_bucket"] for item in feature_registry}
    result = []
    for route in routes:
        features = {
            coverage.FAMILY_FEATURE.get(operations[ref].get("family"))
            for ref in route.get("operation_refs", [])
            if ref in operations
        }
        features.discard(None)
        if len(features) > 1:
            raise ValueError(f"conflicting entitlement features for {route['path']}: {sorted(features)}")
        if not features and route["path"] in EXPLICIT_ROUTE_FEATURES:
            features = {EXPLICIT_ROUTE_FEATURES[route["path"]]}
        if len(features) == 1:
            feature = next(iter(features))
            if feature not in buckets:
                raise ValueError(f"unregistered feature {feature}")
            result.append((route["path"], feature, buckets[feature]))
    if len({path for path, _, _ in result}) != len(result):
        raise ValueError("duplicate governed route")
    return sorted(result)


def render():
    rows = requirements()
    entries = "\n".join(
        "\n".join([
            "    RouteEntitlementRequirement {",
            f"        template: {json.dumps(path)},",
            f"        feature: {json.dumps(feature)},",
            f'        limit_bucket: {"Some(" + json.dumps(bucket) + ")" if bucket else "None"},',
            "    },",
        ])
        for path, feature, bucket in rows
    )
    return f'''//! Generated by scripts/generate-spec152-route-entitlement-table.py. Do not hand-edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct RouteEntitlementRequirement {{
    pub template: &'static str,
    pub feature: &'static str,
    pub limit_bucket: Option<&'static str>,
}}

pub(crate) static ROUTE_ENTITLEMENT_REQUIREMENTS: &[RouteEntitlementRequirement] = &[
{entries}
];

pub(crate) fn requirement_for_path(path: &str) -> Option<&'static RouteEntitlementRequirement> {{
    ROUTE_ENTITLEMENT_REQUIREMENTS
        .iter()
        .find(|requirement| template_matches(requirement.template, path))
}}

fn template_matches(template: &str, path: &str) -> bool {{
    let template_segments: Vec<_> = template.trim_matches('/').split('/').collect();
    let path_segments: Vec<_> = path.trim_matches('/').split('/').collect();
    template_segments.len() == path_segments.len()
        && template_segments
            .iter()
            .zip(path_segments)
            .all(|(expected, actual)| {{
                (expected.starts_with('{{') && expected.ends_with('}}'))
                    || expected.starts_with(':')
                    || *expected == actual
            }})
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn exact_and_parameterized_routes_match_without_prefix_guessing() {{
        assert!(requirement_for_path("/v1/workpoint/checkpoint").is_some());
        assert!(requirement_for_path("/not/a/focusa/route").is_none());
        assert!(!template_matches("/v1/items/{{id}}", "/v1/items"));
        assert!(template_matches("/v1/items/{{id}}", "/v1/items/item-1"));
    }}
}}
'''


if __name__ == "__main__":
    rendered = render()
    OUTPUT.write_text(rendered)
    print(json.dumps({"routes": len(requirements()), "output": str(OUTPUT.relative_to(ROOT))}))
