#!/usr/bin/env python3
"""Generate Spec 135C-3 named workspace invalidation contract."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "docs/contracts/spec135/generated-contract-v1/json-schema"
SCHEMA_PATH = SCHEMA_DIR / "focusa.workspace_event.v1.json"
CONTRACT_PATH = ROOT / "docs/contracts/spec135-workspace-invalidation-live-refresh.v1.json"
EVENTS = [
    "uiai_session_opened", "uiai_session_status_changed",
    "uiai_fpv_share_created", "browser_context_created", "browser_context_status_changed",
    "browser_context_closed", "browser_target_opened", "browser_target_navigated",
    "browser_target_moved", "browser_target_closed", "workspace_artifact_capture_pending",
    "workspace_artifact_linked", "workspace_artifact_verified", "workspace_artifact_stale",
    "workspace_artifact_redacted", "workspace_artifact_removed", "workspace_artifact_render_failed",
]
SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://docs.startempire.ai/focusa/spec135/focusa.workspace_event.v1.json",
    "title": "Focusa Workspace Invalidation Event v1",
    "type": "object",
    "required": ["schema", "event", "event_id", "cursor", "project_root", "continuity_id", "session_id", "attachment_id", "invalidate"],
    "properties": {
        "schema": {"const": "focusa.workspace_event.v1"},
        "event": {"type": "string", "enum": EVENTS},
        "event_id": {"type": "string", "minLength": 1},
        "cursor": {"type": "string", "minLength": 1},
        "project_root": {"type": "string", "minLength": 1},
        "continuity_id": {"type": "string", "minLength": 1},
        "session_id": {"type": "string", "minLength": 1},
        "attachment_id": {"type": "string", "minLength": 1},
        "work_surface_id": {"type": "string"},
        "artifact_id": {"type": "string"},
        "invalidate": {"type": "array", "minItems": 1, "items": {"type": "string", "pattern": "^(mission_canvas|workspace|workpoint|context|connectors)\\."}},
    },
    "additionalProperties": False,
}
CONTRACT = {
    "schema": "focusa.spec135.workspace_invalidation_live_refresh.v1",
    "acceptance_criteria": "Canvas updates affected panels live and reconnects through replay without whole-state pushes.",
    "primary_transport": "Focusa SSE",
    "fallback_transport": "bounded polling only when SSE is unavailable",
    "refresh_pipeline": ["reconnectable event cursor", "validate project/workstream and origin identity", "map event to named query keys", "invalidate affected bounded read models", "refetch visible or subscribed views", "rerender"],
    "laws": [
        "No full Mission Canvas or workspace refetch for unrelated events",
        "No high-frequency hidden-pane rerender unless subscribed",
        "Workspace invalidation is not an ontology promotion event",
        "Semantic delta and UI invalidation remain separately versioned",
        "Disconnect shows stale state until cursor replay reaches live",
    ],
    "event_types": EVENTS,
    "schema_ref": "docs/contracts/spec135/generated-contract-v1/json-schema/focusa.workspace_event.v1.json",
}
SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
# The canonical workspace-event schema is generated by the shared Spec 135
# contract pipeline. C3 consumes it; it must not replace that richer schema.
canonical_schema = json.loads(SCHEMA_PATH.read_text())
assert canonical_schema["properties"]["schema"]["const"] == "focusa.workspace_event.v1"
assert set(EVENTS).issubset(set(canonical_schema["properties"]["event"]["enum"]))
CONTRACT_PATH.write_text(json.dumps(CONTRACT, indent=2) + "\n")
print(f"Spec 135C-3 workspace invalidation generated: {len(EVENTS)} event types")
