//! Spec 109 AX-001 — Authoritative Agent Capabilities Endpoint.
//!
//! `GET /v1/agent/capabilities` returns a compact machine-readable index of
//! every Focusa operation, with metadata for schema, side effects, permissions,
//! and documentation refs. Agents use this to discover what Focusa can do
//! without reading docs.

use crate::server::AppState;
use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::{Json, Router, routing::get};
use serde::Serialize;
use serde_json::{Value, json};
use std::sync::Arc;
use chrono::Utc;

#[derive(Debug, Serialize)]
struct CapabilitiesIndex {
    #[serde(rename = "schema")]
    schema: &'static str,
    api_version: &'static str,
    generated_at: String,
    operation_count: usize,
    families: Vec<&'static str>,
    operations: Vec<OperationEntry>,
}

#[derive(Debug, Serialize)]
struct OperationEntry {
    operation_id: &'static str,
    label: &'static str,
    family: &'static str,
    method: &'static str,
    path: &'static str,
    canonical: bool,
    alias_of: Option<&'static str>,
    operation_version: &'static str,
    schema_version: &'static str,
    side_effect_profile: &'static str,
    materialization_mode: &'static str,
    supports_side_effect_policy: Vec<&'static str>,
    requires_idempotency_key: bool,
    requires_if_match_version: bool,
    requires_preview_token: bool,
    permissions_required: Vec<&'static str>,
    confirmation_required: bool,
    budget_profile: &'static str,
    response_detail_supported: Vec<&'static str>,
    request_schema_ref: &'static str,
    response_schema_ref: &'static str,
    error_taxonomy_ref: &'static str,
    examples_ref: &'static str,
    docs_ref: &'static str,
    deprecation: Option<DeprecationEntry>,
}

#[derive(Debug, Serialize)]
struct DeprecationEntry {
    deprecated: bool,
    deprecation_message: &'static str,
    deprecation_removed_in: &'static str,
    deprecation_replacement: &'static str,
}

#[allow(clippy::too_many_arguments)]
fn op(
    id: &'static str,
    label: &'static str,
    family: &'static str,
    method: &'static str,
    path: &'static str,
    canonical: bool,
    alias_of: Option<&'static str>,
    side_effect: &'static str,
    materialization: &'static str,
    policies: Vec<&'static str>,
    req_idempotency: bool,
    req_if_match: bool,
    req_preview: bool,
    permissions: Vec<&'static str>,
    confirm: bool,
    budget: &'static str,
    detail: Vec<&'static str>,
    req_schema: &'static str,
    res_schema: &'static str,
    docs: &'static str,
    deprecation: Option<DeprecationEntry>,
) -> OperationEntry {
    OperationEntry {
        operation_id: id,
        label,
        family,
        method,
        path,
        canonical,
        alias_of,
        operation_version: "1.0.0",
        schema_version: req_schema,
        side_effect_profile: side_effect,
        materialization_mode: materialization,
        supports_side_effect_policy: policies,
        requires_idempotency_key: req_idempotency,
        requires_if_match_version: req_if_match,
        requires_preview_token: req_preview,
        permissions_required: permissions,
        confirmation_required: confirm,
        budget_profile: budget,
        response_detail_supported: detail,
        request_schema_ref: req_schema,
        response_schema_ref: res_schema,
        error_taxonomy_ref: "/v1/agent/error-taxonomy",
        examples_ref: "/v1/agent/examples/operations",
        docs_ref: docs,
        deprecation,
    }
}

fn build_operations() -> Vec<OperationEntry> {
    vec![
        // ── health ──────────────────────────────────────────────────────────
        op(
            "focusa.health.check",
            "Health Check",
            "health",
            "GET",
            "/v1/health",
            true, None,
            "read_health",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["health:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.health.request.v1",
            "focusa.health.response.v1",
            "docs/focusa-api/routes/health.md",
            None,
        ),
        // ── project identity ────────────────────────────────────────────────
        op(
            "focusa.project.identity",
            "Project Identity",
            "project",
            "GET",
            "/v1/project/identity",
            true, None,
            "read_identity",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["project:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.project_identity.request.v1",
            "focusa.project_identity.response.v1",
            "docs/focusa-api/routes/project.md",
            None,
        ),
        op(
            "focusa.project.verify",
            "Project Verify",
            "project",
            "GET",
            "/v1/project/verify",
            true, None,
            "read_verify",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["project:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.project_verify.request.v1",
            "focusa.project_verify.response.v1",
            "docs/focusa-api/routes/project.md",
            None,
        ),
        // ── trajectory ───────────────────────────────────────────────────────
        op(
            "focusa.trajectory.view",
            "Trajectory View",
            "trajectory",
            "GET",
            "/v1/trajectory/view",
            true, None,
            "read_trajectory",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["trajectory:read"],
            false,
            "light_read",
            vec!["compact", "standard", "debug"],
            "focusa.trajectory_view.request.v1",
            "focusa.trajectory_view.response.v1",
            "docs/focusa-api/routes/trajectory.md",
            None,
        ),
        op(
            "focusa.trajectory.define_goal",
            "Trajectory Define Goal",
            "trajectory",
            "POST",
            "/v1/trajectory/define-goal",
            true, None,
            "write_trajectory_goal",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["trajectory:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.trajectory_define_goal.request.v1",
            "focusa.trajectory_define_goal.response.v1",
            "docs/focusa-api/routes/trajectory.md",
            None,
        ),
        op(
            "focusa.trajectory.assess",
            "Trajectory Assess",
            "trajectory",
            "POST",
            "/v1/trajectory/assess",
            true, None,
            "read_trajectory_assess",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["trajectory:read"],
            false,
            "standard_read",
            vec!["compact", "standard", "debug"],
            "focusa.trajectory_assess.request.v1",
            "focusa.trajectory_assess.response.v1",
            "docs/focusa-api/routes/trajectory.md",
            None,
        ),
        op(
            "focusa.trajectory.propose_workpoint",
            "Trajectory Propose Workpoint",
            "trajectory",
            "POST",
            "/v1/trajectory/propose-workpoint",
            true, None,
            "read_trajectory_propose",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["trajectory:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.trajectory_propose_workpoint.request.v1",
            "focusa.trajectory_propose_workpoint.response.v1",
            "docs/focusa-api/routes/trajectory.md",
            None,
        ),
        op(
            "focusa.trajectory.checkpoint",
            "Trajectory Checkpoint",
            "trajectory",
            "POST",
            "/v1/trajectory/checkpoint",
            true, None,
            "write_trajectory_checkpoint",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["trajectory:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.trajectory_checkpoint.request.v1",
            "focusa.trajectory_checkpoint.response.v1",
            "docs/focusa-api/routes/trajectory.md",
            None,
        ),
        op(
            "focusa.trajectory.resume",
            "Trajectory Resume",
            "trajectory",
            "POST",
            "/v1/trajectory/resume",
            true, None,
            "read_trajectory_resume",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["trajectory:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.trajectory_resume.request.v1",
            "focusa.trajectory_resume.response.v1",
            "docs/focusa-api/routes/trajectory.md",
            None,
        ),
        // ── workpoint ────────────────────────────────────────────────────────
        op(
            "focusa.workpoint.checkpoint",
            "Workpoint Checkpoint",
            "workpoint",
            "POST",
            "/v1/workpoint/checkpoint",
            true, None,
            "write_workpoint_checkpoint",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, true, false,
            vec!["workpoint:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard", "debug"],
            "focusa.workpoint_checkpoint.request.v1",
            "focusa.workpoint_checkpoint.response.v1",
            "docs/focusa-api/routes/workpoint.md",
            None,
        ),
        op(
            "focusa.workpoint.resume",
            "Workpoint Resume",
            "workpoint",
            "GET",
            "/v1/workpoint/resume",
            true, None,
            "read_workpoint_resume",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["workpoint:read"],
            false,
            "standard_read",
            vec!["compact", "standard", "debug"],
            "focusa.workpoint_resume.request.v1",
            "focusa.workpoint_resume.response.v1",
            "docs/focusa-api/routes/workpoint.md",
            None,
        ),
        op(
            "focusa.workpoint.link_evidence",
            "Workpoint Link Evidence",
            "workpoint",
            "POST",
            "/v1/workpoint/link-evidence",
            true, None,
            "write_workpoint_evidence",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, true, false,
            vec!["workpoint:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.workpoint_link_evidence.request.v1",
            "focusa.workpoint_link_evidence.response.v1",
            "docs/focusa-api/routes/workpoint.md",
            None,
        ),
        // ── metacognition ────────────────────────────────────────────────────
        op(
            "focusa.metacog.capture",
            "Metacog Capture",
            "metacognition",
            "POST",
            "/v1/metacognition/capture",
            true, None,
            "write_metacog_signal",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["metacog:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.metacog_capture.request.v1",
            "focusa.metacog_capture.response.v1",
            "docs/focusa-api/routes/metacognition.md",
            None,
        ),
        op(
            "focusa.metacog.retrieve",
            "Metacog Retrieve",
            "metacognition",
            "POST",
            "/v1/metacognition/retrieve",
            true, None,
            "read_metacog",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["metacog:read"],
            false,
            "standard_read",
            vec!["compact", "standard", "debug"],
            "focusa.metacog_retrieve.request.v1",
            "focusa.metacog_retrieve.response.v1",
            "docs/focusa-api/routes/metacognition.md",
            None,
        ),
        op(
            "focusa.metacog.reflect",
            "Metacog Reflect",
            "metacognition",
            "POST",
            "/v1/metacognition/reflect",
            true, None,
            "read_metacog_reflect",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["metacog:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.metacog_reflect.request.v1",
            "focusa.metacog_reflect.response.v1",
            "docs/focusa-api/routes/metacognition.md",
            None,
        ),
        op(
            "focusa.metacog.doctor",
            "Metacog Doctor",
            "metacognition",
            "POST",
            "/v1/metacognition/doctor",
            true, None,
            "read_metacog_doctor",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["metacog:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.metacog_doctor.request.v1",
            "focusa.metacog_doctor.response.v1",
            "docs/focusa-api/routes/metacognition.md",
            None,
        ),
        // ── evidence ─────────────────────────────────────────────────────────
        op(
            "focusa.evidence.capture",
            "Evidence Capture",
            "evidence",
            "POST",
            "/v1/evidence/capture",
            true, None,
            "write_evidence",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["evidence:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.evidence_capture.request.v1",
            "focusa.evidence_capture.response.v1",
            "docs/focusa-api/routes/evidence.md",
            None,
        ),
        // ── prediction ───────────────────────────────────────────────────────
        op(
            "focusa.prediction.record",
            "Prediction Record",
            "prediction",
            "POST",
            "/v1/predictions/record",
            true, None,
            "write_prediction",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["prediction:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.prediction_record.request.v1",
            "focusa.prediction_record.response.v1",
            "docs/focusa-api/routes/predictions.md",
            None,
        ),
        op(
            "focusa.prediction.evaluate",
            "Prediction Evaluate",
            "prediction",
            "POST",
            "/v1/predictions/evaluate",
            true, None,
            "write_prediction_eval",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["prediction:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.prediction_evaluate.request.v1",
            "focusa.prediction_evaluate.response.v1",
            "docs/focusa-api/routes/predictions.md",
            None,
        ),
        op(
            "focusa.prediction.recent",
            "Prediction Recent",
            "prediction",
            "GET",
            "/v1/predictions/recent",
            true, None,
            "read_prediction",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["prediction:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.prediction_recent.request.v1",
            "focusa.prediction_recent.response.v1",
            "docs/focusa-api/routes/predictions.md",
            None,
        ),
        // ── context cognition ────────────────────────────────────────────────
        op(
            "focusa.context_cognition.packet",
            "Context Cognition Packet",
            "context_cognition",
            "GET",
            "/v1/context-cognition/packet",
            true, None,
            "read_context",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["context:read"],
            false,
            "heavy_read",
            vec!["compact", "standard", "debug"],
            "focusa.context_cognition_packet.request.v1",
            "focusa.context_cognition_packet.response.v1",
            "docs/focusa-api/routes/context_cognition.md",
            None,
        ),
        op(
            "focusa.context_cognition.curate",
            "Context Cognition Curate",
            "context_cognition",
            "POST",
            "/v1/context-cognition/curate",
            true, None,
            "read_context_curate",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["context:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.context_cognition_curate.request.v1",
            "focusa.context_cognition_curate.response.v1",
            "docs/focusa-api/routes/context_cognition.md",
            None,
        ),
        // ── tool doctor ──────────────────────────────────────────────────────
        op(
            "focusa.tool_doctor",
            "Tool Doctor",
            "diagnostics",
            "GET",
            "/v1/tool-doctor",
            true, None,
            "read_diagnostics",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["diagnostics:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.tool_doctor.request.v1",
            "focusa.tool_doctor.response.v1",
            "docs/focusa-api/routes/tool_doctor.md",
            None,
        ),
        // ── awareness ────────────────────────────────────────────────────────
        op(
            "focusa.awareness.packet",
            "Awareness Packet",
            "awareness",
            "POST",
            "/v1/awareness/packet",
            true, None,
            "read_awareness",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["awareness:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.awareness_packet.request.v1",
            "focusa.awareness_packet.response.v1",
            "docs/focusa-api/routes/awareness.md",
            None,
        ),
        // ── resource mode ────────────────────────────────────────────────────
        op(
            "focusa.resource_mode",
            "Resource Mode",
            "resource",
            "GET",
            "/v1/resource/mode",
            true, None,
            "read_resource",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["resource:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.resource_mode.request.v1",
            "focusa.resource_mode.response.v1",
            "docs/focusa-api/routes/resource.md",
            None,
        ),
        // ── traverse ─────────────────────────────────────────────────────────
        op(
            "focusa.traverse",
            "Traverse",
            "traverse",
            "POST",
            "/v1/traverse",
            true, None,
            "read_traverse",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["traverse:read"],
            false,
            "heavy_read",
            vec!["compact", "standard", "debug"],
            "focusa.traverse.request.v1",
            "focusa.traverse.response.v1",
            "docs/focusa-api/routes/traverse.md",
            None,
        ),
        // ── state ────────────────────────────────────────────────────────────
        op(
            "focusa.state.current",
            "State Current",
            "state",
            "GET",
            "/v1/state/current",
            true, None,
            "read_state",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["state:read"],
            false,
            "standard_read",
            vec!["compact", "standard", "debug"],
            "focusa.state_current.request.v1",
            "focusa.state_current.response.v1",
            "docs/focusa-api/routes/state.md",
            None,
        ),
        // ── lineage ──────────────────────────────────────────────────────────
        op(
            "focusa.lineage.head",
            "Lineage Head",
            "lineage",
            "GET",
            "/v1/lineage/head",
            true, None,
            "read_lineage",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["lineage:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.lineage_head.request.v1",
            "focusa.lineage_head.response.v1",
            "docs/focusa-api/routes/lineage.md",
            None,
        ),
        op(
            "focusa.lineage.tree",
            "Lineage Tree",
            "lineage",
            "GET",
            "/v1/lineage/tree",
            true, None,
            "read_lineage_tree",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["lineage:read"],
            false,
            "heavy_read",
            vec!["compact", "standard", "debug"],
            "focusa.lineage_tree.request.v1",
            "focusa.lineage_tree.response.v1",
            "docs/focusa-api/routes/lineage.md",
            None,
        ),
        // ── bloatgaurd ───────────────────────────────────────────────────────
        op(
            "focusa.bloatgaurd.report",
            "Bloatgaurd Report",
            "bloatgaurd",
            "GET",
            "/v1/bloatgaurd/report",
            true, None,
            "read_bloatgaurd",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["bloatgaurd:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.bloatgaurd_report.request.v1",
            "focusa.bloatgaurd_report.response.v1",
            "docs/focusa-api/routes/bloatgaurd.md",
            None,
        ),
        // ── device pairing ───────────────────────────────────────────────────
        op(
            "focusa.device_pair.start",
            "Device Pair Start",
            "device",
            "POST",
            "/v1/device/pair/start",
            true, None,
            "write_pairing",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            false, false, false,
            vec!["device:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.device_pair_start.request.v1",
            "focusa.device_pair_start.response.v1",
            "docs/focusa-api/routes/device.md",
            None,
        ),
        op(
            "focusa.device_pair.status",
            "Device Pair Status",
            "device",
            "GET",
            "/v1/device/pair/status",
            true, None,
            "read_pairing",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["device:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.device_pair_status.request.v1",
            "focusa.device_pair_status.response.v1",
            "docs/focusa-api/routes/device.md",
            None,
        ),
        // ── work loop ────────────────────────────────────────────────────────
        op(
            "focusa.work_loop.status",
            "Work Loop Status",
            "work_loop",
            "GET",
            "/v1/work-loop/status",
            true, None,
            "read_work_loop",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["work_loop:read"],
            false,
            "light_read",
            vec!["compact", "standard"],
            "focusa.work_loop_status.request.v1",
            "focusa.work_loop_status.response.v1",
            "docs/focusa-api/routes/work_loop.md",
            None,
        ),
        op(
            "focusa.work_loop.control",
            "Work Loop Control",
            "work_loop",
            "POST",
            "/v1/work-loop/control",
            true, None,
            "write_work_loop",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["work_loop:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.work_loop_control.request.v1",
            "focusa.work_loop_control.response.v1",
            "docs/focusa-api/routes/work_loop.md",
            None,
        ),
        // ── license ──────────────────────────────────────────────────────────
        op(
            "focusa.license.validate",
            "License Validate",
            "license",
            "POST",
            "/v1/license/validate",
            true, None,
            "write_license",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["license:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.license_validate.request.v1",
            "focusa.license_validate.response.v1",
            "docs/focusa-api/routes/license.md",
            None,
        ),
        // ── DXUX ─────────────────────────────────────────────────────────────
        op(
            "focusa.dxux.report",
            "DXUX Report",
            "dxux",
            "GET",
            "/v1/dxux/report",
            true, None,
            "read_dxux",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["dxux:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.dxux_report.request.v1",
            "focusa.dxux_report.response.v1",
            "docs/focusa-api/routes/dxux.md",
            None,
        ),
        // ── call stack ───────────────────────────────────────────────────────
        op(
            "focusa.call_stack.design",
            "Call Stack Design",
            "call_stack",
            "POST",
            "/v1/call-stack/design",
            true, None,
            "write_call_stack",
            "daemon_dispatch",
            vec!["dry_run", "preview", "commit"],
            true, false, false,
            vec!["call_stack:write"],
            false,
            "standard_mutation",
            vec!["compact", "standard"],
            "focusa.call_stack_design.request.v1",
            "focusa.call_stack_design.response.v1",
            "docs/focusa-api/routes/call_stack.md",
            None,
        ),
        op(
            "focusa.call_stack.verify",
            "Call Stack Verify",
            "call_stack",
            "POST",
            "/v1/call-stack/verify",
            true, None,
            "read_call_stack_verify",
            "advisory_read",
            vec!["preview", "commit"],
            false, false, false,
            vec!["call_stack:read"],
            false,
            "standard_read",
            vec!["compact", "standard"],
            "focusa.call_stack_verify.request.v1",
            "focusa.call_stack_verify.response.v1",
            "docs/focusa-api/routes/call_stack.md",
            None,
        ),
    ]
}

fn build_families() -> Vec<&'static str> {
    vec![
        "health",
        "project",
        "trajectory",
        "workpoint",
        "metacognition",
        "evidence",
        "prediction",
        "context_cognition",
        "diagnostics",
        "awareness",
        "resource",
        "traverse",
        "state",
        "lineage",
        "bloatgaurd",
        "device",
        "work_loop",
        "license",
        "dxux",
        "call_stack",
    ]
}

pub async fn capabilities_index_handler(
    State(_state): State<Arc<AppState>>,
) -> Json<Value> {
    let operations = build_operations();
    let families = build_families();
    let index = CapabilitiesIndex {
        schema: "focusa.agent_capabilities.index.v1",
        api_version: "v1",
        generated_at: Utc::now().to_rfc3339(),
        operation_count: operations.len(),
        families,
        operations,
    };
    Json(serde_json::to_value(&index).unwrap_or(json!({
        "status": "error",
        "failure_class": "serialization_error",
        "message": "Failed to serialize capabilities index"
    })))
}

pub async fn list_schemas(
    State(_state): State<Arc<AppState>>,
) -> Json<Value> {
    let schema_ids: Vec<&str> = build_operations()
        .iter()
        .flat_map(|op| vec![op.request_schema_ref, op.response_schema_ref])
        .collect::<std::collections::BTreeSet<&str>>()
        .into_iter()
        .collect();
    Json(json!({
        "schema": "focusa.agent_schema_index.v1",
        "api_version": "v1",
        "generated_at": chrono::Utc::now().to_rfc3339(),
        "schema_count": schema_ids.len(),
        "schemas": schema_ids,
        "list_detail": "GET /v1/agent/schemas/{schema_id}",
    }))
}

pub async fn get_schema(
    State(_state): State<Arc<AppState>>,
    Path(schema_id): Path<String>,
) -> Result<Json<Value>, (StatusCode, Json<Value>)> {
    // Return a minimal schema descriptor. For a full JSON Schema compatible
    // document, each schema_id would reference a generated OpenAPI component.
    // Here we return a placeholder that documents the schema identity.
    let normalized = schema_id.trim().to_string();
    if normalized.is_empty() || normalized.len() > 256 {
        return Err((StatusCode::BAD_REQUEST, Json(json!({
            "status": "validation_rejected",
            "failure_class": "invalid_schema_id",
            "message": "Schema ID must be 1-256 characters",
            "requested": schema_id,
        }))));
    }
    Ok(Json(json!({
        "schema": "focusa.schema_descriptor.v1",
        "schema_id": normalized,
        "description": format!("Schema descriptor for {}", normalized),
        "api_version": "v1",
        "generated_at": chrono::Utc::now().to_rfc3339(),
        "fields": [],
        "full_schema_url": format!("/v1/openapi.json#/components/schemas/{}", normalized.replace(['.', '/'], "_")),
    })))
}

pub async fn openapi_export(
    State(_state): State<Arc<AppState>>,
) -> Json<Value> {
    let ops = build_operations();
    let mut paths = serde_json::Map::new();
    for op in &ops {
        let path_key = op.path.to_string();
        let method_key = op.method.to_lowercase();
        let entry = paths.entry(path_key).or_insert_with(|| json!({}));
        if let Some(obj) = entry.as_object_mut() {
            let response_schema = json!({
                "description": format!("{} response", op.label),
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": format!("#/components/schemas/{}", op.response_schema_ref.replace('.', "_")),
                        }
                    }
                }
            });
            obj.insert(method_key, json!({
                "operationId": op.operation_id,
                "summary": op.label,
                "description": format!("{} — family={} budget={} materialization={}", op.label, op.family, op.budget_profile, op.materialization_mode),
                "tags": [op.family],
                "parameters": [
                    {"name": "project_root", "in": "query", "schema": {"type": "string"}, "description": "Project root for scoping"},
                    {"name": "continuity_id", "in": "query", "schema": {"type": "string"}, "description": "Session continuity ID"},
                ],
                "responses": {
                    "200": response_schema,
                    "default": {
                        "description": "Standard error envelope",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/ErrorEnvelope"}
                            }
                        }
                    }
                },
                "x-focusa": {
                    "family": op.family,
                    "canonical": op.canonical,
                    "budget_profile": op.budget_profile,
                    "side_effect_profile": op.side_effect_profile,
                    "materialization_mode": op.materialization_mode,
                    "supports_side_effect_policy": op.supports_side_effect_policy,
                    "requires_idempotency_key": op.requires_idempotency_key,
                    "requires_if_match_version": op.requires_if_match_version,
                    "permissions_required": op.permissions_required,
                    "deprecation": op.deprecation,
                },
            }));
        }
    }
    Json(json!({
        "openapi": "3.1.0",
        "info": {
            "title": "Focusa Agent Runtime API",
            "version": "v1",
            "description": "Agent-first REST API for Focusa — mission state, Workpoints, trajectory, evidence, metacognition, predictions, and governance.",
        },
        "servers": [{"url": "/", "description": "Focusa daemon"}],
        "paths": paths,
        "components": {
            "schemas": {
                "ErrorEnvelope": {
                    "type": "object",
                    "properties": {
                        "failure_class": {"type": "string"},
                        "message": {"type": "string"},
                        "recovery_hint": {"type": "string"},
                        "next_tools": {"type": "array", "items": {"type": "string"}},
                    },
                },
            },
        },
    }))
}

pub fn routes() -> Router<Arc<AppState>> {
    Router::new()
        .route("/v1/agent/capabilities", get(capabilities_index_handler))
        .route("/v1/agent/schemas", get(list_schemas))
        .route("/v1/agent/schemas/{schema_id}", get(get_schema))
        .route("/v1/openapi.json", get(openapi_export))
}
