pub mod agent_capabilities;
pub mod agent_runtime;
pub mod agent_runtime_delivery;
pub mod agent_runtime_integrity;
pub mod agent_runtime_migration;
pub mod agent_runtime_studio;
#[cfg(test)]
mod agent_runtime_tests;
pub mod ascc;
pub mod attachments;
pub mod autonomy;
pub mod awareness;
pub mod background_jobs;
pub mod bloatgaurd;
pub mod bloatgaurd_optical;
pub mod bounded;
pub mod browser_interop;
pub mod call_stack;
pub mod callgraph;
#[cfg(test)]
mod callgraph_validation_test;
pub mod capabilities;
pub mod capabilities_extra;
pub mod clt;
pub mod commands;
pub mod compaction;
pub mod compaction_policy;
pub mod compaction_policy_resolution;
mod compaction_policy_store;
pub mod constitution;
pub mod context_claims;
pub mod context_cognition;
pub mod context_sources;
pub mod convergence;
pub mod credentials;
pub mod daemon_routing;
pub mod deck;
pub mod device_pairing;
pub mod dxux;
pub mod ecs;
pub mod env;
pub mod license;
pub mod pairing_store;
pub mod role_profiles;
pub mod sync;
pub mod sync_receive;
pub mod sync_transfer;
pub mod turn_recent;
// pub mod events; // deprecated JSONL event tailing
pub mod agent_reminder;
pub mod events_sqlite;
pub mod focus;
pub mod gate;
pub mod health;
pub mod info;
pub mod instances;
pub mod interview_sessions;
pub mod interview_strategy;
pub mod llms_txt;
pub mod mcp;
pub mod memory;
pub mod metacognition;
pub mod mission_canvas_surfaces;
pub mod ontology;
pub mod permissions;
pub mod prediction_authority;
pub mod prediction_authority_canonical;
pub mod predictions;
pub mod preload;
pub mod project;
pub mod project_bootstrap;
mod project_bootstrap_support;
pub mod project_genesis;
mod project_genesis_support;
pub mod proposals;
pub mod provider_execution;
pub mod proxy;
pub mod reflection;
pub mod reflex;
pub mod release;
pub mod resource;
pub mod rfm;
pub mod semantic_integrity;
mod semantic_integrity_executor;
pub mod session;
pub mod silent_sessions;
pub mod silent_sessions_adopt;
pub mod silent_sessions_approvals;
pub mod silent_sessions_authorize;
pub mod silent_sessions_capabilities;
pub mod silent_sessions_config_mutation;
pub mod silent_sessions_config_read;
pub mod silent_sessions_contract;
pub mod silent_sessions_control;
pub mod silent_sessions_create;
pub mod silent_sessions_input;
pub mod silent_sessions_lifecycle;
pub mod silent_sessions_observe;
pub mod silent_sessions_projection;
pub mod silent_sessions_restart;
pub mod silent_sessions_retention;
pub mod silent_sessions_retention_export;
pub mod skills;
pub mod sms;
pub mod snapshots;
pub mod spec_workbench;
pub mod sse;
pub mod subagent;
pub mod task_plans;
pub mod telemetry;
pub mod temporal;
mod temporal_advanced;
#[cfg(test)]
mod temporal_advanced_test;
mod temporal_canonical_mutation;
mod temporal_canonical_operations;
mod temporal_canonical_read;
#[cfg(test)]
mod temporal_canonical_test;
pub mod temporal_clients;
pub mod temporal_closure;
pub mod temporal_conformance;
pub mod temporal_context;
mod temporal_persistence;
pub mod threads;
pub mod tokens;
pub mod training;
pub mod trajectory;
pub mod traverse;
pub mod trust;
pub mod turn;
pub mod update;
mod update_authority;
pub mod utility;
pub mod uxp;
pub mod visual_workflow;
pub mod work_item_temporal;
pub mod work_items;
pub mod work_loop;
pub mod work_rail;
pub mod workpoint;
pub mod workspace_artifacts;
