import { fetchWorkLoop } from './lib/api-client.mjs';
import { listConnections } from './lib/storage.mjs';
import { listNotifications, notificationFromEvent, saveNotification, unreadNotificationCount } from './lib/notifications.mjs';
import { runReliableEventStream } from './lib/reconnect.mjs';

let connection=null;let abort=null;let cursor=null;let notifications=[];
const $=(selector)=>document.querySelector(selector);
function clock(){$('#clock').textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date());}
function stateLabel(node,label,tone='degraded'){node.textContent=label;node.className=`state ${tone}`;}
function renderSignals(){const node=$('#signals');node.replaceChildren();for(const item of notifications.slice(0,6)){const row=document.createElement('div');row.className='signal';const dot=document.createElement('span');dot.className='signal-dot';const copy=document.createElement('div');copy.className='signal-copy';const title=document.createElement('strong');title.textContent=item.title;const body=document.createElement('small');body.textContent=`${item.body} · ${item.timestamp}`;copy.append(title,body);row.append(dot,copy);node.append(row);}if(!notifications.length)node.append(Object.assign(document.createElement('p'),{className:'empty',textContent:'No important signals.'}));$('#signal-count').textContent=String(unreadNotificationCount(notifications));}
async function refresh(){const records=await listConnections();connection=records[0]||null;if(!connection){$('#source').textContent='No daemon connected';stateLabel($('#freshness'),'OFFLINE');return false;}$('#source').textContent=connection.label;$('#daemon-label').textContent=connection.label;try{const body=await fetchWorkLoop({baseUrl:connection.base_url,token:connection.token});const task=body.current_task?.title||body.current_task?.id||'No active task';$('#task').textContent=task;$('#project-status').textContent=body.project_status||body.status||'Unknown';$('#wall-summary').textContent=body.enabled===true?'Live governed execution is visible below.':'The Work Loop is idle; no mutation controls are available on this wall.';$('#projection-time').textContent=new Date().toLocaleTimeString();stateLabel($('#loop-state'),String(body.status||'READY').toUpperCase(),'ready');stateLabel($('#freshness'),'FRESH','ready');return true;}catch(error){stateLabel($('#loop-state'),'DEGRADED');stateLabel($('#freshness'),error?.kind==='unauthenticated'?'UNAUTHORIZED':'STALE');$('#wall-summary').textContent='The last verified wall state is unavailable. Waiting for a safe refresh.';return false;}}
async function start(){notifications=await listNotifications().catch(()=>[]);renderSignals();if(!await refresh())return;abort=new AbortController();await runReliableEventStream({baseUrl:connection.base_url,token:connection.token,initialCursor:cursor,signal:abort.signal,onEvent:async(event)=>{await refresh();const notification=notificationFromEvent(event);if(notification){notifications=await saveNotification(notification);renderSignals();}},commitCursor:async(value)=>{cursor=value;},onState:(value)=>{$('#stream-state').textContent=value.phase;$('#projection-time').textContent=value.phase==='live'?'Live':$('#projection-time').textContent;}}).catch(()=>{if(!abort.signal.aborted){stateLabel($('#freshness'),'RECONNECTING');$('#stream-state').textContent='Reconnecting';}});}
clock();setInterval(clock,30000);start();window.addEventListener('pagehide',()=>abort?.abort());
